/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_J_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[78] = {12, 7, 0, 8, 20, 32, 41, 50, 59, 68, 1, 2, 4, 5, 7, 8, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* f_J:(i0[7],i1[3],i2[],i3[3x3])->(o0[12x7,68nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=sin(a3);
  a5=arg[0]? arg[0][0] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a8=(a2*a7);
  a9=sin(a1);
  a10=sin(a5);
  a11=(a9*a10);
  a8=(a8-a11);
  a8=(a0*a8);
  a11=arg[1]? arg[1][1] : 0;
  a12=cos(a1);
  a10=(a12*a10);
  a13=sin(a1);
  a7=(a13*a7);
  a10=(a10+a7);
  a10=(a11*a10);
  a8=(a8-a10);
  a10=arg[1]? arg[1][2] : 0;
  a7=cos(a3);
  a6=(a7*a6);
  a6=(a10*a6);
  a8=(a8-a6);
  if (res[0]!=0) res[0][0]=a8;
  a8=cos(a5);
  a9=(a9*a8);
  a6=sin(a5);
  a14=(a4*a6);
  a15=(a2*a14);
  a9=(a9+a15);
  a9=(a0*a9);
  a12=(a12*a8);
  a14=(a13*a14);
  a12=(a12-a14);
  a12=(a11*a12);
  a9=(a9+a12);
  a7=(a7*a6);
  a7=(a10*a7);
  a9=(a9-a7);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[0]? arg[0][5] : 0;
  a7=cos(a9);
  a6=arg[0]? arg[0][6] : 0;
  a12=cos(a6);
  a14=(a7*a12);
  a8=arg[3]? arg[3][0] : 0;
  a14=(a14*a8);
  a15=sin(a6);
  a16=(a7*a15);
  a17=arg[3]? arg[3][1] : 0;
  a16=(a16*a17);
  a14=(a14-a16);
  a16=sin(a9);
  a18=arg[3]? arg[3][2] : 0;
  a16=(a16*a18);
  a14=(a14+a16);
  a16=cos(a1);
  a19=sin(a3);
  a20=cos(a5);
  a21=(a19*a20);
  a22=(a16*a21);
  a23=sin(a1);
  a24=sin(a5);
  a25=(a23*a24);
  a22=(a22-a25);
  a22=(a14*a22);
  a25=arg[0]? arg[0][4] : 0;
  a26=sin(a25);
  a27=sin(a9);
  a28=(a26*a27);
  a29=(a28*a12);
  a30=cos(a25);
  a31=sin(a6);
  a32=(a30*a31);
  a29=(a29+a32);
  a29=(a29*a8);
  a32=cos(a6);
  a33=(a30*a32);
  a34=(a28*a15);
  a33=(a33-a34);
  a33=(a33*a17);
  a29=(a29+a33);
  a33=cos(a9);
  a34=(a26*a33);
  a34=(a34*a18);
  a29=(a29-a34);
  a34=arg[0]? arg[0][3] : 0;
  a35=cos(a34);
  a36=cos(a1);
  a24=(a36*a24);
  a37=sin(a1);
  a21=(a37*a21);
  a24=(a24+a21);
  a21=(a35*a24);
  a38=sin(a34);
  a39=cos(a3);
  a20=(a39*a20);
  a40=(a38*a20);
  a21=(a21+a40);
  a21=(a29*a21);
  a22=(a22-a21);
  a21=sin(a25);
  a40=(a21*a31);
  a41=cos(a25);
  a42=(a41*a27);
  a43=(a42*a12);
  a40=(a40-a43);
  a40=(a40*a8);
  a43=(a42*a15);
  a44=(a21*a32);
  a43=(a43+a44);
  a43=(a43*a17);
  a40=(a40+a43);
  a43=(a41*a33);
  a43=(a43*a18);
  a40=(a40+a43);
  a43=cos(a34);
  a44=(a43*a20);
  a45=sin(a34);
  a46=(a45*a24);
  a44=(a44-a46);
  a44=(a40*a44);
  a22=(a22-a44);
  a44=-2.5840000000000002e-01;
  a46=(a44*a35);
  a47=(a46*a24);
  a48=(a44*a38);
  a20=(a48*a20);
  a47=(a47+a20);
  a20=-4.7827999999999998e-01;
  a24=(a20*a24);
  a47=(a47+a24);
  a22=(a22-a47);
  if (res[0]!=0) res[0][2]=a22;
  a22=cos(a5);
  a47=(a23*a22);
  a24=sin(a5);
  a49=(a19*a24);
  a50=(a16*a49);
  a47=(a47+a50);
  a47=(a14*a47);
  a22=(a36*a22);
  a49=(a37*a49);
  a22=(a22-a49);
  a49=(a35*a22);
  a24=(a39*a24);
  a50=(a38*a24);
  a49=(a49-a50);
  a49=(a29*a49);
  a47=(a47+a49);
  a49=(a43*a24);
  a50=(a45*a22);
  a49=(a49+a50);
  a49=(a40*a49);
  a47=(a47-a49);
  a49=(a46*a22);
  a24=(a48*a24);
  a49=(a49-a24);
  a22=(a20*a22);
  a49=(a49+a22);
  a47=(a47+a49);
  if (res[0]!=0) res[0][3]=a47;
  a47=cos(a9);
  a49=cos(a6);
  a22=(a47*a49);
  a24=arg[3]? arg[3][3] : 0;
  a22=(a22*a24);
  a50=sin(a6);
  a51=(a47*a50);
  a52=arg[3]? arg[3][4] : 0;
  a51=(a51*a52);
  a22=(a22-a51);
  a51=sin(a9);
  a53=arg[3]? arg[3][5] : 0;
  a51=(a51*a53);
  a22=(a22+a51);
  a51=cos(a1);
  a54=sin(a3);
  a55=cos(a5);
  a56=(a54*a55);
  a57=(a51*a56);
  a58=sin(a1);
  a59=sin(a5);
  a60=(a58*a59);
  a57=(a57-a60);
  a57=(a22*a57);
  a60=sin(a25);
  a61=sin(a9);
  a62=(a60*a61);
  a63=(a62*a49);
  a64=cos(a25);
  a65=sin(a6);
  a66=(a64*a65);
  a63=(a63+a66);
  a63=(a63*a24);
  a66=cos(a6);
  a67=(a64*a66);
  a68=(a62*a50);
  a67=(a67-a68);
  a67=(a67*a52);
  a63=(a63+a67);
  a67=cos(a9);
  a68=(a60*a67);
  a68=(a68*a53);
  a63=(a63-a68);
  a68=cos(a34);
  a69=cos(a1);
  a59=(a69*a59);
  a70=sin(a1);
  a56=(a70*a56);
  a59=(a59+a56);
  a56=(a68*a59);
  a71=sin(a34);
  a72=cos(a3);
  a55=(a72*a55);
  a73=(a71*a55);
  a56=(a56+a73);
  a56=(a63*a56);
  a57=(a57-a56);
  a56=sin(a25);
  a73=(a56*a65);
  a74=cos(a25);
  a75=(a74*a61);
  a76=(a75*a49);
  a73=(a73-a76);
  a73=(a73*a24);
  a76=(a75*a50);
  a77=(a56*a66);
  a76=(a76+a77);
  a76=(a76*a52);
  a73=(a73+a76);
  a76=(a74*a67);
  a76=(a76*a53);
  a73=(a73+a76);
  a76=cos(a34);
  a77=(a76*a55);
  a78=sin(a34);
  a79=(a78*a59);
  a77=(a77-a79);
  a77=(a73*a77);
  a57=(a57-a77);
  a77=(a44*a68);
  a79=(a77*a59);
  a80=(a44*a71);
  a55=(a80*a55);
  a79=(a79+a55);
  a59=(a20*a59);
  a79=(a79+a59);
  a57=(a57-a79);
  if (res[0]!=0) res[0][4]=a57;
  a57=cos(a5);
  a79=(a58*a57);
  a59=sin(a5);
  a55=(a54*a59);
  a81=(a51*a55);
  a79=(a79+a81);
  a79=(a22*a79);
  a57=(a69*a57);
  a55=(a70*a55);
  a57=(a57-a55);
  a55=(a68*a57);
  a59=(a72*a59);
  a81=(a71*a59);
  a55=(a55-a81);
  a55=(a63*a55);
  a79=(a79+a55);
  a55=(a76*a59);
  a81=(a78*a57);
  a55=(a55+a81);
  a55=(a73*a55);
  a79=(a79-a55);
  a55=(a77*a57);
  a59=(a80*a59);
  a55=(a55-a59);
  a57=(a20*a57);
  a55=(a55+a57);
  a79=(a79+a55);
  if (res[0]!=0) res[0][5]=a79;
  a79=cos(a9);
  a55=cos(a6);
  a57=(a79*a55);
  a59=arg[3]? arg[3][6] : 0;
  a57=(a57*a59);
  a81=sin(a6);
  a82=(a79*a81);
  a83=arg[3]? arg[3][7] : 0;
  a82=(a82*a83);
  a57=(a57-a82);
  a82=sin(a9);
  a84=arg[3]? arg[3][8] : 0;
  a82=(a82*a84);
  a57=(a57+a82);
  a82=cos(a1);
  a85=sin(a3);
  a86=cos(a5);
  a87=(a85*a86);
  a88=(a82*a87);
  a89=sin(a1);
  a90=sin(a5);
  a91=(a89*a90);
  a88=(a88-a91);
  a88=(a57*a88);
  a91=sin(a25);
  a92=sin(a9);
  a93=(a91*a92);
  a94=(a93*a55);
  a95=cos(a25);
  a96=sin(a6);
  a97=(a95*a96);
  a94=(a94+a97);
  a94=(a94*a59);
  a97=cos(a6);
  a98=(a95*a97);
  a99=(a93*a81);
  a98=(a98-a99);
  a98=(a98*a83);
  a94=(a94+a98);
  a98=cos(a9);
  a99=(a91*a98);
  a99=(a99*a84);
  a94=(a94-a99);
  a99=cos(a34);
  a100=cos(a1);
  a90=(a100*a90);
  a101=sin(a1);
  a87=(a101*a87);
  a90=(a90+a87);
  a87=(a99*a90);
  a102=sin(a34);
  a103=cos(a3);
  a86=(a103*a86);
  a104=(a102*a86);
  a87=(a87+a104);
  a87=(a94*a87);
  a88=(a88-a87);
  a87=sin(a25);
  a104=(a87*a96);
  a105=cos(a25);
  a106=(a105*a92);
  a107=(a106*a55);
  a104=(a104-a107);
  a104=(a104*a59);
  a107=(a106*a81);
  a108=(a87*a97);
  a107=(a107+a108);
  a107=(a107*a83);
  a104=(a104+a107);
  a107=(a105*a98);
  a107=(a107*a84);
  a104=(a104+a107);
  a107=cos(a34);
  a108=(a107*a86);
  a109=sin(a34);
  a110=(a109*a90);
  a108=(a108-a110);
  a108=(a104*a108);
  a88=(a88-a108);
  a108=(a44*a99);
  a110=(a108*a90);
  a111=(a44*a102);
  a86=(a111*a86);
  a110=(a110+a86);
  a90=(a20*a90);
  a110=(a110+a90);
  a88=(a88-a110);
  if (res[0]!=0) res[0][6]=a88;
  a88=cos(a5);
  a110=(a89*a88);
  a90=sin(a5);
  a86=(a85*a90);
  a112=(a82*a86);
  a110=(a110+a112);
  a110=(a57*a110);
  a88=(a100*a88);
  a86=(a101*a86);
  a88=(a88-a86);
  a86=(a99*a88);
  a90=(a103*a90);
  a112=(a102*a90);
  a86=(a86-a112);
  a86=(a94*a86);
  a110=(a110+a86);
  a86=(a107*a90);
  a112=(a109*a88);
  a86=(a86+a112);
  a86=(a104*a86);
  a110=(a110-a86);
  a86=(a108*a88);
  a90=(a111*a90);
  a86=(a86-a90);
  a88=(a20*a88);
  a86=(a86+a88);
  a110=(a110+a86);
  if (res[0]!=0) res[0][7]=a110;
  a110=sin(a3);
  a86=(a13*a110);
  a86=(a11*a86);
  a110=(a2*a110);
  a110=(a0*a110);
  a86=(a86-a110);
  a110=cos(a3);
  a110=(a10*a110);
  a86=(a86+a110);
  if (res[0]!=0) res[0][8]=a86;
  a86=sin(a5);
  a110=cos(a3);
  a88=(a86*a110);
  a90=(a2*a88);
  a90=(a0*a90);
  a88=(a13*a88);
  a88=(a11*a88);
  a90=(a90-a88);
  a88=sin(a3);
  a112=(a86*a88);
  a112=(a10*a112);
  a90=(a90+a112);
  if (res[0]!=0) res[0][9]=a90;
  a90=cos(a5);
  a110=(a90*a110);
  a13=(a13*a110);
  a13=(a11*a13);
  a2=(a2*a110);
  a2=(a0*a2);
  a13=(a13-a2);
  a88=(a90*a88);
  a10=(a10*a88);
  a13=(a13-a10);
  if (res[0]!=0) res[0][10]=a13;
  a13=cos(a3);
  a10=(a38*a13);
  a88=sin(a3);
  a2=(a37*a88);
  a110=(a35*a2);
  a10=(a10+a110);
  a10=(a29*a10);
  a88=(a16*a88);
  a88=(a14*a88);
  a10=(a10-a88);
  a88=(a43*a13);
  a110=(a45*a2);
  a88=(a88-a110);
  a88=(a40*a88);
  a10=(a10+a88);
  a13=(a48*a13);
  a88=(a46*a2);
  a13=(a13+a88);
  a2=(a20*a2);
  a13=(a13+a2);
  a10=(a10+a13);
  if (res[0]!=0) res[0][11]=a10;
  a10=sin(a5);
  a13=cos(a3);
  a2=(a10*a13);
  a88=(a16*a2);
  a88=(a14*a88);
  a110=sin(a3);
  a112=(a10*a110);
  a113=(a38*a112);
  a2=(a37*a2);
  a114=(a35*a2);
  a113=(a113-a114);
  a113=(a29*a113);
  a88=(a88+a113);
  a113=(a45*a2);
  a114=(a43*a112);
  a113=(a113+a114);
  a113=(a40*a113);
  a88=(a88+a113);
  a112=(a48*a112);
  a113=(a46*a2);
  a112=(a112-a113);
  a2=(a20*a2);
  a112=(a112-a2);
  a88=(a88+a112);
  if (res[0]!=0) res[0][12]=a88;
  a88=cos(a5);
  a13=(a88*a13);
  a112=(a37*a13);
  a2=(a35*a112);
  a110=(a88*a110);
  a113=(a38*a110);
  a2=(a2-a113);
  a2=(a29*a2);
  a13=(a16*a13);
  a13=(a14*a13);
  a2=(a2-a13);
  a13=(a43*a110);
  a113=(a45*a112);
  a13=(a13+a113);
  a13=(a40*a13);
  a2=(a2-a13);
  a13=(a46*a112);
  a48=(a48*a110);
  a13=(a13-a48);
  a112=(a20*a112);
  a13=(a13+a112);
  a2=(a2+a13);
  if (res[0]!=0) res[0][13]=a2;
  a2=cos(a3);
  a13=(a71*a2);
  a112=sin(a3);
  a48=(a70*a112);
  a110=(a68*a48);
  a13=(a13+a110);
  a13=(a63*a13);
  a112=(a51*a112);
  a112=(a22*a112);
  a13=(a13-a112);
  a112=(a76*a2);
  a110=(a78*a48);
  a112=(a112-a110);
  a112=(a73*a112);
  a13=(a13+a112);
  a2=(a80*a2);
  a112=(a77*a48);
  a2=(a2+a112);
  a48=(a20*a48);
  a2=(a2+a48);
  a13=(a13+a2);
  if (res[0]!=0) res[0][14]=a13;
  a13=sin(a5);
  a2=cos(a3);
  a48=(a13*a2);
  a112=(a51*a48);
  a112=(a22*a112);
  a110=sin(a3);
  a113=(a13*a110);
  a114=(a71*a113);
  a48=(a70*a48);
  a115=(a68*a48);
  a114=(a114-a115);
  a114=(a63*a114);
  a112=(a112+a114);
  a114=(a78*a48);
  a115=(a76*a113);
  a114=(a114+a115);
  a114=(a73*a114);
  a112=(a112+a114);
  a113=(a80*a113);
  a114=(a77*a48);
  a113=(a113-a114);
  a48=(a20*a48);
  a113=(a113-a48);
  a112=(a112+a113);
  if (res[0]!=0) res[0][15]=a112;
  a112=cos(a5);
  a2=(a112*a2);
  a113=(a70*a2);
  a48=(a68*a113);
  a110=(a112*a110);
  a114=(a71*a110);
  a48=(a48-a114);
  a48=(a63*a48);
  a2=(a51*a2);
  a2=(a22*a2);
  a48=(a48-a2);
  a2=(a76*a110);
  a114=(a78*a113);
  a2=(a2+a114);
  a2=(a73*a2);
  a48=(a48-a2);
  a2=(a77*a113);
  a80=(a80*a110);
  a2=(a2-a80);
  a113=(a20*a113);
  a2=(a2+a113);
  a48=(a48+a2);
  if (res[0]!=0) res[0][16]=a48;
  a48=cos(a3);
  a2=(a102*a48);
  a113=sin(a3);
  a80=(a101*a113);
  a110=(a99*a80);
  a2=(a2+a110);
  a2=(a94*a2);
  a113=(a82*a113);
  a113=(a57*a113);
  a2=(a2-a113);
  a113=(a107*a48);
  a110=(a109*a80);
  a113=(a113-a110);
  a113=(a104*a113);
  a2=(a2+a113);
  a48=(a111*a48);
  a113=(a108*a80);
  a48=(a48+a113);
  a80=(a20*a80);
  a48=(a48+a80);
  a2=(a2+a48);
  if (res[0]!=0) res[0][17]=a2;
  a2=sin(a5);
  a48=cos(a3);
  a80=(a2*a48);
  a113=(a82*a80);
  a113=(a57*a113);
  a110=sin(a3);
  a114=(a2*a110);
  a115=(a102*a114);
  a80=(a101*a80);
  a116=(a99*a80);
  a115=(a115-a116);
  a115=(a94*a115);
  a113=(a113+a115);
  a115=(a109*a80);
  a116=(a107*a114);
  a115=(a115+a116);
  a115=(a104*a115);
  a113=(a113+a115);
  a114=(a111*a114);
  a115=(a108*a80);
  a114=(a114-a115);
  a80=(a20*a80);
  a114=(a114-a80);
  a113=(a113+a114);
  if (res[0]!=0) res[0][18]=a113;
  a113=cos(a5);
  a48=(a113*a48);
  a114=(a101*a48);
  a80=(a99*a114);
  a110=(a113*a110);
  a115=(a102*a110);
  a80=(a80-a115);
  a80=(a94*a80);
  a48=(a82*a48);
  a48=(a57*a48);
  a80=(a80-a48);
  a48=(a107*a110);
  a115=(a109*a114);
  a48=(a48+a115);
  a48=(a104*a48);
  a80=(a80-a48);
  a48=(a108*a114);
  a111=(a111*a110);
  a48=(a48-a111);
  a114=(a20*a114);
  a48=(a48+a114);
  a80=(a80+a48);
  if (res[0]!=0) res[0][19]=a80;
  a80=cos(a3);
  a48=sin(a1);
  a114=(a80*a48);
  a114=(a0*a114);
  a111=cos(a1);
  a80=(a80*a111);
  a80=(a11*a80);
  a114=(a114+a80);
  a114=(-a114);
  if (res[0]!=0) res[0][20]=a114;
  a114=cos(a5);
  a80=cos(a1);
  a110=(a114*a80);
  a86=(a86*a4);
  a115=(a86*a48);
  a110=(a110-a115);
  a110=(a0*a110);
  a115=sin(a1);
  a114=(a114*a115);
  a86=(a86*a111);
  a114=(a114+a86);
  a114=(a11*a114);
  a110=(a110-a114);
  if (res[0]!=0) res[0][21]=a110;
  a110=sin(a5);
  a80=(a110*a80);
  a90=(a90*a4);
  a48=(a90*a48);
  a80=(a80+a48);
  a0=(a0*a80);
  a90=(a90*a111);
  a110=(a110*a115);
  a90=(a90-a110);
  a11=(a11*a90);
  a0=(a0+a11);
  if (res[0]!=0) res[0][22]=a0;
  a0=cos(a3);
  a11=cos(a1);
  a90=(a0*a11);
  a110=(a45*a90);
  a110=(a40*a110);
  a115=sin(a1);
  a111=(a0*a115);
  a111=(a14*a111);
  a80=(a35*a90);
  a80=(a29*a80);
  a111=(a111+a80);
  a110=(a110-a111);
  a111=(a46*a90);
  a90=(a20*a90);
  a111=(a111+a90);
  a110=(a110-a111);
  if (res[0]!=0) res[0][23]=a110;
  a110=cos(a5);
  a111=cos(a1);
  a90=(a110*a111);
  a80=(a10*a19);
  a48=(a80*a115);
  a90=(a90-a48);
  a90=(a14*a90);
  a48=sin(a1);
  a4=(a110*a48);
  a114=(a80*a11);
  a4=(a4+a114);
  a114=(a35*a4);
  a114=(a29*a114);
  a90=(a90-a114);
  a114=(a45*a4);
  a114=(a40*a114);
  a90=(a90+a114);
  a114=(a46*a4);
  a4=(a20*a4);
  a114=(a114+a4);
  a90=(a90-a114);
  if (res[0]!=0) res[0][24]=a90;
  a90=sin(a5);
  a111=(a90*a111);
  a19=(a88*a19);
  a115=(a19*a115);
  a111=(a111+a115);
  a14=(a14*a111);
  a11=(a19*a11);
  a48=(a90*a48);
  a11=(a11-a48);
  a48=(a35*a11);
  a48=(a29*a48);
  a14=(a14+a48);
  a48=(a45*a11);
  a48=(a40*a48);
  a14=(a14-a48);
  a46=(a46*a11);
  a11=(a20*a11);
  a46=(a46+a11);
  a14=(a14+a46);
  if (res[0]!=0) res[0][25]=a14;
  a14=cos(a3);
  a46=cos(a1);
  a11=(a14*a46);
  a48=(a78*a11);
  a48=(a73*a48);
  a111=sin(a1);
  a115=(a14*a111);
  a115=(a22*a115);
  a114=(a68*a11);
  a114=(a63*a114);
  a115=(a115+a114);
  a48=(a48-a115);
  a115=(a77*a11);
  a11=(a20*a11);
  a115=(a115+a11);
  a48=(a48-a115);
  if (res[0]!=0) res[0][26]=a48;
  a48=cos(a5);
  a115=cos(a1);
  a11=(a48*a115);
  a114=(a13*a54);
  a4=(a114*a111);
  a11=(a11-a4);
  a11=(a22*a11);
  a4=sin(a1);
  a86=(a48*a4);
  a116=(a114*a46);
  a86=(a86+a116);
  a116=(a68*a86);
  a116=(a63*a116);
  a11=(a11-a116);
  a116=(a78*a86);
  a116=(a73*a116);
  a11=(a11+a116);
  a116=(a77*a86);
  a86=(a20*a86);
  a116=(a116+a86);
  a11=(a11-a116);
  if (res[0]!=0) res[0][27]=a11;
  a11=sin(a5);
  a115=(a11*a115);
  a54=(a112*a54);
  a111=(a54*a111);
  a115=(a115+a111);
  a22=(a22*a115);
  a46=(a54*a46);
  a4=(a11*a4);
  a46=(a46-a4);
  a4=(a68*a46);
  a4=(a63*a4);
  a22=(a22+a4);
  a4=(a78*a46);
  a4=(a73*a4);
  a22=(a22-a4);
  a77=(a77*a46);
  a46=(a20*a46);
  a77=(a77+a46);
  a22=(a22+a77);
  if (res[0]!=0) res[0][28]=a22;
  a22=cos(a3);
  a77=cos(a1);
  a46=(a22*a77);
  a4=(a109*a46);
  a4=(a104*a4);
  a115=sin(a1);
  a111=(a22*a115);
  a111=(a57*a111);
  a116=(a99*a46);
  a116=(a94*a116);
  a111=(a111+a116);
  a4=(a4-a111);
  a111=(a108*a46);
  a46=(a20*a46);
  a111=(a111+a46);
  a4=(a4-a111);
  if (res[0]!=0) res[0][29]=a4;
  a4=cos(a5);
  a111=cos(a1);
  a46=(a4*a111);
  a116=(a2*a85);
  a86=(a116*a115);
  a46=(a46-a86);
  a46=(a57*a46);
  a1=sin(a1);
  a86=(a4*a1);
  a117=(a116*a77);
  a86=(a86+a117);
  a117=(a99*a86);
  a117=(a94*a117);
  a46=(a46-a117);
  a117=(a109*a86);
  a117=(a104*a117);
  a46=(a46+a117);
  a117=(a108*a86);
  a86=(a20*a86);
  a117=(a117+a86);
  a46=(a46-a117);
  if (res[0]!=0) res[0][30]=a46;
  a5=sin(a5);
  a111=(a5*a111);
  a85=(a113*a85);
  a115=(a85*a115);
  a111=(a111+a115);
  a57=(a57*a111);
  a77=(a85*a77);
  a1=(a5*a1);
  a77=(a77-a1);
  a1=(a99*a77);
  a1=(a94*a1);
  a57=(a57+a1);
  a1=(a109*a77);
  a1=(a104*a1);
  a57=(a57-a1);
  a108=(a108*a77);
  a20=(a20*a77);
  a108=(a108+a20);
  a57=(a57+a108);
  if (res[0]!=0) res[0][31]=a57;
  a57=sin(a3);
  a108=cos(a34);
  a20=(a57*a108);
  a77=(a0*a37);
  a1=sin(a34);
  a111=(a77*a1);
  a20=(a20+a111);
  a20=(a29*a20);
  a111=cos(a34);
  a115=(a77*a111);
  a46=sin(a34);
  a117=(a57*a46);
  a115=(a115-a117);
  a115=(a40*a115);
  a20=(a20+a115);
  a115=(a44*a108);
  a117=(a57*a115);
  a86=(a44*a1);
  a118=(a77*a86);
  a117=(a117+a118);
  a20=(a20+a117);
  if (res[0]!=0) res[0][32]=a20;
  a20=(a110*a36);
  a117=(a80*a37);
  a20=(a20-a117);
  a117=(a20*a1);
  a10=(a10*a39);
  a118=(a10*a108);
  a117=(a117+a118);
  a117=(a29*a117);
  a118=(a20*a111);
  a119=(a10*a46);
  a118=(a118-a119);
  a118=(a40*a118);
  a117=(a117+a118);
  a118=(a20*a86);
  a119=(a10*a115);
  a118=(a118+a119);
  a117=(a117+a118);
  a117=(-a117);
  if (res[0]!=0) res[0][33]=a117;
  a88=(a88*a39);
  a108=(a88*a108);
  a37=(a19*a37);
  a36=(a90*a36);
  a37=(a37+a36);
  a1=(a37*a1);
  a108=(a108-a1);
  a29=(a29*a108);
  a46=(a88*a46);
  a111=(a37*a111);
  a46=(a46+a111);
  a40=(a40*a46);
  a29=(a29-a40);
  a115=(a88*a115);
  a86=(a37*a86);
  a115=(a115-a86);
  a29=(a29+a115);
  if (res[0]!=0) res[0][34]=a29;
  a29=sin(a3);
  a115=cos(a34);
  a86=(a29*a115);
  a40=(a14*a70);
  a46=sin(a34);
  a111=(a40*a46);
  a86=(a86+a111);
  a86=(a63*a86);
  a111=cos(a34);
  a108=(a40*a111);
  a1=sin(a34);
  a36=(a29*a1);
  a108=(a108-a36);
  a108=(a73*a108);
  a86=(a86+a108);
  a108=(a44*a115);
  a36=(a29*a108);
  a39=(a44*a46);
  a117=(a40*a39);
  a36=(a36+a117);
  a86=(a86+a36);
  if (res[0]!=0) res[0][35]=a86;
  a86=(a48*a69);
  a36=(a114*a70);
  a86=(a86-a36);
  a36=(a86*a46);
  a13=(a13*a72);
  a117=(a13*a115);
  a36=(a36+a117);
  a36=(a63*a36);
  a117=(a86*a111);
  a118=(a13*a1);
  a117=(a117-a118);
  a117=(a73*a117);
  a36=(a36+a117);
  a117=(a86*a39);
  a118=(a13*a108);
  a117=(a117+a118);
  a36=(a36+a117);
  a36=(-a36);
  if (res[0]!=0) res[0][36]=a36;
  a112=(a112*a72);
  a115=(a112*a115);
  a70=(a54*a70);
  a69=(a11*a69);
  a70=(a70+a69);
  a46=(a70*a46);
  a115=(a115-a46);
  a63=(a63*a115);
  a1=(a112*a1);
  a111=(a70*a111);
  a1=(a1+a111);
  a73=(a73*a1);
  a63=(a63-a73);
  a108=(a112*a108);
  a39=(a70*a39);
  a108=(a108-a39);
  a63=(a63+a108);
  if (res[0]!=0) res[0][37]=a63;
  a3=sin(a3);
  a63=cos(a34);
  a108=(a3*a63);
  a39=(a22*a101);
  a73=sin(a34);
  a1=(a39*a73);
  a108=(a108+a1);
  a108=(a94*a108);
  a1=cos(a34);
  a111=(a39*a1);
  a34=sin(a34);
  a115=(a3*a34);
  a111=(a111-a115);
  a111=(a104*a111);
  a108=(a108+a111);
  a111=(a44*a63);
  a115=(a3*a111);
  a44=(a44*a73);
  a46=(a39*a44);
  a115=(a115+a46);
  a108=(a108+a115);
  if (res[0]!=0) res[0][38]=a108;
  a108=(a4*a100);
  a115=(a116*a101);
  a108=(a108-a115);
  a115=(a108*a73);
  a2=(a2*a103);
  a46=(a2*a63);
  a115=(a115+a46);
  a115=(a94*a115);
  a46=(a108*a1);
  a69=(a2*a34);
  a46=(a46-a69);
  a46=(a104*a46);
  a115=(a115+a46);
  a46=(a108*a44);
  a69=(a2*a111);
  a46=(a46+a69);
  a115=(a115+a46);
  a115=(-a115);
  if (res[0]!=0) res[0][39]=a115;
  a113=(a113*a103);
  a63=(a113*a63);
  a101=(a85*a101);
  a100=(a5*a100);
  a101=(a101+a100);
  a73=(a101*a73);
  a63=(a63-a73);
  a94=(a94*a63);
  a34=(a113*a34);
  a1=(a101*a1);
  a34=(a34+a1);
  a104=(a104*a34);
  a94=(a94-a104);
  a111=(a113*a111);
  a44=(a101*a44);
  a111=(a111-a44);
  a94=(a94+a111);
  if (res[0]!=0) res[0][40]=a94;
  a94=(a57*a38);
  a111=(a77*a35);
  a94=(a94-a111);
  a111=cos(a25);
  a44=(a27*a111);
  a104=(a12*a44);
  a34=sin(a25);
  a1=(a31*a34);
  a104=(a104-a1);
  a104=(a8*a104);
  a34=(a32*a34);
  a44=(a15*a44);
  a34=(a34+a44);
  a34=(a17*a34);
  a104=(a104-a34);
  a111=(a33*a111);
  a111=(a18*a111);
  a104=(a104-a111);
  a111=(a94*a104);
  a77=(a77*a45);
  a57=(a57*a43);
  a77=(a77+a57);
  a57=cos(a25);
  a31=(a31*a57);
  a34=sin(a25);
  a27=(a27*a34);
  a44=(a12*a27);
  a31=(a31+a44);
  a31=(a8*a31);
  a32=(a32*a57);
  a27=(a15*a27);
  a32=(a32-a27);
  a32=(a17*a32);
  a31=(a31+a32);
  a33=(a33*a34);
  a33=(a18*a33);
  a31=(a31-a33);
  a33=(a77*a31);
  a111=(a111+a33);
  if (res[0]!=0) res[0][41]=a111;
  a111=(a20*a35);
  a33=(a10*a38);
  a111=(a111-a33);
  a33=(a111*a104);
  a20=(a20*a45);
  a10=(a10*a43);
  a20=(a20+a10);
  a10=(a20*a31);
  a33=(a33-a10);
  if (res[0]!=0) res[0][42]=a33;
  a35=(a37*a35);
  a38=(a88*a38);
  a35=(a35+a38);
  a104=(a35*a104);
  a88=(a88*a43);
  a37=(a37*a45);
  a88=(a88-a37);
  a31=(a88*a31);
  a104=(a104+a31);
  if (res[0]!=0) res[0][43]=a104;
  a104=(a29*a71);
  a31=(a40*a68);
  a104=(a104-a31);
  a31=cos(a25);
  a37=(a61*a31);
  a45=(a49*a37);
  a43=sin(a25);
  a38=(a65*a43);
  a45=(a45-a38);
  a45=(a24*a45);
  a43=(a66*a43);
  a37=(a50*a37);
  a43=(a43+a37);
  a43=(a52*a43);
  a45=(a45-a43);
  a31=(a67*a31);
  a31=(a53*a31);
  a45=(a45-a31);
  a31=(a104*a45);
  a40=(a40*a78);
  a29=(a29*a76);
  a40=(a40+a29);
  a29=cos(a25);
  a65=(a65*a29);
  a43=sin(a25);
  a61=(a61*a43);
  a37=(a49*a61);
  a65=(a65+a37);
  a65=(a24*a65);
  a66=(a66*a29);
  a61=(a50*a61);
  a66=(a66-a61);
  a66=(a52*a66);
  a65=(a65+a66);
  a67=(a67*a43);
  a67=(a53*a67);
  a65=(a65-a67);
  a67=(a40*a65);
  a31=(a31+a67);
  if (res[0]!=0) res[0][44]=a31;
  a31=(a86*a68);
  a67=(a13*a71);
  a31=(a31-a67);
  a67=(a31*a45);
  a86=(a86*a78);
  a13=(a13*a76);
  a86=(a86+a13);
  a13=(a86*a65);
  a67=(a67-a13);
  if (res[0]!=0) res[0][45]=a67;
  a68=(a70*a68);
  a71=(a112*a71);
  a68=(a68+a71);
  a45=(a68*a45);
  a112=(a112*a76);
  a70=(a70*a78);
  a112=(a112-a70);
  a65=(a112*a65);
  a45=(a45+a65);
  if (res[0]!=0) res[0][46]=a45;
  a45=(a3*a102);
  a65=(a39*a99);
  a45=(a45-a65);
  a65=cos(a25);
  a70=(a92*a65);
  a78=(a55*a70);
  a76=sin(a25);
  a71=(a96*a76);
  a78=(a78-a71);
  a78=(a59*a78);
  a76=(a97*a76);
  a70=(a81*a70);
  a76=(a76+a70);
  a76=(a83*a76);
  a78=(a78-a76);
  a65=(a98*a65);
  a65=(a84*a65);
  a78=(a78-a65);
  a65=(a45*a78);
  a39=(a39*a109);
  a3=(a3*a107);
  a39=(a39+a3);
  a3=cos(a25);
  a96=(a96*a3);
  a25=sin(a25);
  a92=(a92*a25);
  a76=(a55*a92);
  a96=(a96+a76);
  a96=(a59*a96);
  a97=(a97*a3);
  a92=(a81*a92);
  a97=(a97-a92);
  a97=(a83*a97);
  a96=(a96+a97);
  a98=(a98*a25);
  a98=(a84*a98);
  a96=(a96-a98);
  a98=(a39*a96);
  a65=(a65+a98);
  if (res[0]!=0) res[0][47]=a65;
  a65=(a108*a99);
  a98=(a2*a102);
  a65=(a65-a98);
  a98=(a65*a78);
  a108=(a108*a109);
  a2=(a2*a107);
  a108=(a108+a2);
  a2=(a108*a96);
  a98=(a98-a2);
  if (res[0]!=0) res[0][48]=a98;
  a99=(a101*a99);
  a102=(a113*a102);
  a99=(a99+a102);
  a78=(a99*a78);
  a113=(a113*a107);
  a101=(a101*a109);
  a113=(a113-a101);
  a96=(a113*a96);
  a78=(a78+a96);
  if (res[0]!=0) res[0][49]=a78;
  a0=(a0*a16);
  a78=sin(a9);
  a96=(a15*a78);
  a96=(a17*a96);
  a78=(a12*a78);
  a78=(a8*a78);
  a96=(a96-a78);
  a78=cos(a9);
  a78=(a18*a78);
  a96=(a96+a78);
  a78=(a0*a96);
  a101=cos(a9);
  a109=(a26*a101);
  a107=(a12*a109);
  a107=(a8*a107);
  a109=(a15*a109);
  a109=(a17*a109);
  a107=(a107-a109);
  a109=sin(a9);
  a26=(a26*a109);
  a26=(a18*a26);
  a107=(a107+a26);
  a26=(a94*a107);
  a78=(a78+a26);
  a101=(a41*a101);
  a15=(a15*a101);
  a15=(a17*a15);
  a12=(a12*a101);
  a12=(a8*a12);
  a15=(a15-a12);
  a41=(a41*a109);
  a18=(a18*a41);
  a15=(a15-a18);
  a18=(a77*a15);
  a78=(a78+a18);
  if (res[0]!=0) res[0][50]=a78;
  a80=(a80*a16);
  a110=(a110*a23);
  a80=(a80+a110);
  a110=(a80*a96);
  a78=(a111*a107);
  a110=(a110+a78);
  a78=(a20*a15);
  a110=(a110-a78);
  if (res[0]!=0) res[0][51]=a110;
  a90=(a90*a23);
  a19=(a19*a16);
  a90=(a90-a19);
  a96=(a90*a96);
  a107=(a35*a107);
  a96=(a96+a107);
  a15=(a88*a15);
  a96=(a96+a15);
  if (res[0]!=0) res[0][52]=a96;
  a14=(a14*a51);
  a96=sin(a9);
  a15=(a50*a96);
  a15=(a52*a15);
  a96=(a49*a96);
  a96=(a24*a96);
  a15=(a15-a96);
  a96=cos(a9);
  a96=(a53*a96);
  a15=(a15+a96);
  a96=(a14*a15);
  a107=cos(a9);
  a19=(a60*a107);
  a16=(a49*a19);
  a16=(a24*a16);
  a19=(a50*a19);
  a19=(a52*a19);
  a16=(a16-a19);
  a19=sin(a9);
  a60=(a60*a19);
  a60=(a53*a60);
  a16=(a16+a60);
  a60=(a104*a16);
  a96=(a96+a60);
  a107=(a74*a107);
  a50=(a50*a107);
  a50=(a52*a50);
  a49=(a49*a107);
  a49=(a24*a49);
  a50=(a50-a49);
  a74=(a74*a19);
  a53=(a53*a74);
  a50=(a50-a53);
  a53=(a40*a50);
  a96=(a96+a53);
  if (res[0]!=0) res[0][53]=a96;
  a114=(a114*a51);
  a48=(a48*a58);
  a114=(a114+a48);
  a48=(a114*a15);
  a96=(a31*a16);
  a48=(a48+a96);
  a96=(a86*a50);
  a48=(a48-a96);
  if (res[0]!=0) res[0][54]=a48;
  a11=(a11*a58);
  a54=(a54*a51);
  a11=(a11-a54);
  a15=(a11*a15);
  a16=(a68*a16);
  a15=(a15+a16);
  a50=(a112*a50);
  a15=(a15+a50);
  if (res[0]!=0) res[0][55]=a15;
  a22=(a22*a82);
  a15=sin(a9);
  a50=(a81*a15);
  a50=(a83*a50);
  a15=(a55*a15);
  a15=(a59*a15);
  a50=(a50-a15);
  a15=cos(a9);
  a15=(a84*a15);
  a50=(a50+a15);
  a15=(a22*a50);
  a16=cos(a9);
  a54=(a91*a16);
  a51=(a55*a54);
  a51=(a59*a51);
  a54=(a81*a54);
  a54=(a83*a54);
  a51=(a51-a54);
  a9=sin(a9);
  a91=(a91*a9);
  a91=(a84*a91);
  a51=(a51+a91);
  a91=(a45*a51);
  a15=(a15+a91);
  a16=(a105*a16);
  a81=(a81*a16);
  a81=(a83*a81);
  a55=(a55*a16);
  a55=(a59*a55);
  a81=(a81-a55);
  a105=(a105*a9);
  a84=(a84*a105);
  a81=(a81-a84);
  a84=(a39*a81);
  a15=(a15+a84);
  if (res[0]!=0) res[0][56]=a15;
  a116=(a116*a82);
  a4=(a4*a89);
  a116=(a116+a4);
  a4=(a116*a50);
  a15=(a65*a51);
  a4=(a4+a15);
  a15=(a108*a81);
  a4=(a4-a15);
  if (res[0]!=0) res[0][57]=a4;
  a5=(a5*a89);
  a85=(a85*a82);
  a5=(a5-a85);
  a50=(a5*a50);
  a51=(a99*a51);
  a50=(a50+a51);
  a81=(a113*a81);
  a50=(a50+a81);
  if (res[0]!=0) res[0][58]=a50;
  a50=cos(a6);
  a81=(a30*a50);
  a51=sin(a6);
  a85=(a28*a51);
  a81=(a81-a85);
  a81=(a8*a81);
  a85=sin(a6);
  a30=(a30*a85);
  a82=cos(a6);
  a28=(a28*a82);
  a30=(a30+a28);
  a30=(a17*a30);
  a81=(a81-a30);
  a94=(a94*a81);
  a30=(a7*a51);
  a30=(a8*a30);
  a7=(a7*a82);
  a7=(a17*a7);
  a30=(a30+a7);
  a0=(a0*a30);
  a94=(a94-a0);
  a50=(a21*a50);
  a51=(a42*a51);
  a50=(a50+a51);
  a8=(a8*a50);
  a42=(a42*a82);
  a21=(a21*a85);
  a42=(a42-a21);
  a17=(a17*a42);
  a8=(a8+a17);
  a77=(a77*a8);
  a94=(a94+a77);
  if (res[0]!=0) res[0][59]=a94;
  a111=(a111*a81);
  a80=(a80*a30);
  a111=(a111-a80);
  a20=(a20*a8);
  a111=(a111-a20);
  if (res[0]!=0) res[0][60]=a111;
  a35=(a35*a81);
  a90=(a90*a30);
  a35=(a35-a90);
  a88=(a88*a8);
  a35=(a35+a88);
  if (res[0]!=0) res[0][61]=a35;
  a35=cos(a6);
  a88=(a64*a35);
  a8=sin(a6);
  a90=(a62*a8);
  a88=(a88-a90);
  a88=(a24*a88);
  a90=sin(a6);
  a64=(a64*a90);
  a30=cos(a6);
  a62=(a62*a30);
  a64=(a64+a62);
  a64=(a52*a64);
  a88=(a88-a64);
  a104=(a104*a88);
  a64=(a47*a8);
  a64=(a24*a64);
  a47=(a47*a30);
  a47=(a52*a47);
  a64=(a64+a47);
  a14=(a14*a64);
  a104=(a104-a14);
  a35=(a56*a35);
  a8=(a75*a8);
  a35=(a35+a8);
  a24=(a24*a35);
  a75=(a75*a30);
  a56=(a56*a90);
  a75=(a75-a56);
  a52=(a52*a75);
  a24=(a24+a52);
  a40=(a40*a24);
  a104=(a104+a40);
  if (res[0]!=0) res[0][62]=a104;
  a31=(a31*a88);
  a114=(a114*a64);
  a31=(a31-a114);
  a86=(a86*a24);
  a31=(a31-a86);
  if (res[0]!=0) res[0][63]=a31;
  a68=(a68*a88);
  a11=(a11*a64);
  a68=(a68-a11);
  a112=(a112*a24);
  a68=(a68+a112);
  if (res[0]!=0) res[0][64]=a68;
  a68=cos(a6);
  a112=(a95*a68);
  a24=sin(a6);
  a11=(a93*a24);
  a112=(a112-a11);
  a112=(a59*a112);
  a11=sin(a6);
  a95=(a95*a11);
  a6=cos(a6);
  a93=(a93*a6);
  a95=(a95+a93);
  a95=(a83*a95);
  a112=(a112-a95);
  a45=(a45*a112);
  a95=(a79*a24);
  a95=(a59*a95);
  a79=(a79*a6);
  a79=(a83*a79);
  a95=(a95+a79);
  a22=(a22*a95);
  a45=(a45-a22);
  a68=(a87*a68);
  a24=(a106*a24);
  a68=(a68+a24);
  a59=(a59*a68);
  a106=(a106*a6);
  a87=(a87*a11);
  a106=(a106-a87);
  a83=(a83*a106);
  a59=(a59+a83);
  a39=(a39*a59);
  a45=(a45+a39);
  if (res[0]!=0) res[0][65]=a45;
  a65=(a65*a112);
  a116=(a116*a95);
  a65=(a65-a116);
  a108=(a108*a59);
  a65=(a65-a108);
  if (res[0]!=0) res[0][66]=a65;
  a99=(a99*a112);
  a5=(a5*a95);
  a99=(a99-a5);
  a113=(a113*a59);
  a99=(a99+a113);
  if (res[0]!=0) res[0][67]=a99;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_J_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_J(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[207];
  casadi_int *iw = 0;
  const casadi_real* arg[4] = {0};
  casadi_real* res[1] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+87);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+87);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+10, casadi_s2, w+87);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+10, casadi_s3, w+87);
  --resc;
  res[0] = w+19;
  i = f_J(arg, res, iw, w+87, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s4, res[0]);
}
#endif

casadi_int main_f_J(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[207];
  const casadi_real* arg[4];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+7;
  arg[2] = w+10;
  arg[3] = w+10;
  res[0] = w+19;
  a = w;
  for (j=0; j<19; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_J(arg, res, iw, w+87, 0);
  if (flag) return flag;
  r = w+19;
  for (j=0; j<68; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[4];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_J(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_J")==0) {
    mex_f_J(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_J'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_J")==0) {
    return main_f_J(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_J'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
