/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_J_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[3] = {0, 0, 0};
static const casadi_int casadi_s2[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[72] = {12, 7, 0, 8, 20, 32, 44, 50, 56, 62, 1, 2, 4, 5, 7, 8, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 6, 7, 8, 9, 10, 11, 6, 7, 8, 9, 10, 11, 6, 7, 8, 9, 10, 11};

/* f_J:(i0[7],i1[],i2[3x2],i3[3x2])->(o0[12x7,62nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[0]? arg[0][3] : 0;
  a1=cos(a0);
  a2=arg[2]? arg[2][0] : 0;
  a1=(a1*a2);
  a3=sin(a0);
  a4=arg[2]? arg[2][1] : 0;
  a3=(a3*a4);
  a1=(a1-a3);
  a3=arg[0]? arg[0][2] : 0;
  a5=cos(a3);
  a6=arg[0]? arg[0][1] : 0;
  a7=sin(a6);
  a8=arg[0]? arg[0][0] : 0;
  a9=cos(a8);
  a10=(a7*a9);
  a11=(a5*a10);
  a12=sin(a3);
  a13=sin(a8);
  a14=(a12*a13);
  a11=(a11-a14);
  a11=(a1*a11);
  a14=sin(a0);
  a14=(a14*a2);
  a15=cos(a0);
  a15=(a15*a4);
  a14=(a14+a15);
  a15=cos(a3);
  a13=(a15*a13);
  a16=sin(a3);
  a10=(a16*a10);
  a13=(a13+a10);
  a10=(a14*a13);
  a11=(a11-a10);
  a10=arg[2]? arg[2][2] : 0;
  a17=cos(a6);
  a9=(a17*a9);
  a9=(a10*a9);
  a11=(a11-a9);
  a9=-2.5000000000000000e-01;
  a13=(a9*a13);
  a11=(a11-a13);
  if (res[0]!=0) res[0][0]=a11;
  a11=cos(a8);
  a13=(a12*a11);
  a18=sin(a8);
  a19=(a7*a18);
  a20=(a5*a19);
  a13=(a13+a20);
  a13=(a1*a13);
  a11=(a15*a11);
  a19=(a16*a19);
  a11=(a11-a19);
  a19=(a14*a11);
  a13=(a13+a19);
  a17=(a17*a18);
  a17=(a10*a17);
  a13=(a13-a17);
  a11=(a9*a11);
  a13=(a13+a11);
  if (res[0]!=0) res[0][1]=a13;
  a13=cos(a0);
  a11=arg[2]? arg[2][3] : 0;
  a13=(a13*a11);
  a17=sin(a0);
  a18=arg[2]? arg[2][4] : 0;
  a17=(a17*a18);
  a13=(a13-a17);
  a17=cos(a3);
  a19=sin(a6);
  a20=cos(a8);
  a21=(a19*a20);
  a22=(a17*a21);
  a23=sin(a3);
  a24=sin(a8);
  a25=(a23*a24);
  a22=(a22-a25);
  a22=(a13*a22);
  a25=sin(a0);
  a25=(a25*a11);
  a26=cos(a0);
  a26=(a26*a18);
  a25=(a25+a26);
  a26=cos(a3);
  a24=(a26*a24);
  a27=sin(a3);
  a21=(a27*a21);
  a24=(a24+a21);
  a21=(a25*a24);
  a22=(a22-a21);
  a21=arg[2]? arg[2][5] : 0;
  a28=cos(a6);
  a20=(a28*a20);
  a20=(a21*a20);
  a22=(a22-a20);
  a24=(a9*a24);
  a22=(a22-a24);
  if (res[0]!=0) res[0][2]=a22;
  a22=cos(a8);
  a24=(a23*a22);
  a20=sin(a8);
  a29=(a19*a20);
  a30=(a17*a29);
  a24=(a24+a30);
  a24=(a13*a24);
  a22=(a26*a22);
  a29=(a27*a29);
  a22=(a22-a29);
  a29=(a25*a22);
  a24=(a24+a29);
  a28=(a28*a20);
  a28=(a21*a28);
  a24=(a24-a28);
  a22=(a9*a22);
  a24=(a24+a22);
  if (res[0]!=0) res[0][3]=a24;
  a24=arg[0]? arg[0][5] : 0;
  a22=cos(a24);
  a28=arg[0]? arg[0][6] : 0;
  a20=cos(a28);
  a29=(a22*a20);
  a30=arg[3]? arg[3][0] : 0;
  a29=(a29*a30);
  a31=sin(a28);
  a32=(a22*a31);
  a33=arg[3]? arg[3][1] : 0;
  a32=(a32*a33);
  a29=(a29-a32);
  a32=sin(a24);
  a34=arg[3]? arg[3][2] : 0;
  a32=(a32*a34);
  a29=(a29+a32);
  a32=cos(a0);
  a35=cos(a3);
  a36=sin(a6);
  a37=cos(a8);
  a38=(a36*a37);
  a39=(a35*a38);
  a40=sin(a3);
  a41=sin(a8);
  a42=(a40*a41);
  a39=(a39-a42);
  a42=(a32*a39);
  a43=sin(a0);
  a44=cos(a3);
  a41=(a44*a41);
  a45=sin(a3);
  a38=(a45*a38);
  a41=(a41+a38);
  a38=(a43*a41);
  a42=(a42-a38);
  a42=(a29*a42);
  a38=arg[0]? arg[0][4] : 0;
  a46=sin(a38);
  a47=sin(a24);
  a48=(a46*a47);
  a49=(a48*a20);
  a50=cos(a38);
  a51=sin(a28);
  a52=(a50*a51);
  a49=(a49+a52);
  a49=(a49*a30);
  a52=cos(a28);
  a53=(a50*a52);
  a54=(a48*a31);
  a53=(a53-a54);
  a53=(a53*a33);
  a49=(a49+a53);
  a53=cos(a24);
  a54=(a46*a53);
  a54=(a54*a34);
  a49=(a49-a54);
  a54=cos(a0);
  a55=(a54*a41);
  a56=sin(a0);
  a57=(a56*a39);
  a55=(a55+a57);
  a55=(a49*a55);
  a42=(a42-a55);
  a55=sin(a38);
  a57=(a55*a51);
  a58=cos(a38);
  a59=(a58*a47);
  a60=(a59*a20);
  a57=(a57-a60);
  a57=(a57*a30);
  a60=(a59*a31);
  a61=(a55*a52);
  a60=(a60+a61);
  a60=(a60*a33);
  a57=(a57+a60);
  a60=(a58*a53);
  a60=(a60*a34);
  a57=(a57+a60);
  a60=cos(a6);
  a37=(a60*a37);
  a37=(a57*a37);
  a42=(a42-a37);
  a37=(a9*a54);
  a61=(a37*a41);
  a62=(a9*a56);
  a39=(a62*a39);
  a61=(a61+a39);
  a41=(a9*a41);
  a61=(a61+a41);
  a42=(a42-a61);
  if (res[0]!=0) res[0][4]=a42;
  a42=cos(a8);
  a61=(a40*a42);
  a41=sin(a8);
  a39=(a36*a41);
  a63=(a35*a39);
  a61=(a61+a63);
  a63=(a32*a61);
  a42=(a44*a42);
  a39=(a45*a39);
  a42=(a42-a39);
  a39=(a43*a42);
  a63=(a63+a39);
  a63=(a29*a63);
  a39=(a54*a42);
  a64=(a56*a61);
  a39=(a39-a64);
  a39=(a49*a39);
  a63=(a63+a39);
  a41=(a60*a41);
  a41=(a57*a41);
  a63=(a63-a41);
  a41=(a37*a42);
  a61=(a62*a61);
  a41=(a41-a61);
  a42=(a9*a42);
  a41=(a41+a42);
  a63=(a63+a41);
  if (res[0]!=0) res[0][5]=a63;
  a63=cos(a24);
  a41=cos(a28);
  a42=(a63*a41);
  a61=arg[3]? arg[3][3] : 0;
  a42=(a42*a61);
  a39=sin(a28);
  a64=(a63*a39);
  a65=arg[3]? arg[3][4] : 0;
  a64=(a64*a65);
  a42=(a42-a64);
  a64=sin(a24);
  a66=arg[3]? arg[3][5] : 0;
  a64=(a64*a66);
  a42=(a42+a64);
  a64=cos(a0);
  a67=cos(a3);
  a68=sin(a6);
  a69=cos(a8);
  a70=(a68*a69);
  a71=(a67*a70);
  a72=sin(a3);
  a73=sin(a8);
  a74=(a72*a73);
  a71=(a71-a74);
  a74=(a64*a71);
  a75=sin(a0);
  a76=cos(a3);
  a73=(a76*a73);
  a77=sin(a3);
  a70=(a77*a70);
  a73=(a73+a70);
  a70=(a75*a73);
  a74=(a74-a70);
  a74=(a42*a74);
  a70=sin(a38);
  a78=sin(a24);
  a79=(a70*a78);
  a80=(a79*a41);
  a81=cos(a38);
  a82=sin(a28);
  a83=(a81*a82);
  a80=(a80+a83);
  a80=(a80*a61);
  a83=cos(a28);
  a84=(a81*a83);
  a85=(a79*a39);
  a84=(a84-a85);
  a84=(a84*a65);
  a80=(a80+a84);
  a84=cos(a24);
  a85=(a70*a84);
  a85=(a85*a66);
  a80=(a80-a85);
  a85=cos(a0);
  a86=(a85*a73);
  a87=sin(a0);
  a88=(a87*a71);
  a86=(a86+a88);
  a86=(a80*a86);
  a74=(a74-a86);
  a86=sin(a38);
  a88=(a86*a82);
  a89=cos(a38);
  a90=(a89*a78);
  a91=(a90*a41);
  a88=(a88-a91);
  a88=(a88*a61);
  a91=(a90*a39);
  a92=(a86*a83);
  a91=(a91+a92);
  a91=(a91*a65);
  a88=(a88+a91);
  a91=(a89*a84);
  a91=(a91*a66);
  a88=(a88+a91);
  a91=cos(a6);
  a69=(a91*a69);
  a69=(a88*a69);
  a74=(a74-a69);
  a69=(a9*a85);
  a92=(a69*a73);
  a93=(a9*a87);
  a71=(a93*a71);
  a92=(a92+a71);
  a73=(a9*a73);
  a92=(a92+a73);
  a74=(a74-a92);
  if (res[0]!=0) res[0][6]=a74;
  a74=cos(a8);
  a92=(a72*a74);
  a73=sin(a8);
  a71=(a68*a73);
  a94=(a67*a71);
  a92=(a92+a94);
  a94=(a64*a92);
  a74=(a76*a74);
  a71=(a77*a71);
  a74=(a74-a71);
  a71=(a75*a74);
  a94=(a94+a71);
  a94=(a42*a94);
  a71=(a85*a74);
  a95=(a87*a92);
  a71=(a71-a95);
  a71=(a80*a71);
  a94=(a94+a71);
  a73=(a91*a73);
  a73=(a88*a73);
  a94=(a94-a73);
  a73=(a69*a74);
  a92=(a93*a92);
  a73=(a73-a92);
  a74=(a9*a74);
  a73=(a73+a74);
  a94=(a94+a73);
  if (res[0]!=0) res[0][7]=a94;
  a94=sin(a6);
  a73=(a16*a94);
  a74=(a14*a73);
  a94=(a5*a94);
  a94=(a1*a94);
  a74=(a74-a94);
  a94=cos(a6);
  a94=(a10*a94);
  a74=(a74+a94);
  a73=(a9*a73);
  a74=(a74+a73);
  if (res[0]!=0) res[0][8]=a74;
  a74=sin(a8);
  a73=cos(a6);
  a94=(a74*a73);
  a92=(a5*a94);
  a92=(a1*a92);
  a94=(a16*a94);
  a71=(a14*a94);
  a92=(a92-a71);
  a71=sin(a6);
  a95=(a74*a71);
  a95=(a10*a95);
  a92=(a92+a95);
  a94=(a9*a94);
  a92=(a92-a94);
  if (res[0]!=0) res[0][9]=a92;
  a92=cos(a8);
  a73=(a92*a73);
  a94=(a16*a73);
  a95=(a14*a94);
  a73=(a5*a73);
  a73=(a1*a73);
  a95=(a95-a73);
  a71=(a92*a71);
  a10=(a10*a71);
  a95=(a95-a10);
  a94=(a9*a94);
  a95=(a95+a94);
  if (res[0]!=0) res[0][10]=a95;
  a95=sin(a6);
  a94=(a27*a95);
  a10=(a25*a94);
  a95=(a17*a95);
  a95=(a13*a95);
  a10=(a10-a95);
  a95=cos(a6);
  a95=(a21*a95);
  a10=(a10+a95);
  a94=(a9*a94);
  a10=(a10+a94);
  if (res[0]!=0) res[0][11]=a10;
  a10=sin(a8);
  a94=cos(a6);
  a95=(a10*a94);
  a71=(a17*a95);
  a71=(a13*a71);
  a95=(a27*a95);
  a73=(a25*a95);
  a71=(a71-a73);
  a73=sin(a6);
  a96=(a10*a73);
  a96=(a21*a96);
  a71=(a71+a96);
  a95=(a9*a95);
  a71=(a71-a95);
  if (res[0]!=0) res[0][12]=a71;
  a71=cos(a8);
  a94=(a71*a94);
  a95=(a27*a94);
  a96=(a25*a95);
  a94=(a17*a94);
  a94=(a13*a94);
  a96=(a96-a94);
  a73=(a71*a73);
  a21=(a21*a73);
  a96=(a96-a21);
  a95=(a9*a95);
  a96=(a96+a95);
  if (res[0]!=0) res[0][13]=a96;
  a96=sin(a6);
  a95=(a45*a96);
  a21=(a43*a95);
  a96=(a35*a96);
  a73=(a32*a96);
  a21=(a21-a73);
  a21=(a29*a21);
  a73=(a56*a96);
  a94=(a54*a95);
  a73=(a73+a94);
  a73=(a49*a73);
  a21=(a21+a73);
  a73=cos(a6);
  a73=(a57*a73);
  a21=(a21+a73);
  a96=(a62*a96);
  a73=(a37*a95);
  a96=(a96+a73);
  a95=(a9*a95);
  a96=(a96+a95);
  a21=(a21+a96);
  if (res[0]!=0) res[0][14]=a21;
  a21=sin(a8);
  a96=cos(a6);
  a95=(a21*a96);
  a73=(a35*a95);
  a94=(a32*a73);
  a95=(a45*a95);
  a97=(a43*a95);
  a94=(a94-a97);
  a94=(a29*a94);
  a97=(a54*a95);
  a98=(a56*a73);
  a97=(a97+a98);
  a97=(a49*a97);
  a94=(a94-a97);
  a97=sin(a6);
  a98=(a21*a97);
  a98=(a57*a98);
  a94=(a94+a98);
  a98=(a37*a95);
  a73=(a62*a73);
  a98=(a98+a73);
  a95=(a9*a95);
  a98=(a98+a95);
  a94=(a94-a98);
  if (res[0]!=0) res[0][15]=a94;
  a94=cos(a8);
  a96=(a94*a96);
  a98=(a45*a96);
  a95=(a43*a98);
  a96=(a35*a96);
  a73=(a32*a96);
  a95=(a95-a73);
  a95=(a29*a95);
  a73=(a54*a98);
  a99=(a56*a96);
  a73=(a73+a99);
  a73=(a49*a73);
  a95=(a95+a73);
  a97=(a94*a97);
  a57=(a57*a97);
  a95=(a95-a57);
  a57=(a37*a98);
  a96=(a62*a96);
  a57=(a57+a96);
  a98=(a9*a98);
  a57=(a57+a98);
  a95=(a95+a57);
  if (res[0]!=0) res[0][16]=a95;
  a95=sin(a6);
  a57=(a77*a95);
  a98=(a75*a57);
  a95=(a67*a95);
  a96=(a64*a95);
  a98=(a98-a96);
  a98=(a42*a98);
  a96=(a87*a95);
  a97=(a85*a57);
  a96=(a96+a97);
  a96=(a80*a96);
  a98=(a98+a96);
  a96=cos(a6);
  a96=(a88*a96);
  a98=(a98+a96);
  a95=(a93*a95);
  a96=(a69*a57);
  a95=(a95+a96);
  a57=(a9*a57);
  a95=(a95+a57);
  a98=(a98+a95);
  if (res[0]!=0) res[0][17]=a98;
  a98=sin(a8);
  a95=cos(a6);
  a57=(a98*a95);
  a96=(a67*a57);
  a97=(a64*a96);
  a57=(a77*a57);
  a73=(a75*a57);
  a97=(a97-a73);
  a97=(a42*a97);
  a73=(a85*a57);
  a99=(a87*a96);
  a73=(a73+a99);
  a73=(a80*a73);
  a97=(a97-a73);
  a73=sin(a6);
  a99=(a98*a73);
  a99=(a88*a99);
  a97=(a97+a99);
  a99=(a69*a57);
  a96=(a93*a96);
  a99=(a99+a96);
  a57=(a9*a57);
  a99=(a99+a57);
  a97=(a97-a99);
  if (res[0]!=0) res[0][18]=a97;
  a97=cos(a8);
  a95=(a97*a95);
  a99=(a77*a95);
  a57=(a75*a99);
  a95=(a67*a95);
  a96=(a64*a95);
  a57=(a57-a96);
  a57=(a42*a57);
  a96=(a85*a99);
  a100=(a87*a95);
  a96=(a96+a100);
  a96=(a80*a96);
  a57=(a57+a96);
  a73=(a97*a73);
  a88=(a88*a73);
  a57=(a57-a88);
  a88=(a69*a99);
  a95=(a93*a95);
  a88=(a88+a95);
  a99=(a9*a99);
  a88=(a88+a99);
  a57=(a57+a88);
  if (res[0]!=0) res[0][19]=a57;
  a57=cos(a6);
  a88=sin(a3);
  a99=(a57*a88);
  a99=(a1*a99);
  a95=cos(a3);
  a73=(a57*a95);
  a96=(a14*a73);
  a99=(a99+a96);
  a73=(a9*a73);
  a99=(a99+a73);
  a99=(-a99);
  if (res[0]!=0) res[0][20]=a99;
  a99=cos(a8);
  a73=cos(a3);
  a96=(a99*a73);
  a74=(a74*a7);
  a100=(a74*a88);
  a96=(a96-a100);
  a96=(a1*a96);
  a100=sin(a3);
  a101=(a99*a100);
  a102=(a74*a95);
  a101=(a101+a102);
  a102=(a14*a101);
  a96=(a96-a102);
  a101=(a9*a101);
  a96=(a96-a101);
  if (res[0]!=0) res[0][21]=a96;
  a96=sin(a8);
  a73=(a96*a73);
  a92=(a92*a7);
  a88=(a92*a88);
  a73=(a73+a88);
  a1=(a1*a73);
  a95=(a92*a95);
  a100=(a96*a100);
  a95=(a95-a100);
  a14=(a14*a95);
  a1=(a1+a14);
  a95=(a9*a95);
  a1=(a1+a95);
  if (res[0]!=0) res[0][22]=a1;
  a1=cos(a6);
  a95=sin(a3);
  a14=(a1*a95);
  a14=(a13*a14);
  a100=cos(a3);
  a73=(a1*a100);
  a88=(a25*a73);
  a14=(a14+a88);
  a73=(a9*a73);
  a14=(a14+a73);
  a14=(-a14);
  if (res[0]!=0) res[0][23]=a14;
  a14=cos(a8);
  a73=cos(a3);
  a88=(a14*a73);
  a10=(a10*a19);
  a7=(a10*a95);
  a88=(a88-a7);
  a88=(a13*a88);
  a7=sin(a3);
  a101=(a14*a7);
  a102=(a10*a100);
  a101=(a101+a102);
  a102=(a25*a101);
  a88=(a88-a102);
  a101=(a9*a101);
  a88=(a88-a101);
  if (res[0]!=0) res[0][24]=a88;
  a88=sin(a8);
  a73=(a88*a73);
  a71=(a71*a19);
  a95=(a71*a95);
  a73=(a73+a95);
  a13=(a13*a73);
  a100=(a71*a100);
  a7=(a88*a7);
  a100=(a100-a7);
  a25=(a25*a100);
  a13=(a13+a25);
  a100=(a9*a100);
  a13=(a13+a100);
  if (res[0]!=0) res[0][25]=a13;
  a13=cos(a6);
  a100=sin(a3);
  a25=(a13*a100);
  a7=(a32*a25);
  a73=cos(a3);
  a95=(a13*a73);
  a19=(a43*a95);
  a7=(a7+a19);
  a7=(a29*a7);
  a19=(a54*a95);
  a101=(a56*a25);
  a19=(a19-a101);
  a19=(a49*a19);
  a7=(a7+a19);
  a19=(a37*a95);
  a25=(a62*a25);
  a19=(a19-a25);
  a95=(a9*a95);
  a19=(a19+a95);
  a7=(a7+a19);
  a7=(-a7);
  if (res[0]!=0) res[0][26]=a7;
  a7=cos(a8);
  a19=cos(a3);
  a95=(a7*a19);
  a25=(a21*a36);
  a101=(a25*a100);
  a95=(a95-a101);
  a101=(a32*a95);
  a102=sin(a3);
  a103=(a7*a102);
  a104=(a25*a73);
  a103=(a103+a104);
  a104=(a43*a103);
  a101=(a101-a104);
  a101=(a29*a101);
  a104=(a54*a103);
  a105=(a56*a95);
  a104=(a104+a105);
  a104=(a49*a104);
  a101=(a101-a104);
  a104=(a37*a103);
  a95=(a62*a95);
  a104=(a104+a95);
  a103=(a9*a103);
  a104=(a104+a103);
  a101=(a101-a104);
  if (res[0]!=0) res[0][27]=a101;
  a101=sin(a8);
  a19=(a101*a19);
  a36=(a94*a36);
  a100=(a36*a100);
  a19=(a19+a100);
  a100=(a32*a19);
  a73=(a36*a73);
  a102=(a101*a102);
  a73=(a73-a102);
  a102=(a43*a73);
  a100=(a100+a102);
  a100=(a29*a100);
  a102=(a54*a73);
  a104=(a56*a19);
  a102=(a102-a104);
  a102=(a49*a102);
  a100=(a100+a102);
  a37=(a37*a73);
  a62=(a62*a19);
  a37=(a37-a62);
  a73=(a9*a73);
  a37=(a37+a73);
  a100=(a100+a37);
  if (res[0]!=0) res[0][28]=a100;
  a100=cos(a6);
  a37=sin(a3);
  a73=(a100*a37);
  a62=(a64*a73);
  a19=cos(a3);
  a102=(a100*a19);
  a104=(a75*a102);
  a62=(a62+a104);
  a62=(a42*a62);
  a104=(a85*a102);
  a103=(a87*a73);
  a104=(a104-a103);
  a104=(a80*a104);
  a62=(a62+a104);
  a104=(a69*a102);
  a73=(a93*a73);
  a104=(a104-a73);
  a102=(a9*a102);
  a104=(a104+a102);
  a62=(a62+a104);
  a62=(-a62);
  if (res[0]!=0) res[0][29]=a62;
  a62=cos(a8);
  a104=cos(a3);
  a102=(a62*a104);
  a73=(a98*a68);
  a103=(a73*a37);
  a102=(a102-a103);
  a103=(a64*a102);
  a3=sin(a3);
  a95=(a62*a3);
  a105=(a73*a19);
  a95=(a95+a105);
  a105=(a75*a95);
  a103=(a103-a105);
  a103=(a42*a103);
  a105=(a85*a95);
  a106=(a87*a102);
  a105=(a105+a106);
  a105=(a80*a105);
  a103=(a103-a105);
  a105=(a69*a95);
  a102=(a93*a102);
  a105=(a105+a102);
  a95=(a9*a95);
  a105=(a105+a95);
  a103=(a103-a105);
  if (res[0]!=0) res[0][30]=a103;
  a8=sin(a8);
  a104=(a8*a104);
  a68=(a97*a68);
  a37=(a68*a37);
  a104=(a104+a37);
  a37=(a64*a104);
  a19=(a68*a19);
  a3=(a8*a3);
  a19=(a19-a3);
  a3=(a75*a19);
  a37=(a37+a3);
  a37=(a42*a37);
  a3=(a85*a19);
  a103=(a87*a104);
  a3=(a3-a103);
  a3=(a80*a3);
  a37=(a37+a3);
  a69=(a69*a19);
  a93=(a93*a104);
  a69=(a69-a93);
  a19=(a9*a19);
  a69=(a69+a19);
  a37=(a37+a69);
  if (res[0]!=0) res[0][31]=a37;
  a37=(a57*a5);
  a69=sin(a0);
  a69=(a2*a69);
  a19=cos(a0);
  a19=(a4*a19);
  a69=(a69+a19);
  a37=(a37*a69);
  a57=(a57*a16);
  a19=cos(a0);
  a2=(a2*a19);
  a19=sin(a0);
  a4=(a4*a19);
  a2=(a2-a4);
  a57=(a57*a2);
  a37=(a37+a57);
  a37=(-a37);
  if (res[0]!=0) res[0][32]=a37;
  a37=(a99*a15);
  a57=(a74*a16);
  a37=(a37-a57);
  a37=(a37*a2);
  a74=(a74*a5);
  a99=(a99*a12);
  a74=(a74+a99);
  a74=(a74*a69);
  a37=(a37-a74);
  if (res[0]!=0) res[0][33]=a37;
  a16=(a92*a16);
  a15=(a96*a15);
  a16=(a16+a15);
  a16=(a16*a2);
  a96=(a96*a12);
  a92=(a92*a5);
  a96=(a96-a92);
  a96=(a96*a69);
  a16=(a16-a96);
  if (res[0]!=0) res[0][34]=a16;
  a16=(a1*a17);
  a96=sin(a0);
  a96=(a11*a96);
  a69=cos(a0);
  a69=(a18*a69);
  a96=(a96+a69);
  a16=(a16*a96);
  a1=(a1*a27);
  a69=cos(a0);
  a11=(a11*a69);
  a69=sin(a0);
  a18=(a18*a69);
  a11=(a11-a18);
  a1=(a1*a11);
  a16=(a16+a1);
  a16=(-a16);
  if (res[0]!=0) res[0][35]=a16;
  a16=(a14*a26);
  a1=(a10*a27);
  a16=(a16-a1);
  a16=(a16*a11);
  a10=(a10*a17);
  a14=(a14*a23);
  a10=(a10+a14);
  a10=(a10*a96);
  a16=(a16-a10);
  if (res[0]!=0) res[0][36]=a16;
  a27=(a71*a27);
  a26=(a88*a26);
  a27=(a27+a26);
  a27=(a27*a11);
  a88=(a88*a23);
  a71=(a71*a17);
  a88=(a88-a71);
  a88=(a88*a96);
  a27=(a27-a88);
  if (res[0]!=0) res[0][37]=a27;
  a27=(a13*a35);
  a88=sin(a0);
  a96=(a27*a88);
  a13=(a13*a45);
  a71=cos(a0);
  a17=(a13*a71);
  a96=(a96+a17);
  a96=(a29*a96);
  a17=cos(a0);
  a23=(a27*a17);
  a11=sin(a0);
  a26=(a13*a11);
  a23=(a23-a26);
  a23=(a49*a23);
  a96=(a96+a23);
  a23=(a9*a17);
  a26=(a27*a23);
  a16=(a9*a11);
  a10=(a13*a16);
  a26=(a26-a10);
  a96=(a96+a26);
  a96=(-a96);
  if (res[0]!=0) res[0][38]=a96;
  a96=(a7*a44);
  a26=(a25*a45);
  a96=(a96-a26);
  a26=(a96*a71);
  a25=(a25*a35);
  a7=(a7*a40);
  a25=(a25+a7);
  a7=(a25*a88);
  a26=(a26-a7);
  a26=(a29*a26);
  a7=(a96*a11);
  a10=(a25*a17);
  a7=(a7+a10);
  a7=(a49*a7);
  a26=(a26-a7);
  a7=(a96*a16);
  a10=(a25*a23);
  a7=(a7+a10);
  a26=(a26-a7);
  if (res[0]!=0) res[0][39]=a26;
  a45=(a36*a45);
  a44=(a101*a44);
  a45=(a45+a44);
  a71=(a45*a71);
  a101=(a101*a40);
  a36=(a36*a35);
  a101=(a101-a36);
  a88=(a101*a88);
  a71=(a71-a88);
  a29=(a29*a71);
  a11=(a45*a11);
  a17=(a101*a17);
  a11=(a11+a17);
  a49=(a49*a11);
  a29=(a29-a49);
  a16=(a45*a16);
  a23=(a101*a23);
  a16=(a16+a23);
  a29=(a29-a16);
  if (res[0]!=0) res[0][40]=a29;
  a29=(a100*a67);
  a16=sin(a0);
  a23=(a29*a16);
  a100=(a100*a77);
  a49=cos(a0);
  a11=(a100*a49);
  a23=(a23+a11);
  a23=(a42*a23);
  a11=cos(a0);
  a17=(a29*a11);
  a0=sin(a0);
  a71=(a100*a0);
  a17=(a17-a71);
  a17=(a80*a17);
  a23=(a23+a17);
  a17=(a9*a11);
  a71=(a29*a17);
  a9=(a9*a0);
  a88=(a100*a9);
  a71=(a71-a88);
  a23=(a23+a71);
  a23=(-a23);
  if (res[0]!=0) res[0][41]=a23;
  a23=(a62*a76);
  a71=(a73*a77);
  a23=(a23-a71);
  a71=(a23*a49);
  a73=(a73*a67);
  a62=(a62*a72);
  a73=(a73+a62);
  a62=(a73*a16);
  a71=(a71-a62);
  a71=(a42*a71);
  a62=(a23*a0);
  a88=(a73*a11);
  a62=(a62+a88);
  a62=(a80*a62);
  a71=(a71-a62);
  a62=(a23*a9);
  a88=(a73*a17);
  a62=(a62+a88);
  a71=(a71-a62);
  if (res[0]!=0) res[0][42]=a71;
  a77=(a68*a77);
  a76=(a8*a76);
  a77=(a77+a76);
  a49=(a77*a49);
  a8=(a8*a72);
  a68=(a68*a67);
  a8=(a8-a68);
  a16=(a8*a16);
  a49=(a49-a16);
  a42=(a42*a49);
  a0=(a77*a0);
  a11=(a8*a11);
  a0=(a0+a11);
  a80=(a80*a0);
  a42=(a42-a80);
  a9=(a77*a9);
  a17=(a8*a17);
  a9=(a9+a17);
  a42=(a42-a9);
  if (res[0]!=0) res[0][43]=a42;
  a42=sin(a6);
  a9=cos(a38);
  a17=(a51*a9);
  a80=sin(a38);
  a0=(a47*a80);
  a11=(a20*a0);
  a17=(a17+a11);
  a17=(a30*a17);
  a9=(a52*a9);
  a0=(a31*a0);
  a9=(a9-a0);
  a9=(a33*a9);
  a17=(a17+a9);
  a80=(a53*a80);
  a80=(a34*a80);
  a17=(a17-a80);
  a80=(a42*a17);
  a9=(a27*a56);
  a0=(a13*a54);
  a9=(a9+a0);
  a0=cos(a38);
  a47=(a47*a0);
  a11=(a20*a47);
  a49=sin(a38);
  a51=(a51*a49);
  a11=(a11-a51);
  a11=(a30*a11);
  a52=(a52*a49);
  a47=(a31*a47);
  a52=(a52+a47);
  a52=(a33*a52);
  a11=(a11-a52);
  a53=(a53*a0);
  a53=(a34*a53);
  a11=(a11-a53);
  a53=(a9*a11);
  a80=(a80-a53);
  if (res[0]!=0) res[0][44]=a80;
  a80=(a96*a54);
  a53=(a25*a56);
  a80=(a80-a53);
  a53=(a80*a11);
  a21=(a21*a60);
  a0=(a21*a17);
  a53=(a53-a0);
  if (res[0]!=0) res[0][45]=a53;
  a54=(a45*a54);
  a56=(a101*a56);
  a54=(a54-a56);
  a11=(a54*a11);
  a94=(a94*a60);
  a17=(a94*a17);
  a11=(a11+a17);
  if (res[0]!=0) res[0][46]=a11;
  a6=sin(a6);
  a11=cos(a38);
  a17=(a82*a11);
  a60=sin(a38);
  a56=(a78*a60);
  a53=(a41*a56);
  a17=(a17+a53);
  a17=(a61*a17);
  a11=(a83*a11);
  a56=(a39*a56);
  a11=(a11-a56);
  a11=(a65*a11);
  a17=(a17+a11);
  a60=(a84*a60);
  a60=(a66*a60);
  a17=(a17-a60);
  a60=(a6*a17);
  a11=(a29*a87);
  a56=(a100*a85);
  a11=(a11+a56);
  a56=cos(a38);
  a78=(a78*a56);
  a53=(a41*a78);
  a38=sin(a38);
  a82=(a82*a38);
  a53=(a53-a82);
  a53=(a61*a53);
  a83=(a83*a38);
  a78=(a39*a78);
  a83=(a83+a78);
  a83=(a65*a83);
  a53=(a53-a83);
  a84=(a84*a56);
  a84=(a66*a84);
  a53=(a53-a84);
  a84=(a11*a53);
  a60=(a60-a84);
  if (res[0]!=0) res[0][47]=a60;
  a60=(a23*a85);
  a84=(a73*a87);
  a60=(a60-a84);
  a84=(a60*a53);
  a98=(a98*a91);
  a56=(a98*a17);
  a84=(a84-a56);
  if (res[0]!=0) res[0][48]=a84;
  a85=(a77*a85);
  a87=(a8*a87);
  a85=(a85-a87);
  a53=(a85*a53);
  a97=(a97*a91);
  a17=(a97*a17);
  a53=(a53+a17);
  if (res[0]!=0) res[0][49]=a53;
  a27=(a27*a32);
  a13=(a13*a43);
  a27=(a27-a13);
  a13=sin(a24);
  a53=(a31*a13);
  a53=(a33*a53);
  a13=(a20*a13);
  a13=(a30*a13);
  a53=(a53-a13);
  a13=cos(a24);
  a13=(a34*a13);
  a53=(a53+a13);
  a13=(a27*a53);
  a17=cos(a24);
  a91=(a46*a17);
  a87=(a20*a91);
  a87=(a30*a87);
  a91=(a31*a91);
  a91=(a33*a91);
  a87=(a87-a91);
  a91=sin(a24);
  a46=(a46*a91);
  a46=(a34*a46);
  a87=(a87+a46);
  a46=(a9*a87);
  a13=(a13-a46);
  a17=(a58*a17);
  a31=(a31*a17);
  a31=(a33*a31);
  a20=(a20*a17);
  a20=(a30*a20);
  a31=(a31-a20);
  a58=(a58*a91);
  a34=(a34*a58);
  a31=(a31-a34);
  a34=(a42*a31);
  a13=(a13+a34);
  if (res[0]!=0) res[0][50]=a13;
  a25=(a25*a32);
  a96=(a96*a43);
  a25=(a25+a96);
  a96=(a25*a53);
  a13=(a80*a87);
  a96=(a96+a13);
  a13=(a21*a31);
  a96=(a96-a13);
  if (res[0]!=0) res[0][51]=a96;
  a101=(a101*a32);
  a45=(a45*a43);
  a101=(a101+a45);
  a53=(a101*a53);
  a87=(a54*a87);
  a53=(a53+a87);
  a31=(a94*a31);
  a53=(a53+a31);
  if (res[0]!=0) res[0][52]=a53;
  a29=(a29*a64);
  a100=(a100*a75);
  a29=(a29-a100);
  a100=sin(a24);
  a53=(a39*a100);
  a53=(a65*a53);
  a100=(a41*a100);
  a100=(a61*a100);
  a53=(a53-a100);
  a100=cos(a24);
  a100=(a66*a100);
  a53=(a53+a100);
  a100=(a29*a53);
  a31=cos(a24);
  a87=(a70*a31);
  a45=(a41*a87);
  a45=(a61*a45);
  a87=(a39*a87);
  a87=(a65*a87);
  a45=(a45-a87);
  a24=sin(a24);
  a70=(a70*a24);
  a70=(a66*a70);
  a45=(a45+a70);
  a70=(a11*a45);
  a100=(a100-a70);
  a31=(a89*a31);
  a39=(a39*a31);
  a39=(a65*a39);
  a41=(a41*a31);
  a41=(a61*a41);
  a39=(a39-a41);
  a89=(a89*a24);
  a66=(a66*a89);
  a39=(a39-a66);
  a66=(a6*a39);
  a100=(a100+a66);
  if (res[0]!=0) res[0][53]=a100;
  a73=(a73*a64);
  a23=(a23*a75);
  a73=(a73+a23);
  a23=(a73*a53);
  a100=(a60*a45);
  a23=(a23+a100);
  a100=(a98*a39);
  a23=(a23-a100);
  if (res[0]!=0) res[0][54]=a23;
  a8=(a8*a64);
  a77=(a77*a75);
  a8=(a8+a77);
  a53=(a8*a53);
  a45=(a85*a45);
  a53=(a53+a45);
  a39=(a97*a39);
  a53=(a53+a39);
  if (res[0]!=0) res[0][55]=a53;
  a53=cos(a28);
  a39=(a55*a53);
  a45=sin(a28);
  a77=(a59*a45);
  a39=(a39+a77);
  a39=(a30*a39);
  a77=cos(a28);
  a59=(a59*a77);
  a75=sin(a28);
  a55=(a55*a75);
  a59=(a59-a55);
  a59=(a33*a59);
  a39=(a39+a59);
  a42=(a42*a39);
  a59=(a22*a45);
  a59=(a30*a59);
  a22=(a22*a77);
  a22=(a33*a22);
  a59=(a59+a22);
  a27=(a27*a59);
  a53=(a50*a53);
  a45=(a48*a45);
  a53=(a53-a45);
  a30=(a30*a53);
  a50=(a50*a75);
  a48=(a48*a77);
  a50=(a50+a48);
  a33=(a33*a50);
  a30=(a30-a33);
  a9=(a9*a30);
  a27=(a27+a9);
  a42=(a42-a27);
  if (res[0]!=0) res[0][56]=a42;
  a80=(a80*a30);
  a25=(a25*a59);
  a80=(a80-a25);
  a21=(a21*a39);
  a80=(a80-a21);
  if (res[0]!=0) res[0][57]=a80;
  a54=(a54*a30);
  a101=(a101*a59);
  a54=(a54-a101);
  a94=(a94*a39);
  a54=(a54+a94);
  if (res[0]!=0) res[0][58]=a54;
  a54=cos(a28);
  a94=(a86*a54);
  a39=sin(a28);
  a101=(a90*a39);
  a94=(a94+a101);
  a94=(a61*a94);
  a101=cos(a28);
  a90=(a90*a101);
  a28=sin(a28);
  a86=(a86*a28);
  a90=(a90-a86);
  a90=(a65*a90);
  a94=(a94+a90);
  a6=(a6*a94);
  a90=(a63*a39);
  a90=(a61*a90);
  a63=(a63*a101);
  a63=(a65*a63);
  a90=(a90+a63);
  a29=(a29*a90);
  a54=(a81*a54);
  a39=(a79*a39);
  a54=(a54-a39);
  a61=(a61*a54);
  a81=(a81*a28);
  a79=(a79*a101);
  a81=(a81+a79);
  a65=(a65*a81);
  a61=(a61-a65);
  a11=(a11*a61);
  a29=(a29+a11);
  a6=(a6-a29);
  if (res[0]!=0) res[0][59]=a6;
  a60=(a60*a61);
  a73=(a73*a90);
  a60=(a60-a73);
  a98=(a98*a94);
  a60=(a60-a98);
  if (res[0]!=0) res[0][60]=a60;
  a85=(a85*a61);
  a8=(a8*a90);
  a85=(a85-a8);
  a97=(a97*a94);
  a85=(a85+a97);
  if (res[0]!=0) res[0][61]=a85;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_J_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_J(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[188];
  casadi_int *iw = 0;
  const casadi_real* arg[4] = {0};
  casadi_real* res[1] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+81);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+81);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+7, casadi_s2, w+81);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+13, casadi_s2, w+81);
  --resc;
  res[0] = w+19;
  i = f_J(arg, res, iw, w+81, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_f_J(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[188];
  const casadi_real* arg[4];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+7;
  arg[2] = w+7;
  arg[3] = w+13;
  res[0] = w+19;
  a = w;
  for (j=0; j<19; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_J(arg, res, iw, w+81, 0);
  if (flag) return flag;
  r = w+19;
  for (j=0; j<62; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[4];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_J(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_J")==0) {
    mex_f_J(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_J'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_J")==0) {
    return main_f_J(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_J'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
