/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_Jpseudo_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[75] = {7, 9, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6};

/* f_Jpseudo:(i0[7],i1[3],i2[3],i3[3])->(o0[7x9]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a9;
  a0=arg[1]? arg[1][1] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=sin(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=sin(a3);
  a5=(a2*a4);
  a5=(a0*a5);
  a6=arg[1]? arg[1][0] : 0;
  a7=cos(a1);
  a4=(a7*a4);
  a4=(a6*a4);
  a5=(a5-a4);
  a4=arg[1]? arg[1][2] : 0;
  a8=cos(a3);
  a8=(a4*a8);
  a5=(a5+a8);
  a8=sin(a3);
  a9=arg[0]? arg[0][0] : 0;
  a10=cos(a9);
  a11=(a8*a10);
  a12=(a7*a11);
  a13=sin(a1);
  a14=sin(a9);
  a15=(a13*a14);
  a12=(a12-a15);
  a12=(a6*a12);
  a15=cos(a1);
  a14=(a15*a14);
  a11=(a2*a11);
  a14=(a14+a11);
  a14=(a0*a14);
  a12=(a12-a14);
  a14=cos(a3);
  a10=(a14*a10);
  a10=(a4*a10);
  a12=(a12-a10);
  a10=sin(a9);
  a11=cos(a3);
  a16=(a10*a11);
  a17=(a7*a16);
  a17=(a6*a17);
  a16=(a2*a16);
  a16=(a0*a16);
  a17=(a17-a16);
  a16=sin(a3);
  a18=(a10*a16);
  a18=(a4*a18);
  a17=(a17+a18);
  a18=(a12*a17);
  a19=cos(a9);
  a13=(a13*a19);
  a20=sin(a9);
  a21=(a8*a20);
  a22=(a7*a21);
  a13=(a13+a22);
  a13=(a6*a13);
  a15=(a15*a19);
  a21=(a2*a21);
  a15=(a15-a21);
  a15=(a0*a15);
  a13=(a13+a15);
  a14=(a14*a20);
  a14=(a4*a14);
  a13=(a13-a14);
  a14=cos(a9);
  a11=(a14*a11);
  a2=(a2*a11);
  a2=(a0*a2);
  a7=(a7*a11);
  a7=(a6*a7);
  a2=(a2-a7);
  a16=(a14*a16);
  a4=(a4*a16);
  a2=(a2-a4);
  a4=(a13*a2);
  a18=(a18+a4);
  a4=arg[2]? arg[2][0] : 0;
  a16=cos(a1);
  a7=sin(a3);
  a11=cos(a9);
  a20=(a7*a11);
  a15=(a16*a20);
  a21=sin(a1);
  a19=sin(a9);
  a22=(a21*a19);
  a15=(a15-a22);
  a15=(a4*a15);
  a22=arg[0]? arg[0][3] : 0;
  a23=cos(a22);
  a24=arg[2]? arg[2][1] : 0;
  a23=(a23*a24);
  a25=sin(a22);
  a26=arg[2]? arg[2][2] : 0;
  a25=(a25*a26);
  a23=(a23-a25);
  a25=cos(a1);
  a19=(a25*a19);
  a27=sin(a1);
  a20=(a27*a20);
  a19=(a19+a20);
  a20=(a23*a19);
  a15=(a15-a20);
  a20=sin(a22);
  a20=(a20*a24);
  a28=cos(a22);
  a28=(a28*a26);
  a20=(a20+a28);
  a28=cos(a3);
  a11=(a28*a11);
  a11=(a20*a11);
  a15=(a15-a11);
  a11=-4.7827999999999998e-01;
  a19=(a11*a19);
  a15=(a15-a19);
  a19=sin(a9);
  a29=cos(a3);
  a30=(a19*a29);
  a31=(a16*a30);
  a31=(a4*a31);
  a30=(a27*a30);
  a32=(a23*a30);
  a31=(a31-a32);
  a32=sin(a3);
  a33=(a19*a32);
  a33=(a20*a33);
  a31=(a31+a33);
  a30=(a11*a30);
  a31=(a31-a30);
  a30=(a15*a31);
  a18=(a18+a30);
  a30=cos(a9);
  a21=(a21*a30);
  a33=sin(a9);
  a34=(a7*a33);
  a35=(a16*a34);
  a21=(a21+a35);
  a21=(a4*a21);
  a30=(a25*a30);
  a34=(a27*a34);
  a30=(a30-a34);
  a34=(a23*a30);
  a21=(a21+a34);
  a33=(a28*a33);
  a33=(a20*a33);
  a21=(a21-a33);
  a30=(a11*a30);
  a21=(a21+a30);
  a30=cos(a9);
  a29=(a30*a29);
  a33=(a27*a29);
  a34=(a23*a33);
  a29=(a16*a29);
  a29=(a4*a29);
  a34=(a34-a29);
  a32=(a30*a32);
  a32=(a20*a32);
  a34=(a34-a32);
  a33=(a11*a33);
  a34=(a34+a33);
  a33=(a21*a34);
  a18=(a18+a33);
  a33=arg[0]? arg[0][5] : 0;
  a32=cos(a33);
  a29=arg[0]? arg[0][6] : 0;
  a35=cos(a29);
  a36=(a32*a35);
  a37=arg[3]? arg[3][0] : 0;
  a36=(a36*a37);
  a38=sin(a29);
  a39=(a32*a38);
  a40=arg[3]? arg[3][1] : 0;
  a39=(a39*a40);
  a36=(a36-a39);
  a39=sin(a33);
  a41=arg[3]? arg[3][2] : 0;
  a39=(a39*a41);
  a36=(a36+a39);
  a39=cos(a1);
  a42=sin(a3);
  a43=cos(a9);
  a44=(a42*a43);
  a45=(a39*a44);
  a46=sin(a1);
  a47=sin(a9);
  a48=(a46*a47);
  a45=(a45-a48);
  a45=(a36*a45);
  a48=arg[0]? arg[0][4] : 0;
  a49=sin(a48);
  a50=sin(a33);
  a51=(a49*a50);
  a52=(a51*a35);
  a53=cos(a48);
  a54=sin(a29);
  a55=(a53*a54);
  a52=(a52+a55);
  a52=(a52*a37);
  a55=cos(a29);
  a56=(a53*a55);
  a57=(a51*a38);
  a56=(a56-a57);
  a56=(a56*a40);
  a52=(a52+a56);
  a56=cos(a33);
  a57=(a49*a56);
  a57=(a57*a41);
  a52=(a52-a57);
  a57=cos(a22);
  a58=cos(a1);
  a47=(a58*a47);
  a59=sin(a1);
  a44=(a59*a44);
  a47=(a47+a44);
  a44=(a57*a47);
  a60=sin(a22);
  a61=cos(a3);
  a43=(a61*a43);
  a62=(a60*a43);
  a44=(a44+a62);
  a44=(a52*a44);
  a45=(a45-a44);
  a44=sin(a48);
  a62=(a44*a54);
  a63=cos(a48);
  a64=(a63*a50);
  a65=(a64*a35);
  a62=(a62-a65);
  a62=(a62*a37);
  a65=(a64*a38);
  a66=(a44*a55);
  a65=(a65+a66);
  a65=(a65*a40);
  a62=(a62+a65);
  a65=(a63*a56);
  a65=(a65*a41);
  a62=(a62+a65);
  a65=cos(a22);
  a66=(a65*a43);
  a67=sin(a22);
  a68=(a67*a47);
  a66=(a66-a68);
  a66=(a62*a66);
  a45=(a45-a66);
  a66=-2.5840000000000002e-01;
  a68=(a66*a57);
  a69=(a68*a47);
  a70=(a66*a60);
  a43=(a70*a43);
  a69=(a69+a43);
  a47=(a11*a47);
  a69=(a69+a47);
  a45=(a45-a69);
  a69=sin(a9);
  a47=cos(a3);
  a43=(a69*a47);
  a71=(a39*a43);
  a71=(a36*a71);
  a72=sin(a3);
  a73=(a69*a72);
  a74=(a60*a73);
  a43=(a59*a43);
  a75=(a57*a43);
  a74=(a74-a75);
  a74=(a52*a74);
  a71=(a71+a74);
  a74=(a67*a43);
  a75=(a65*a73);
  a74=(a74+a75);
  a74=(a62*a74);
  a71=(a71+a74);
  a73=(a70*a73);
  a74=(a68*a43);
  a73=(a73-a74);
  a43=(a11*a43);
  a73=(a73-a43);
  a71=(a71+a73);
  a73=(a45*a71);
  a18=(a18+a73);
  a73=cos(a9);
  a43=(a46*a73);
  a74=sin(a9);
  a75=(a42*a74);
  a76=(a39*a75);
  a43=(a43+a76);
  a43=(a36*a43);
  a73=(a58*a73);
  a75=(a59*a75);
  a73=(a73-a75);
  a75=(a57*a73);
  a74=(a61*a74);
  a76=(a60*a74);
  a75=(a75-a76);
  a75=(a52*a75);
  a43=(a43+a75);
  a75=(a65*a74);
  a76=(a67*a73);
  a75=(a75+a76);
  a75=(a62*a75);
  a43=(a43-a75);
  a75=(a68*a73);
  a74=(a70*a74);
  a75=(a75-a74);
  a73=(a11*a73);
  a75=(a75+a73);
  a43=(a43+a75);
  a75=cos(a9);
  a47=(a75*a47);
  a73=(a59*a47);
  a74=(a57*a73);
  a72=(a75*a72);
  a76=(a60*a72);
  a74=(a74-a76);
  a74=(a52*a74);
  a47=(a39*a47);
  a47=(a36*a47);
  a74=(a74-a47);
  a47=(a65*a72);
  a76=(a67*a73);
  a47=(a47+a76);
  a47=(a62*a47);
  a74=(a74-a47);
  a47=(a68*a73);
  a72=(a70*a72);
  a47=(a47-a72);
  a73=(a11*a73);
  a47=(a47+a73);
  a74=(a74+a47);
  a47=(a43*a74);
  a18=(a18+a47);
  a47=(a5/a18);
  a73=cos(a3);
  a72=sin(a1);
  a76=(a73*a72);
  a76=(a6*a76);
  a77=cos(a1);
  a73=(a73*a77);
  a73=(a0*a73);
  a76=(a76+a73);
  a73=cos(a9);
  a78=cos(a1);
  a79=(a73*a78);
  a10=(a10*a8);
  a80=(a10*a72);
  a79=(a79-a80);
  a79=(a6*a79);
  a80=sin(a1);
  a73=(a73*a80);
  a10=(a10*a77);
  a73=(a73+a10);
  a73=(a0*a73);
  a79=(a79-a73);
  a73=(a12*a79);
  a10=sin(a9);
  a78=(a10*a78);
  a14=(a14*a8);
  a72=(a14*a72);
  a78=(a78+a72);
  a6=(a6*a78);
  a14=(a14*a77);
  a10=(a10*a80);
  a14=(a14-a10);
  a0=(a0*a14);
  a6=(a6+a0);
  a0=(a13*a6);
  a73=(a73+a0);
  a0=cos(a9);
  a14=cos(a1);
  a10=(a0*a14);
  a80=(a19*a7);
  a77=sin(a1);
  a78=(a80*a77);
  a10=(a10-a78);
  a10=(a4*a10);
  a78=sin(a1);
  a72=(a0*a78);
  a8=cos(a1);
  a81=(a80*a8);
  a72=(a72+a81);
  a81=(a23*a72);
  a10=(a10-a81);
  a72=(a11*a72);
  a10=(a10-a72);
  a72=(a15*a10);
  a73=(a73+a72);
  a72=sin(a9);
  a14=(a72*a14);
  a7=(a30*a7);
  a81=(a7*a77);
  a14=(a14+a81);
  a14=(a4*a14);
  a81=(a7*a8);
  a78=(a72*a78);
  a81=(a81-a78);
  a78=(a23*a81);
  a14=(a14+a78);
  a81=(a11*a81);
  a14=(a14+a81);
  a81=(a21*a14);
  a73=(a73+a81);
  a81=cos(a9);
  a78=cos(a1);
  a82=(a81*a78);
  a83=(a69*a42);
  a84=sin(a1);
  a85=(a83*a84);
  a82=(a82-a85);
  a82=(a36*a82);
  a85=sin(a1);
  a86=(a81*a85);
  a1=cos(a1);
  a87=(a83*a1);
  a86=(a86+a87);
  a87=(a57*a86);
  a87=(a52*a87);
  a82=(a82-a87);
  a87=(a67*a86);
  a87=(a62*a87);
  a82=(a82+a87);
  a87=(a68*a86);
  a86=(a11*a86);
  a87=(a87+a86);
  a82=(a82-a87);
  a87=(a45*a82);
  a73=(a73+a87);
  a9=sin(a9);
  a78=(a9*a78);
  a42=(a75*a42);
  a87=(a42*a84);
  a78=(a78+a87);
  a78=(a36*a78);
  a87=(a42*a1);
  a85=(a9*a85);
  a87=(a87-a85);
  a85=(a57*a87);
  a85=(a52*a85);
  a78=(a78+a85);
  a85=(a67*a87);
  a85=(a62*a85);
  a78=(a78-a85);
  a85=(a68*a87);
  a87=(a11*a87);
  a85=(a85+a87);
  a78=(a78+a85);
  a85=(a43*a78);
  a73=(a73+a85);
  a85=(a76/a73);
  a47=(a47-a85);
  if (res[0]!=0) res[0][0]=a47;
  a47=casadi_sq(a5);
  a85=casadi_sq(a17);
  a47=(a47+a85);
  a85=casadi_sq(a2);
  a47=(a47+a85);
  a85=sin(a3);
  a87=(a27*a85);
  a86=(a23*a87);
  a16=(a16*a85);
  a16=(a4*a16);
  a86=(a86-a16);
  a16=cos(a3);
  a20=(a20*a16);
  a86=(a86+a20);
  a87=(a11*a87);
  a86=(a86+a87);
  a87=casadi_sq(a86);
  a47=(a47+a87);
  a87=casadi_sq(a31);
  a47=(a47+a87);
  a87=casadi_sq(a34);
  a47=(a47+a87);
  a87=cos(a3);
  a20=(a60*a87);
  a16=sin(a3);
  a85=(a59*a16);
  a88=(a57*a85);
  a20=(a20+a88);
  a20=(a52*a20);
  a16=(a39*a16);
  a16=(a36*a16);
  a20=(a20-a16);
  a16=(a65*a87);
  a88=(a67*a85);
  a16=(a16-a88);
  a16=(a62*a16);
  a20=(a20+a16);
  a70=(a70*a87);
  a87=(a68*a85);
  a70=(a70+a87);
  a85=(a11*a85);
  a70=(a70+a85);
  a20=(a20+a70);
  a70=casadi_sq(a20);
  a47=(a47+a70);
  a70=casadi_sq(a71);
  a47=(a47+a70);
  a70=casadi_sq(a74);
  a47=(a47+a70);
  a70=(a5/a47);
  a85=(a17*a79);
  a87=(a5*a76);
  a85=(a85-a87);
  a87=(a2*a6);
  a85=(a85+a87);
  a87=cos(a3);
  a77=(a87*a77);
  a4=(a4*a77);
  a8=(a87*a8);
  a23=(a23*a8);
  a4=(a4+a23);
  a8=(a11*a8);
  a4=(a4+a8);
  a8=(a86*a4);
  a85=(a85-a8);
  a8=(a31*a10);
  a85=(a85+a8);
  a8=(a34*a14);
  a85=(a85+a8);
  a8=cos(a3);
  a1=(a8*a1);
  a23=(a67*a1);
  a23=(a62*a23);
  a84=(a8*a84);
  a36=(a36*a84);
  a84=(a57*a1);
  a84=(a52*a84);
  a36=(a36+a84);
  a23=(a23-a36);
  a68=(a68*a1);
  a11=(a11*a1);
  a68=(a68+a11);
  a23=(a23-a68);
  a68=(a20*a23);
  a85=(a85+a68);
  a68=(a71*a82);
  a85=(a85+a68);
  a68=(a74*a78);
  a85=(a85+a68);
  a68=(a76/a85);
  a70=(a70-a68);
  if (res[0]!=0) res[0][1]=a70;
  a70=(a79*a17);
  a68=(a76*a5);
  a70=(a70-a68);
  a68=(a6*a2);
  a70=(a70+a68);
  a68=(a4*a86);
  a70=(a70-a68);
  a68=(a10*a31);
  a70=(a70+a68);
  a68=(a14*a34);
  a70=(a70+a68);
  a68=(a23*a20);
  a70=(a70+a68);
  a68=(a82*a71);
  a70=(a70+a68);
  a68=(a78*a74);
  a70=(a70+a68);
  a68=(a5/a70);
  a11=casadi_sq(a76);
  a1=casadi_sq(a79);
  a11=(a11+a1);
  a1=casadi_sq(a6);
  a11=(a11+a1);
  a1=casadi_sq(a4);
  a11=(a11+a1);
  a1=casadi_sq(a10);
  a11=(a11+a1);
  a1=casadi_sq(a14);
  a11=(a11+a1);
  a1=casadi_sq(a23);
  a11=(a11+a1);
  a1=casadi_sq(a82);
  a11=(a11+a1);
  a1=casadi_sq(a78);
  a11=(a11+a1);
  a1=(a76/a11);
  a68=(a68-a1);
  if (res[0]!=0) res[0][2]=a68;
  a87=(a87*a27);
  a68=sin(a22);
  a68=(a24*a68);
  a1=cos(a22);
  a1=(a26*a1);
  a68=(a68+a1);
  a87=(a87*a68);
  a1=sin(a3);
  a36=cos(a22);
  a24=(a24*a36);
  a36=sin(a22);
  a26=(a26*a36);
  a24=(a24-a26);
  a1=(a1*a24);
  a87=(a87+a1);
  a1=(a87*a86);
  a0=(a0*a25);
  a80=(a80*a27);
  a0=(a0-a80);
  a0=(a0*a68);
  a19=(a19*a28);
  a19=(a19*a24);
  a0=(a0+a19);
  a19=(a0*a31);
  a1=(a1-a19);
  a30=(a30*a28);
  a30=(a30*a24);
  a7=(a7*a27);
  a72=(a72*a25);
  a7=(a7+a72);
  a7=(a7*a68);
  a30=(a30-a7);
  a7=(a30*a34);
  a1=(a1+a7);
  a3=sin(a3);
  a7=cos(a22);
  a68=(a3*a7);
  a72=(a8*a59);
  a25=sin(a22);
  a27=(a72*a25);
  a68=(a68+a27);
  a68=(a52*a68);
  a27=cos(a22);
  a24=(a72*a27);
  a22=sin(a22);
  a28=(a3*a22);
  a24=(a24-a28);
  a24=(a62*a24);
  a68=(a68+a24);
  a24=(a66*a7);
  a28=(a3*a24);
  a66=(a66*a25);
  a19=(a72*a66);
  a28=(a28+a19);
  a68=(a68+a28);
  a28=(a68*a20);
  a1=(a1+a28);
  a28=(a81*a58);
  a19=(a83*a59);
  a28=(a28-a19);
  a19=(a28*a25);
  a69=(a69*a61);
  a80=(a69*a7);
  a19=(a19+a80);
  a19=(a52*a19);
  a80=(a28*a27);
  a26=(a69*a22);
  a80=(a80-a26);
  a80=(a62*a80);
  a19=(a19+a80);
  a80=(a28*a66);
  a26=(a69*a24);
  a80=(a80+a26);
  a19=(a19+a80);
  a80=(a19*a71);
  a1=(a1-a80);
  a75=(a75*a61);
  a7=(a75*a7);
  a59=(a42*a59);
  a58=(a9*a58);
  a59=(a59+a58);
  a25=(a59*a25);
  a7=(a7-a25);
  a52=(a52*a7);
  a22=(a75*a22);
  a27=(a59*a27);
  a22=(a22+a27);
  a62=(a62*a22);
  a52=(a52-a62);
  a24=(a75*a24);
  a66=(a59*a66);
  a24=(a24-a66);
  a52=(a52+a24);
  a24=(a52*a74);
  a1=(a1+a24);
  a24=(a5/a1);
  a66=(a30*a14);
  a62=(a87*a4);
  a22=(a0*a10);
  a62=(a62+a22);
  a66=(a66-a62);
  a62=(a68*a23);
  a66=(a66+a62);
  a62=(a19*a82);
  a66=(a66-a62);
  a62=(a52*a78);
  a66=(a66+a62);
  a62=(a76/a66);
  a24=(a24-a62);
  if (res[0]!=0) res[0][3]=a24;
  a24=(a3*a60);
  a62=(a72*a57);
  a24=(a24-a62);
  a62=cos(a48);
  a22=(a50*a62);
  a27=(a35*a22);
  a7=sin(a48);
  a25=(a54*a7);
  a27=(a27-a25);
  a27=(a37*a27);
  a7=(a55*a7);
  a22=(a38*a22);
  a7=(a7+a22);
  a7=(a40*a7);
  a27=(a27-a7);
  a62=(a56*a62);
  a62=(a41*a62);
  a27=(a27-a62);
  a62=(a24*a27);
  a72=(a72*a67);
  a3=(a3*a65);
  a72=(a72+a3);
  a3=cos(a48);
  a54=(a54*a3);
  a48=sin(a48);
  a50=(a50*a48);
  a7=(a35*a50);
  a54=(a54+a7);
  a54=(a37*a54);
  a55=(a55*a3);
  a50=(a38*a50);
  a55=(a55-a50);
  a55=(a40*a55);
  a54=(a54+a55);
  a56=(a56*a48);
  a56=(a41*a56);
  a54=(a54-a56);
  a56=(a72*a54);
  a62=(a62+a56);
  a56=(a62*a20);
  a48=(a28*a57);
  a55=(a69*a60);
  a48=(a48-a55);
  a55=(a48*a27);
  a28=(a28*a67);
  a69=(a69*a65);
  a28=(a28+a69);
  a69=(a28*a54);
  a55=(a55-a69);
  a69=(a55*a71);
  a56=(a56+a69);
  a57=(a59*a57);
  a60=(a75*a60);
  a57=(a57+a60);
  a27=(a57*a27);
  a75=(a75*a65);
  a59=(a59*a67);
  a75=(a75-a59);
  a54=(a75*a54);
  a27=(a27+a54);
  a54=(a27*a74);
  a56=(a56+a54);
  a54=(a5/a56);
  a59=(a62*a23);
  a67=(a55*a82);
  a59=(a59+a67);
  a67=(a27*a78);
  a59=(a59+a67);
  a67=(a76/a59);
  a54=(a54-a67);
  if (res[0]!=0) res[0][4]=a54;
  a8=(a8*a39);
  a54=sin(a33);
  a67=(a38*a54);
  a67=(a40*a67);
  a54=(a35*a54);
  a54=(a37*a54);
  a67=(a67-a54);
  a54=cos(a33);
  a54=(a41*a54);
  a67=(a67+a54);
  a54=(a8*a67);
  a65=cos(a33);
  a60=(a49*a65);
  a69=(a35*a60);
  a69=(a37*a69);
  a60=(a38*a60);
  a60=(a40*a60);
  a69=(a69-a60);
  a33=sin(a33);
  a49=(a49*a33);
  a49=(a41*a49);
  a69=(a69+a49);
  a49=(a24*a69);
  a54=(a54+a49);
  a65=(a63*a65);
  a38=(a38*a65);
  a38=(a40*a38);
  a35=(a35*a65);
  a35=(a37*a35);
  a38=(a38-a35);
  a63=(a63*a33);
  a41=(a41*a63);
  a38=(a38-a41);
  a41=(a72*a38);
  a54=(a54+a41);
  a41=(a54*a20);
  a83=(a83*a39);
  a81=(a81*a46);
  a83=(a83+a81);
  a81=(a83*a67);
  a63=(a48*a69);
  a81=(a81+a63);
  a63=(a28*a38);
  a81=(a81-a63);
  a63=(a81*a71);
  a41=(a41+a63);
  a9=(a9*a46);
  a42=(a42*a39);
  a9=(a9-a42);
  a67=(a9*a67);
  a69=(a57*a69);
  a67=(a67+a69);
  a38=(a75*a38);
  a67=(a67+a38);
  a38=(a67*a74);
  a41=(a41+a38);
  a38=(a5/a41);
  a69=(a54*a23);
  a42=(a81*a82);
  a69=(a69+a42);
  a42=(a67*a78);
  a69=(a69+a42);
  a42=(a76/a69);
  a38=(a38-a42);
  if (res[0]!=0) res[0][5]=a38;
  a38=cos(a29);
  a42=(a53*a38);
  a39=sin(a29);
  a46=(a51*a39);
  a42=(a42-a46);
  a42=(a37*a42);
  a46=sin(a29);
  a53=(a53*a46);
  a29=cos(a29);
  a51=(a51*a29);
  a53=(a53+a51);
  a53=(a40*a53);
  a42=(a42-a53);
  a24=(a24*a42);
  a53=(a32*a39);
  a53=(a37*a53);
  a32=(a32*a29);
  a32=(a40*a32);
  a53=(a53+a32);
  a8=(a8*a53);
  a24=(a24-a8);
  a38=(a44*a38);
  a39=(a64*a39);
  a38=(a38+a39);
  a37=(a37*a38);
  a64=(a64*a29);
  a44=(a44*a46);
  a64=(a64-a44);
  a40=(a40*a64);
  a37=(a37+a40);
  a72=(a72*a37);
  a24=(a24+a72);
  a72=(a24*a20);
  a48=(a48*a42);
  a83=(a83*a53);
  a48=(a48-a83);
  a28=(a28*a37);
  a48=(a48-a28);
  a28=(a48*a71);
  a72=(a72+a28);
  a57=(a57*a42);
  a9=(a9*a53);
  a57=(a57-a9);
  a75=(a75*a37);
  a57=(a57+a75);
  a75=(a57*a74);
  a72=(a72+a75);
  a5=(a5/a72);
  a75=(a24*a23);
  a37=(a48*a82);
  a75=(a75+a37);
  a37=(a57*a78);
  a75=(a75+a37);
  a76=(a76/a75);
  a5=(a5-a76);
  if (res[0]!=0) res[0][6]=a5;
  a5=casadi_sq(a12);
  a76=casadi_sq(a13);
  a5=(a5+a76);
  a76=casadi_sq(a15);
  a5=(a5+a76);
  a76=casadi_sq(a21);
  a5=(a5+a76);
  a76=casadi_sq(a45);
  a5=(a5+a76);
  a76=casadi_sq(a43);
  a5=(a5+a76);
  a76=(a12/a5);
  a37=(a17/a18);
  a76=(a76+a37);
  a37=(a79/a73);
  a76=(a76+a37);
  if (res[0]!=0) res[0][7]=a76;
  a76=(a17*a12);
  a37=(a2*a13);
  a76=(a76+a37);
  a37=(a31*a15);
  a76=(a76+a37);
  a37=(a34*a21);
  a76=(a76+a37);
  a37=(a71*a45);
  a76=(a76+a37);
  a37=(a74*a43);
  a76=(a76+a37);
  a37=(a12/a76);
  a9=(a17/a47);
  a37=(a37+a9);
  a9=(a79/a85);
  a37=(a37+a9);
  if (res[0]!=0) res[0][8]=a37;
  a37=(a79*a12);
  a9=(a6*a13);
  a37=(a37+a9);
  a9=(a10*a15);
  a37=(a37+a9);
  a9=(a14*a21);
  a37=(a37+a9);
  a9=(a82*a45);
  a37=(a37+a9);
  a9=(a78*a43);
  a37=(a37+a9);
  a9=(a12/a37);
  a53=(a17/a70);
  a9=(a9+a53);
  a53=(a79/a11);
  a9=(a9+a53);
  if (res[0]!=0) res[0][9]=a9;
  a9=(a30*a21);
  a53=(a0*a15);
  a9=(a9-a53);
  a53=(a19*a45);
  a9=(a9-a53);
  a53=(a52*a43);
  a9=(a9+a53);
  a53=(a12/a9);
  a42=(a17/a1);
  a53=(a53+a42);
  a42=(a79/a66);
  a53=(a53+a42);
  if (res[0]!=0) res[0][10]=a53;
  a53=(a55*a45);
  a42=(a27*a43);
  a53=(a53+a42);
  a42=(a12/a53);
  a28=(a17/a56);
  a42=(a42+a28);
  a28=(a79/a59);
  a42=(a42+a28);
  if (res[0]!=0) res[0][11]=a42;
  a42=(a81*a45);
  a28=(a67*a43);
  a42=(a42+a28);
  a28=(a12/a42);
  a83=(a17/a41);
  a28=(a28+a83);
  a83=(a79/a69);
  a28=(a28+a83);
  if (res[0]!=0) res[0][12]=a28;
  a28=(a48*a45);
  a83=(a57*a43);
  a28=(a28+a83);
  a12=(a12/a28);
  a17=(a17/a72);
  a12=(a12+a17);
  a79=(a79/a75);
  a12=(a12+a79);
  if (res[0]!=0) res[0][13]=a12;
  a12=(a13/a5);
  a79=(a2/a18);
  a12=(a12+a79);
  a79=(a6/a73);
  a12=(a12+a79);
  if (res[0]!=0) res[0][14]=a12;
  a12=(a13/a76);
  a79=(a2/a47);
  a12=(a12+a79);
  a79=(a6/a85);
  a12=(a12+a79);
  if (res[0]!=0) res[0][15]=a12;
  a12=(a13/a37);
  a79=(a2/a70);
  a12=(a12+a79);
  a79=(a6/a11);
  a12=(a12+a79);
  if (res[0]!=0) res[0][16]=a12;
  a12=(a13/a9);
  a79=(a2/a1);
  a12=(a12+a79);
  a79=(a6/a66);
  a12=(a12+a79);
  if (res[0]!=0) res[0][17]=a12;
  a12=(a13/a53);
  a79=(a2/a56);
  a12=(a12+a79);
  a79=(a6/a59);
  a12=(a12+a79);
  if (res[0]!=0) res[0][18]=a12;
  a12=(a13/a42);
  a79=(a2/a41);
  a12=(a12+a79);
  a79=(a6/a69);
  a12=(a12+a79);
  if (res[0]!=0) res[0][19]=a12;
  a13=(a13/a28);
  a2=(a2/a72);
  a13=(a13+a2);
  a6=(a6/a75);
  a13=(a13+a6);
  if (res[0]!=0) res[0][20]=a13;
  a13=(a86/a18);
  a6=(a4/a73);
  a13=(a13-a6);
  a6=(a21*a30);
  a2=(a15*a0);
  a6=(a6-a2);
  a2=(a45*a19);
  a6=(a6-a2);
  a2=(a43*a52);
  a6=(a6+a2);
  a2=(a87/a6);
  a13=(a13+a2);
  if (res[0]!=0) res[0][21]=a13;
  a13=(a86/a47);
  a2=(a4/a85);
  a13=(a13-a2);
  a2=(a86*a87);
  a12=(a31*a0);
  a2=(a2-a12);
  a12=(a34*a30);
  a2=(a2+a12);
  a12=(a20*a68);
  a2=(a2+a12);
  a12=(a71*a19);
  a2=(a2-a12);
  a12=(a74*a52);
  a2=(a2+a12);
  a12=(a87/a2);
  a13=(a13+a12);
  if (res[0]!=0) res[0][22]=a13;
  a13=(a86/a70);
  a12=(a4/a11);
  a13=(a13-a12);
  a12=(a14*a30);
  a79=(a4*a87);
  a17=(a10*a0);
  a79=(a79+a17);
  a12=(a12-a79);
  a79=(a23*a68);
  a12=(a12+a79);
  a79=(a82*a19);
  a12=(a12-a79);
  a79=(a78*a52);
  a12=(a12+a79);
  a79=(a87/a12);
  a13=(a13+a79);
  if (res[0]!=0) res[0][23]=a13;
  a13=(a86/a1);
  a79=(a4/a66);
  a13=(a13-a79);
  a79=casadi_sq(a87);
  a17=casadi_sq(a0);
  a79=(a79+a17);
  a17=casadi_sq(a30);
  a79=(a79+a17);
  a17=casadi_sq(a68);
  a79=(a79+a17);
  a17=casadi_sq(a19);
  a79=(a79+a17);
  a17=casadi_sq(a52);
  a79=(a79+a17);
  a17=(a87/a79);
  a13=(a13+a17);
  if (res[0]!=0) res[0][24]=a13;
  a13=(a86/a56);
  a17=(a4/a59);
  a13=(a13-a17);
  a17=(a62*a68);
  a83=(a55*a19);
  a17=(a17-a83);
  a83=(a27*a52);
  a17=(a17+a83);
  a83=(a87/a17);
  a13=(a13+a83);
  if (res[0]!=0) res[0][25]=a13;
  a13=(a86/a41);
  a83=(a4/a69);
  a13=(a13-a83);
  a83=(a54*a68);
  a40=(a81*a19);
  a83=(a83-a40);
  a40=(a67*a52);
  a83=(a83+a40);
  a40=(a87/a83);
  a13=(a13+a40);
  if (res[0]!=0) res[0][26]=a13;
  a86=(a86/a72);
  a4=(a4/a75);
  a86=(a86-a4);
  a4=(a24*a68);
  a13=(a48*a19);
  a4=(a4-a13);
  a13=(a57*a52);
  a4=(a4+a13);
  a87=(a87/a4);
  a86=(a86+a87);
  if (res[0]!=0) res[0][27]=a86;
  a86=(a15/a5);
  a87=(a31/a18);
  a86=(a86+a87);
  a87=(a10/a73);
  a86=(a86+a87);
  a87=(a0/a6);
  a86=(a86-a87);
  if (res[0]!=0) res[0][28]=a86;
  a86=(a15/a76);
  a87=(a31/a47);
  a86=(a86+a87);
  a87=(a10/a85);
  a86=(a86+a87);
  a87=(a0/a2);
  a86=(a86-a87);
  if (res[0]!=0) res[0][29]=a86;
  a86=(a15/a37);
  a87=(a31/a70);
  a86=(a86+a87);
  a87=(a10/a11);
  a86=(a86+a87);
  a87=(a0/a12);
  a86=(a86-a87);
  if (res[0]!=0) res[0][30]=a86;
  a86=(a15/a9);
  a87=(a31/a1);
  a86=(a86+a87);
  a87=(a10/a66);
  a86=(a86+a87);
  a87=(a0/a79);
  a86=(a86-a87);
  if (res[0]!=0) res[0][31]=a86;
  a86=(a15/a53);
  a87=(a31/a56);
  a86=(a86+a87);
  a87=(a10/a59);
  a86=(a86+a87);
  a87=(a0/a17);
  a86=(a86-a87);
  if (res[0]!=0) res[0][32]=a86;
  a86=(a15/a42);
  a87=(a31/a41);
  a86=(a86+a87);
  a87=(a10/a69);
  a86=(a86+a87);
  a87=(a0/a83);
  a86=(a86-a87);
  if (res[0]!=0) res[0][33]=a86;
  a15=(a15/a28);
  a31=(a31/a72);
  a15=(a15+a31);
  a10=(a10/a75);
  a15=(a15+a10);
  a0=(a0/a4);
  a15=(a15-a0);
  if (res[0]!=0) res[0][34]=a15;
  a15=(a21/a5);
  a0=(a34/a18);
  a15=(a15+a0);
  a0=(a14/a73);
  a15=(a15+a0);
  a0=(a30/a6);
  a15=(a15+a0);
  if (res[0]!=0) res[0][35]=a15;
  a15=(a21/a76);
  a0=(a34/a47);
  a15=(a15+a0);
  a0=(a14/a85);
  a15=(a15+a0);
  a0=(a30/a2);
  a15=(a15+a0);
  if (res[0]!=0) res[0][36]=a15;
  a15=(a21/a37);
  a0=(a34/a70);
  a15=(a15+a0);
  a0=(a14/a11);
  a15=(a15+a0);
  a0=(a30/a12);
  a15=(a15+a0);
  if (res[0]!=0) res[0][37]=a15;
  a15=(a21/a9);
  a0=(a34/a1);
  a15=(a15+a0);
  a0=(a14/a66);
  a15=(a15+a0);
  a0=(a30/a79);
  a15=(a15+a0);
  if (res[0]!=0) res[0][38]=a15;
  a15=(a21/a53);
  a0=(a34/a56);
  a15=(a15+a0);
  a0=(a14/a59);
  a15=(a15+a0);
  a0=(a30/a17);
  a15=(a15+a0);
  if (res[0]!=0) res[0][39]=a15;
  a15=(a21/a42);
  a0=(a34/a41);
  a15=(a15+a0);
  a0=(a14/a69);
  a15=(a15+a0);
  a0=(a30/a83);
  a15=(a15+a0);
  if (res[0]!=0) res[0][40]=a15;
  a21=(a21/a28);
  a34=(a34/a72);
  a21=(a21+a34);
  a14=(a14/a75);
  a21=(a21+a14);
  a30=(a30/a4);
  a21=(a21+a30);
  if (res[0]!=0) res[0][41]=a21;
  a21=(a20/a18);
  a30=(a23/a73);
  a21=(a21+a30);
  a30=(a68/a6);
  a21=(a21+a30);
  a30=(a45*a55);
  a14=(a43*a27);
  a30=(a30+a14);
  a14=(a62/a30);
  a21=(a21+a14);
  a14=(a45*a81);
  a34=(a43*a67);
  a14=(a14+a34);
  a34=(a54/a14);
  a21=(a21+a34);
  a34=(a45*a48);
  a15=(a43*a57);
  a34=(a34+a15);
  a15=(a24/a34);
  a21=(a21+a15);
  if (res[0]!=0) res[0][42]=a21;
  a21=(a20/a47);
  a15=(a23/a85);
  a21=(a21+a15);
  a15=(a68/a2);
  a21=(a21+a15);
  a15=(a20*a62);
  a0=(a71*a55);
  a15=(a15+a0);
  a0=(a74*a27);
  a15=(a15+a0);
  a0=(a62/a15);
  a21=(a21+a0);
  a0=(a20*a54);
  a10=(a71*a81);
  a0=(a0+a10);
  a10=(a74*a67);
  a0=(a0+a10);
  a10=(a54/a0);
  a21=(a21+a10);
  a10=(a20*a24);
  a31=(a71*a48);
  a10=(a10+a31);
  a31=(a74*a57);
  a10=(a10+a31);
  a31=(a24/a10);
  a21=(a21+a31);
  if (res[0]!=0) res[0][43]=a21;
  a21=(a20/a70);
  a31=(a23/a11);
  a21=(a21+a31);
  a31=(a68/a12);
  a21=(a21+a31);
  a31=(a23*a62);
  a86=(a82*a55);
  a31=(a31+a86);
  a86=(a78*a27);
  a31=(a31+a86);
  a86=(a62/a31);
  a21=(a21+a86);
  a86=(a23*a54);
  a87=(a82*a81);
  a86=(a86+a87);
  a87=(a78*a67);
  a86=(a86+a87);
  a87=(a54/a86);
  a21=(a21+a87);
  a87=(a23*a24);
  a13=(a82*a48);
  a87=(a87+a13);
  a13=(a78*a57);
  a87=(a87+a13);
  a13=(a24/a87);
  a21=(a21+a13);
  if (res[0]!=0) res[0][44]=a21;
  a21=(a20/a1);
  a13=(a23/a66);
  a21=(a21+a13);
  a13=(a68/a79);
  a21=(a21+a13);
  a13=(a68*a62);
  a40=(a19*a55);
  a13=(a13-a40);
  a40=(a52*a27);
  a13=(a13+a40);
  a40=(a62/a13);
  a21=(a21+a40);
  a40=(a68*a54);
  a64=(a19*a81);
  a40=(a40-a64);
  a64=(a52*a67);
  a40=(a40+a64);
  a64=(a54/a40);
  a21=(a21+a64);
  a64=(a68*a24);
  a44=(a19*a48);
  a64=(a64-a44);
  a44=(a52*a57);
  a64=(a64+a44);
  a44=(a24/a64);
  a21=(a21+a44);
  if (res[0]!=0) res[0][45]=a21;
  a21=(a20/a56);
  a44=(a23/a59);
  a21=(a21+a44);
  a44=(a68/a17);
  a21=(a21+a44);
  a44=casadi_sq(a62);
  a46=casadi_sq(a55);
  a44=(a44+a46);
  a46=casadi_sq(a27);
  a44=(a44+a46);
  a46=(a62/a44);
  a21=(a21+a46);
  a46=(a62*a54);
  a29=(a55*a81);
  a46=(a46+a29);
  a29=(a27*a67);
  a46=(a46+a29);
  a29=(a54/a46);
  a21=(a21+a29);
  a29=(a62*a24);
  a38=(a55*a48);
  a29=(a29+a38);
  a38=(a27*a57);
  a29=(a29+a38);
  a38=(a24/a29);
  a21=(a21+a38);
  if (res[0]!=0) res[0][46]=a21;
  a21=(a20/a41);
  a38=(a23/a69);
  a21=(a21+a38);
  a38=(a68/a83);
  a21=(a21+a38);
  a38=(a54*a62);
  a39=(a81*a55);
  a38=(a38+a39);
  a39=(a67*a27);
  a38=(a38+a39);
  a39=(a62/a38);
  a21=(a21+a39);
  a39=casadi_sq(a54);
  a8=casadi_sq(a81);
  a39=(a39+a8);
  a8=casadi_sq(a67);
  a39=(a39+a8);
  a8=(a54/a39);
  a21=(a21+a8);
  a8=(a54*a24);
  a32=(a81*a48);
  a8=(a8+a32);
  a32=(a67*a57);
  a8=(a8+a32);
  a32=(a24/a8);
  a21=(a21+a32);
  if (res[0]!=0) res[0][47]=a21;
  a20=(a20/a72);
  a23=(a23/a75);
  a20=(a20+a23);
  a68=(a68/a4);
  a20=(a20+a68);
  a68=(a24*a62);
  a23=(a48*a55);
  a68=(a68+a23);
  a23=(a57*a27);
  a68=(a68+a23);
  a62=(a62/a68);
  a20=(a20+a62);
  a62=(a24*a54);
  a23=(a48*a81);
  a62=(a62+a23);
  a23=(a57*a67);
  a62=(a62+a23);
  a54=(a54/a62);
  a20=(a20+a54);
  a54=casadi_sq(a24);
  a23=casadi_sq(a48);
  a54=(a54+a23);
  a23=casadi_sq(a57);
  a54=(a54+a23);
  a24=(a24/a54);
  a20=(a20+a24);
  if (res[0]!=0) res[0][48]=a20;
  a20=(a45/a5);
  a24=(a71/a18);
  a20=(a20+a24);
  a24=(a82/a73);
  a20=(a20+a24);
  a24=(a19/a6);
  a20=(a20-a24);
  a24=(a55/a30);
  a20=(a20+a24);
  a24=(a81/a14);
  a20=(a20+a24);
  a24=(a48/a34);
  a20=(a20+a24);
  if (res[0]!=0) res[0][49]=a20;
  a20=(a45/a76);
  a24=(a71/a47);
  a20=(a20+a24);
  a24=(a82/a85);
  a20=(a20+a24);
  a24=(a19/a2);
  a20=(a20-a24);
  a24=(a55/a15);
  a20=(a20+a24);
  a24=(a81/a0);
  a20=(a20+a24);
  a24=(a48/a10);
  a20=(a20+a24);
  if (res[0]!=0) res[0][50]=a20;
  a20=(a45/a37);
  a24=(a71/a70);
  a20=(a20+a24);
  a24=(a82/a11);
  a20=(a20+a24);
  a24=(a19/a12);
  a20=(a20-a24);
  a24=(a55/a31);
  a20=(a20+a24);
  a24=(a81/a86);
  a20=(a20+a24);
  a24=(a48/a87);
  a20=(a20+a24);
  if (res[0]!=0) res[0][51]=a20;
  a20=(a45/a9);
  a24=(a71/a1);
  a20=(a20+a24);
  a24=(a82/a66);
  a20=(a20+a24);
  a24=(a19/a79);
  a20=(a20-a24);
  a24=(a55/a13);
  a20=(a20+a24);
  a24=(a81/a40);
  a20=(a20+a24);
  a24=(a48/a64);
  a20=(a20+a24);
  if (res[0]!=0) res[0][52]=a20;
  a20=(a45/a53);
  a24=(a71/a56);
  a20=(a20+a24);
  a24=(a82/a59);
  a20=(a20+a24);
  a24=(a19/a17);
  a20=(a20-a24);
  a24=(a55/a44);
  a20=(a20+a24);
  a24=(a81/a46);
  a20=(a20+a24);
  a24=(a48/a29);
  a20=(a20+a24);
  if (res[0]!=0) res[0][53]=a20;
  a20=(a45/a42);
  a24=(a71/a41);
  a20=(a20+a24);
  a24=(a82/a69);
  a20=(a20+a24);
  a24=(a19/a83);
  a20=(a20-a24);
  a24=(a55/a38);
  a20=(a20+a24);
  a24=(a81/a39);
  a20=(a20+a24);
  a24=(a48/a8);
  a20=(a20+a24);
  if (res[0]!=0) res[0][54]=a20;
  a45=(a45/a28);
  a71=(a71/a72);
  a45=(a45+a71);
  a82=(a82/a75);
  a45=(a45+a82);
  a19=(a19/a4);
  a45=(a45-a19);
  a55=(a55/a68);
  a45=(a45+a55);
  a81=(a81/a62);
  a45=(a45+a81);
  a48=(a48/a54);
  a45=(a45+a48);
  if (res[0]!=0) res[0][55]=a45;
  a5=(a43/a5);
  a18=(a74/a18);
  a5=(a5+a18);
  a73=(a78/a73);
  a5=(a5+a73);
  a6=(a52/a6);
  a5=(a5+a6);
  a30=(a27/a30);
  a5=(a5+a30);
  a14=(a67/a14);
  a5=(a5+a14);
  a34=(a57/a34);
  a5=(a5+a34);
  if (res[0]!=0) res[0][56]=a5;
  a76=(a43/a76);
  a47=(a74/a47);
  a76=(a76+a47);
  a85=(a78/a85);
  a76=(a76+a85);
  a2=(a52/a2);
  a76=(a76+a2);
  a15=(a27/a15);
  a76=(a76+a15);
  a0=(a67/a0);
  a76=(a76+a0);
  a10=(a57/a10);
  a76=(a76+a10);
  if (res[0]!=0) res[0][57]=a76;
  a37=(a43/a37);
  a70=(a74/a70);
  a37=(a37+a70);
  a11=(a78/a11);
  a37=(a37+a11);
  a12=(a52/a12);
  a37=(a37+a12);
  a31=(a27/a31);
  a37=(a37+a31);
  a86=(a67/a86);
  a37=(a37+a86);
  a87=(a57/a87);
  a37=(a37+a87);
  if (res[0]!=0) res[0][58]=a37;
  a9=(a43/a9);
  a1=(a74/a1);
  a9=(a9+a1);
  a66=(a78/a66);
  a9=(a9+a66);
  a79=(a52/a79);
  a9=(a9+a79);
  a13=(a27/a13);
  a9=(a9+a13);
  a40=(a67/a40);
  a9=(a9+a40);
  a64=(a57/a64);
  a9=(a9+a64);
  if (res[0]!=0) res[0][59]=a9;
  a53=(a43/a53);
  a56=(a74/a56);
  a53=(a53+a56);
  a59=(a78/a59);
  a53=(a53+a59);
  a17=(a52/a17);
  a53=(a53+a17);
  a44=(a27/a44);
  a53=(a53+a44);
  a46=(a67/a46);
  a53=(a53+a46);
  a29=(a57/a29);
  a53=(a53+a29);
  if (res[0]!=0) res[0][60]=a53;
  a42=(a43/a42);
  a41=(a74/a41);
  a42=(a42+a41);
  a69=(a78/a69);
  a42=(a42+a69);
  a83=(a52/a83);
  a42=(a42+a83);
  a38=(a27/a38);
  a42=(a42+a38);
  a39=(a67/a39);
  a42=(a42+a39);
  a8=(a57/a8);
  a42=(a42+a8);
  if (res[0]!=0) res[0][61]=a42;
  a43=(a43/a28);
  a74=(a74/a72);
  a43=(a43+a74);
  a78=(a78/a75);
  a43=(a43+a78);
  a52=(a52/a4);
  a43=(a43+a52);
  a27=(a27/a68);
  a43=(a43+a27);
  a67=(a67/a62);
  a43=(a43+a67);
  a57=(a57/a54);
  a43=(a43+a57);
  if (res[0]!=0) res[0][62]=a43;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_Jpseudo(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_Jpseudo_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_Jpseudo_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_Jpseudo_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_Jpseudo_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_Jpseudo_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_Jpseudo_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_Jpseudo_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_Jpseudo_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_Jpseudo_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_Jpseudo_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_Jpseudo_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_Jpseudo_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_Jpseudo_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_Jpseudo_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_Jpseudo_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_Jpseudo(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[168];
  casadi_int *iw = 0;
  const casadi_real* arg[4] = {0};
  casadi_real* res[1] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_Jpseudo\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_Jpseudo\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+79);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+79);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+10, casadi_s1, w+79);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+13, casadi_s1, w+79);
  --resc;
  res[0] = w+16;
  i = f_Jpseudo(arg, res, iw, w+79, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_Jpseudo\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s2, res[0]);
}
#endif

casadi_int main_f_Jpseudo(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[168];
  const casadi_real* arg[4];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+7;
  arg[2] = w+10;
  arg[3] = w+13;
  res[0] = w+16;
  a = w;
  for (j=0; j<16; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_Jpseudo(arg, res, iw, w+79, 0);
  if (flag) return flag;
  r = w+16;
  for (j=0; j<63; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[10];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_Jpseudo(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_Jpseudo")==0) {
    mex_f_Jpseudo(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_Jpseudo'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_Jpseudo")==0) {
    return main_f_Jpseudo(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_Jpseudo'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
