/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_Hekf_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s4[78] = {12, 7, 0, 8, 20, 32, 41, 50, 59, 68, 1, 2, 4, 5, 7, 8, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11, 3, 4, 5, 6, 7, 8, 9, 10, 11};

/* f_J:(i0[7],i1[3],i2[],i3[3x3])->(o0[12x7,68nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=sin(a3);
  a5=arg[0]? arg[0][0] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a8=(a2*a7);
  a9=sin(a1);
  a10=sin(a5);
  a11=(a9*a10);
  a8=(a8-a11);
  a8=(a0*a8);
  a11=arg[1]? arg[1][1] : 0;
  a12=cos(a1);
  a10=(a12*a10);
  a13=sin(a1);
  a7=(a13*a7);
  a10=(a10+a7);
  a10=(a11*a10);
  a8=(a8-a10);
  a10=arg[1]? arg[1][2] : 0;
  a7=cos(a3);
  a6=(a7*a6);
  a6=(a10*a6);
  a8=(a8-a6);
  if (res[0]!=0) res[0][0]=a8;
  a8=cos(a5);
  a9=(a9*a8);
  a6=sin(a5);
  a14=(a4*a6);
  a15=(a2*a14);
  a9=(a9+a15);
  a9=(a0*a9);
  a12=(a12*a8);
  a14=(a13*a14);
  a12=(a12-a14);
  a12=(a11*a12);
  a9=(a9+a12);
  a7=(a7*a6);
  a7=(a10*a7);
  a9=(a9-a7);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[0]? arg[0][5] : 0;
  a7=cos(a9);
  a6=arg[0]? arg[0][6] : 0;
  a12=cos(a6);
  a14=(a7*a12);
  a8=arg[3]? arg[3][0] : 0;
  a14=(a14*a8);
  a15=sin(a6);
  a16=(a7*a15);
  a17=arg[3]? arg[3][1] : 0;
  a16=(a16*a17);
  a14=(a14-a16);
  a16=sin(a9);
  a18=arg[3]? arg[3][2] : 0;
  a16=(a16*a18);
  a14=(a14+a16);
  a16=arg[0]? arg[0][3] : 0;
  a19=cos(a16);
  a20=cos(a1);
  a21=sin(a3);
  a22=cos(a5);
  a23=(a21*a22);
  a24=(a20*a23);
  a25=sin(a1);
  a26=sin(a5);
  a27=(a25*a26);
  a24=(a24-a27);
  a27=(a19*a24);
  a28=sin(a16);
  a29=cos(a1);
  a26=(a29*a26);
  a30=sin(a1);
  a23=(a30*a23);
  a26=(a26+a23);
  a23=(a28*a26);
  a27=(a27-a23);
  a27=(a14*a27);
  a23=arg[0]? arg[0][4] : 0;
  a31=sin(a23);
  a32=sin(a9);
  a33=(a31*a32);
  a34=(a33*a12);
  a35=cos(a23);
  a36=sin(a6);
  a37=(a35*a36);
  a34=(a34+a37);
  a34=(a34*a8);
  a37=cos(a6);
  a38=(a35*a37);
  a39=(a33*a15);
  a38=(a38-a39);
  a38=(a38*a17);
  a34=(a34+a38);
  a38=cos(a9);
  a39=(a31*a38);
  a39=(a39*a18);
  a34=(a34-a39);
  a39=cos(a16);
  a40=(a39*a26);
  a41=sin(a16);
  a42=(a41*a24);
  a40=(a40+a42);
  a40=(a34*a40);
  a27=(a27-a40);
  a40=sin(a23);
  a42=(a40*a36);
  a43=cos(a23);
  a44=(a43*a32);
  a45=(a44*a12);
  a42=(a42-a45);
  a42=(a42*a8);
  a45=(a44*a15);
  a46=(a40*a37);
  a45=(a45+a46);
  a45=(a45*a17);
  a42=(a42+a45);
  a45=(a43*a38);
  a45=(a45*a18);
  a42=(a42+a45);
  a45=cos(a3);
  a22=(a45*a22);
  a22=(a42*a22);
  a27=(a27-a22);
  a22=-2.5000000000000000e-01;
  a46=(a22*a39);
  a47=(a46*a26);
  a48=(a22*a41);
  a24=(a48*a24);
  a47=(a47+a24);
  a26=(a22*a26);
  a47=(a47+a26);
  a27=(a27-a47);
  if (res[0]!=0) res[0][2]=a27;
  a27=cos(a5);
  a47=(a25*a27);
  a26=sin(a5);
  a24=(a21*a26);
  a49=(a20*a24);
  a47=(a47+a49);
  a49=(a19*a47);
  a27=(a29*a27);
  a24=(a30*a24);
  a27=(a27-a24);
  a24=(a28*a27);
  a49=(a49+a24);
  a49=(a14*a49);
  a24=(a39*a27);
  a50=(a41*a47);
  a24=(a24-a50);
  a24=(a34*a24);
  a49=(a49+a24);
  a26=(a45*a26);
  a26=(a42*a26);
  a49=(a49-a26);
  a26=(a46*a27);
  a47=(a48*a47);
  a26=(a26-a47);
  a27=(a22*a27);
  a26=(a26+a27);
  a49=(a49+a26);
  if (res[0]!=0) res[0][3]=a49;
  a49=cos(a9);
  a26=cos(a6);
  a27=(a49*a26);
  a47=arg[3]? arg[3][3] : 0;
  a27=(a27*a47);
  a24=sin(a6);
  a50=(a49*a24);
  a51=arg[3]? arg[3][4] : 0;
  a50=(a50*a51);
  a27=(a27-a50);
  a50=sin(a9);
  a52=arg[3]? arg[3][5] : 0;
  a50=(a50*a52);
  a27=(a27+a50);
  a50=cos(a16);
  a53=cos(a1);
  a54=sin(a3);
  a55=cos(a5);
  a56=(a54*a55);
  a57=(a53*a56);
  a58=sin(a1);
  a59=sin(a5);
  a60=(a58*a59);
  a57=(a57-a60);
  a60=(a50*a57);
  a61=sin(a16);
  a62=cos(a1);
  a59=(a62*a59);
  a63=sin(a1);
  a56=(a63*a56);
  a59=(a59+a56);
  a56=(a61*a59);
  a60=(a60-a56);
  a60=(a27*a60);
  a56=sin(a23);
  a64=sin(a9);
  a65=(a56*a64);
  a66=(a65*a26);
  a67=cos(a23);
  a68=sin(a6);
  a69=(a67*a68);
  a66=(a66+a69);
  a66=(a66*a47);
  a69=cos(a6);
  a70=(a67*a69);
  a71=(a65*a24);
  a70=(a70-a71);
  a70=(a70*a51);
  a66=(a66+a70);
  a70=cos(a9);
  a71=(a56*a70);
  a71=(a71*a52);
  a66=(a66-a71);
  a71=cos(a16);
  a72=(a71*a59);
  a73=sin(a16);
  a74=(a73*a57);
  a72=(a72+a74);
  a72=(a66*a72);
  a60=(a60-a72);
  a72=sin(a23);
  a74=(a72*a68);
  a75=cos(a23);
  a76=(a75*a64);
  a77=(a76*a26);
  a74=(a74-a77);
  a74=(a74*a47);
  a77=(a76*a24);
  a78=(a72*a69);
  a77=(a77+a78);
  a77=(a77*a51);
  a74=(a74+a77);
  a77=(a75*a70);
  a77=(a77*a52);
  a74=(a74+a77);
  a77=cos(a3);
  a55=(a77*a55);
  a55=(a74*a55);
  a60=(a60-a55);
  a55=(a22*a71);
  a78=(a55*a59);
  a79=(a22*a73);
  a57=(a79*a57);
  a78=(a78+a57);
  a59=(a22*a59);
  a78=(a78+a59);
  a60=(a60-a78);
  if (res[0]!=0) res[0][4]=a60;
  a60=cos(a5);
  a78=(a58*a60);
  a59=sin(a5);
  a57=(a54*a59);
  a80=(a53*a57);
  a78=(a78+a80);
  a80=(a50*a78);
  a60=(a62*a60);
  a57=(a63*a57);
  a60=(a60-a57);
  a57=(a61*a60);
  a80=(a80+a57);
  a80=(a27*a80);
  a57=(a71*a60);
  a81=(a73*a78);
  a57=(a57-a81);
  a57=(a66*a57);
  a80=(a80+a57);
  a59=(a77*a59);
  a59=(a74*a59);
  a80=(a80-a59);
  a59=(a55*a60);
  a78=(a79*a78);
  a59=(a59-a78);
  a60=(a22*a60);
  a59=(a59+a60);
  a80=(a80+a59);
  if (res[0]!=0) res[0][5]=a80;
  a80=cos(a9);
  a59=cos(a6);
  a60=(a80*a59);
  a78=arg[3]? arg[3][6] : 0;
  a60=(a60*a78);
  a57=sin(a6);
  a81=(a80*a57);
  a82=arg[3]? arg[3][7] : 0;
  a81=(a81*a82);
  a60=(a60-a81);
  a81=sin(a9);
  a83=arg[3]? arg[3][8] : 0;
  a81=(a81*a83);
  a60=(a60+a81);
  a81=cos(a16);
  a84=cos(a1);
  a85=sin(a3);
  a86=cos(a5);
  a87=(a85*a86);
  a88=(a84*a87);
  a89=sin(a1);
  a90=sin(a5);
  a91=(a89*a90);
  a88=(a88-a91);
  a91=(a81*a88);
  a92=sin(a16);
  a93=cos(a1);
  a90=(a93*a90);
  a94=sin(a1);
  a87=(a94*a87);
  a90=(a90+a87);
  a87=(a92*a90);
  a91=(a91-a87);
  a91=(a60*a91);
  a87=sin(a23);
  a95=sin(a9);
  a96=(a87*a95);
  a97=(a96*a59);
  a98=cos(a23);
  a99=sin(a6);
  a100=(a98*a99);
  a97=(a97+a100);
  a97=(a97*a78);
  a100=cos(a6);
  a101=(a98*a100);
  a102=(a96*a57);
  a101=(a101-a102);
  a101=(a101*a82);
  a97=(a97+a101);
  a101=cos(a9);
  a102=(a87*a101);
  a102=(a102*a83);
  a97=(a97-a102);
  a102=cos(a16);
  a103=(a102*a90);
  a104=sin(a16);
  a105=(a104*a88);
  a103=(a103+a105);
  a103=(a97*a103);
  a91=(a91-a103);
  a103=sin(a23);
  a105=(a103*a99);
  a106=cos(a23);
  a107=(a106*a95);
  a108=(a107*a59);
  a105=(a105-a108);
  a105=(a105*a78);
  a108=(a107*a57);
  a109=(a103*a100);
  a108=(a108+a109);
  a108=(a108*a82);
  a105=(a105+a108);
  a108=(a106*a101);
  a108=(a108*a83);
  a105=(a105+a108);
  a108=cos(a3);
  a86=(a108*a86);
  a86=(a105*a86);
  a91=(a91-a86);
  a86=(a22*a102);
  a109=(a86*a90);
  a110=(a22*a104);
  a88=(a110*a88);
  a109=(a109+a88);
  a90=(a22*a90);
  a109=(a109+a90);
  a91=(a91-a109);
  if (res[0]!=0) res[0][6]=a91;
  a91=cos(a5);
  a109=(a89*a91);
  a90=sin(a5);
  a88=(a85*a90);
  a111=(a84*a88);
  a109=(a109+a111);
  a111=(a81*a109);
  a91=(a93*a91);
  a88=(a94*a88);
  a91=(a91-a88);
  a88=(a92*a91);
  a111=(a111+a88);
  a111=(a60*a111);
  a88=(a102*a91);
  a112=(a104*a109);
  a88=(a88-a112);
  a88=(a97*a88);
  a111=(a111+a88);
  a90=(a108*a90);
  a90=(a105*a90);
  a111=(a111-a90);
  a90=(a86*a91);
  a109=(a110*a109);
  a90=(a90-a109);
  a91=(a22*a91);
  a90=(a90+a91);
  a111=(a111+a90);
  if (res[0]!=0) res[0][7]=a111;
  a111=sin(a3);
  a90=(a13*a111);
  a90=(a11*a90);
  a111=(a2*a111);
  a111=(a0*a111);
  a90=(a90-a111);
  a111=cos(a3);
  a111=(a10*a111);
  a90=(a90+a111);
  if (res[0]!=0) res[0][8]=a90;
  a90=sin(a5);
  a111=cos(a3);
  a91=(a90*a111);
  a109=(a2*a91);
  a109=(a0*a109);
  a91=(a13*a91);
  a91=(a11*a91);
  a109=(a109-a91);
  a91=sin(a3);
  a88=(a90*a91);
  a88=(a10*a88);
  a109=(a109+a88);
  if (res[0]!=0) res[0][9]=a109;
  a109=cos(a5);
  a111=(a109*a111);
  a13=(a13*a111);
  a13=(a11*a13);
  a2=(a2*a111);
  a2=(a0*a2);
  a13=(a13-a2);
  a91=(a109*a91);
  a10=(a10*a91);
  a13=(a13-a10);
  if (res[0]!=0) res[0][10]=a13;
  a13=sin(a3);
  a10=(a30*a13);
  a91=(a28*a10);
  a13=(a20*a13);
  a2=(a19*a13);
  a91=(a91-a2);
  a91=(a14*a91);
  a2=(a41*a13);
  a111=(a39*a10);
  a2=(a2+a111);
  a2=(a34*a2);
  a91=(a91+a2);
  a2=cos(a3);
  a2=(a42*a2);
  a91=(a91+a2);
  a13=(a48*a13);
  a2=(a46*a10);
  a13=(a13+a2);
  a10=(a22*a10);
  a13=(a13+a10);
  a91=(a91+a13);
  if (res[0]!=0) res[0][11]=a91;
  a91=sin(a5);
  a13=cos(a3);
  a10=(a91*a13);
  a2=(a20*a10);
  a111=(a19*a2);
  a10=(a30*a10);
  a88=(a28*a10);
  a111=(a111-a88);
  a111=(a14*a111);
  a88=(a39*a10);
  a112=(a41*a2);
  a88=(a88+a112);
  a88=(a34*a88);
  a111=(a111-a88);
  a88=sin(a3);
  a112=(a91*a88);
  a112=(a42*a112);
  a111=(a111+a112);
  a112=(a46*a10);
  a2=(a48*a2);
  a112=(a112+a2);
  a10=(a22*a10);
  a112=(a112+a10);
  a111=(a111-a112);
  if (res[0]!=0) res[0][12]=a111;
  a111=cos(a5);
  a13=(a111*a13);
  a112=(a30*a13);
  a10=(a28*a112);
  a13=(a20*a13);
  a2=(a19*a13);
  a10=(a10-a2);
  a10=(a14*a10);
  a2=(a39*a112);
  a113=(a41*a13);
  a2=(a2+a113);
  a2=(a34*a2);
  a10=(a10+a2);
  a88=(a111*a88);
  a42=(a42*a88);
  a10=(a10-a42);
  a42=(a46*a112);
  a13=(a48*a13);
  a42=(a42+a13);
  a112=(a22*a112);
  a42=(a42+a112);
  a10=(a10+a42);
  if (res[0]!=0) res[0][13]=a10;
  a10=sin(a3);
  a42=(a63*a10);
  a112=(a61*a42);
  a10=(a53*a10);
  a13=(a50*a10);
  a112=(a112-a13);
  a112=(a27*a112);
  a13=(a73*a10);
  a88=(a71*a42);
  a13=(a13+a88);
  a13=(a66*a13);
  a112=(a112+a13);
  a13=cos(a3);
  a13=(a74*a13);
  a112=(a112+a13);
  a10=(a79*a10);
  a13=(a55*a42);
  a10=(a10+a13);
  a42=(a22*a42);
  a10=(a10+a42);
  a112=(a112+a10);
  if (res[0]!=0) res[0][14]=a112;
  a112=sin(a5);
  a10=cos(a3);
  a42=(a112*a10);
  a13=(a53*a42);
  a88=(a50*a13);
  a42=(a63*a42);
  a2=(a61*a42);
  a88=(a88-a2);
  a88=(a27*a88);
  a2=(a71*a42);
  a113=(a73*a13);
  a2=(a2+a113);
  a2=(a66*a2);
  a88=(a88-a2);
  a2=sin(a3);
  a113=(a112*a2);
  a113=(a74*a113);
  a88=(a88+a113);
  a113=(a55*a42);
  a13=(a79*a13);
  a113=(a113+a13);
  a42=(a22*a42);
  a113=(a113+a42);
  a88=(a88-a113);
  if (res[0]!=0) res[0][15]=a88;
  a88=cos(a5);
  a10=(a88*a10);
  a113=(a63*a10);
  a42=(a61*a113);
  a10=(a53*a10);
  a13=(a50*a10);
  a42=(a42-a13);
  a42=(a27*a42);
  a13=(a71*a113);
  a114=(a73*a10);
  a13=(a13+a114);
  a13=(a66*a13);
  a42=(a42+a13);
  a2=(a88*a2);
  a74=(a74*a2);
  a42=(a42-a74);
  a74=(a55*a113);
  a10=(a79*a10);
  a74=(a74+a10);
  a113=(a22*a113);
  a74=(a74+a113);
  a42=(a42+a74);
  if (res[0]!=0) res[0][16]=a42;
  a42=sin(a3);
  a74=(a94*a42);
  a113=(a92*a74);
  a42=(a84*a42);
  a10=(a81*a42);
  a113=(a113-a10);
  a113=(a60*a113);
  a10=(a104*a42);
  a2=(a102*a74);
  a10=(a10+a2);
  a10=(a97*a10);
  a113=(a113+a10);
  a10=cos(a3);
  a10=(a105*a10);
  a113=(a113+a10);
  a42=(a110*a42);
  a10=(a86*a74);
  a42=(a42+a10);
  a74=(a22*a74);
  a42=(a42+a74);
  a113=(a113+a42);
  if (res[0]!=0) res[0][17]=a113;
  a113=sin(a5);
  a42=cos(a3);
  a74=(a113*a42);
  a10=(a84*a74);
  a2=(a81*a10);
  a74=(a94*a74);
  a13=(a92*a74);
  a2=(a2-a13);
  a2=(a60*a2);
  a13=(a102*a74);
  a114=(a104*a10);
  a13=(a13+a114);
  a13=(a97*a13);
  a2=(a2-a13);
  a13=sin(a3);
  a114=(a113*a13);
  a114=(a105*a114);
  a2=(a2+a114);
  a114=(a86*a74);
  a10=(a110*a10);
  a114=(a114+a10);
  a74=(a22*a74);
  a114=(a114+a74);
  a2=(a2-a114);
  if (res[0]!=0) res[0][18]=a2;
  a2=cos(a5);
  a42=(a2*a42);
  a114=(a94*a42);
  a74=(a92*a114);
  a42=(a84*a42);
  a10=(a81*a42);
  a74=(a74-a10);
  a74=(a60*a74);
  a10=(a102*a114);
  a115=(a104*a42);
  a10=(a10+a115);
  a10=(a97*a10);
  a74=(a74+a10);
  a13=(a2*a13);
  a105=(a105*a13);
  a74=(a74-a105);
  a105=(a86*a114);
  a42=(a110*a42);
  a105=(a105+a42);
  a114=(a22*a114);
  a105=(a105+a114);
  a74=(a74+a105);
  if (res[0]!=0) res[0][19]=a74;
  a74=cos(a3);
  a105=sin(a1);
  a114=(a74*a105);
  a114=(a0*a114);
  a42=cos(a1);
  a74=(a74*a42);
  a74=(a11*a74);
  a114=(a114+a74);
  a114=(-a114);
  if (res[0]!=0) res[0][20]=a114;
  a114=cos(a5);
  a74=cos(a1);
  a13=(a114*a74);
  a90=(a90*a4);
  a10=(a90*a105);
  a13=(a13-a10);
  a13=(a0*a13);
  a10=sin(a1);
  a114=(a114*a10);
  a90=(a90*a42);
  a114=(a114+a90);
  a114=(a11*a114);
  a13=(a13-a114);
  if (res[0]!=0) res[0][21]=a13;
  a13=sin(a5);
  a74=(a13*a74);
  a109=(a109*a4);
  a105=(a109*a105);
  a74=(a74+a105);
  a0=(a0*a74);
  a109=(a109*a42);
  a13=(a13*a10);
  a109=(a109-a13);
  a11=(a11*a109);
  a0=(a0+a11);
  if (res[0]!=0) res[0][22]=a0;
  a0=cos(a3);
  a11=sin(a1);
  a109=(a0*a11);
  a13=(a19*a109);
  a10=cos(a1);
  a42=(a0*a10);
  a74=(a28*a42);
  a13=(a13+a74);
  a13=(a14*a13);
  a74=(a39*a42);
  a105=(a41*a109);
  a74=(a74-a105);
  a74=(a34*a74);
  a13=(a13+a74);
  a74=(a46*a42);
  a109=(a48*a109);
  a74=(a74-a109);
  a42=(a22*a42);
  a74=(a74+a42);
  a13=(a13+a74);
  a13=(-a13);
  if (res[0]!=0) res[0][23]=a13;
  a13=cos(a5);
  a74=cos(a1);
  a42=(a13*a74);
  a109=(a91*a21);
  a105=(a109*a11);
  a42=(a42-a105);
  a105=(a19*a42);
  a4=sin(a1);
  a114=(a13*a4);
  a90=(a109*a10);
  a114=(a114+a90);
  a90=(a28*a114);
  a105=(a105-a90);
  a105=(a14*a105);
  a90=(a39*a114);
  a115=(a41*a42);
  a90=(a90+a115);
  a90=(a34*a90);
  a105=(a105-a90);
  a90=(a46*a114);
  a42=(a48*a42);
  a90=(a90+a42);
  a114=(a22*a114);
  a90=(a90+a114);
  a105=(a105-a90);
  if (res[0]!=0) res[0][24]=a105;
  a105=sin(a5);
  a74=(a105*a74);
  a21=(a111*a21);
  a11=(a21*a11);
  a74=(a74+a11);
  a11=(a19*a74);
  a10=(a21*a10);
  a4=(a105*a4);
  a10=(a10-a4);
  a4=(a28*a10);
  a11=(a11+a4);
  a11=(a14*a11);
  a4=(a39*a10);
  a90=(a41*a74);
  a4=(a4-a90);
  a4=(a34*a4);
  a11=(a11+a4);
  a46=(a46*a10);
  a48=(a48*a74);
  a46=(a46-a48);
  a10=(a22*a10);
  a46=(a46+a10);
  a11=(a11+a46);
  if (res[0]!=0) res[0][25]=a11;
  a11=cos(a3);
  a46=sin(a1);
  a10=(a11*a46);
  a48=(a50*a10);
  a74=cos(a1);
  a4=(a11*a74);
  a90=(a61*a4);
  a48=(a48+a90);
  a48=(a27*a48);
  a90=(a71*a4);
  a114=(a73*a10);
  a90=(a90-a114);
  a90=(a66*a90);
  a48=(a48+a90);
  a90=(a55*a4);
  a10=(a79*a10);
  a90=(a90-a10);
  a4=(a22*a4);
  a90=(a90+a4);
  a48=(a48+a90);
  a48=(-a48);
  if (res[0]!=0) res[0][26]=a48;
  a48=cos(a5);
  a90=cos(a1);
  a4=(a48*a90);
  a10=(a112*a54);
  a114=(a10*a46);
  a4=(a4-a114);
  a114=(a50*a4);
  a42=sin(a1);
  a115=(a48*a42);
  a116=(a10*a74);
  a115=(a115+a116);
  a116=(a61*a115);
  a114=(a114-a116);
  a114=(a27*a114);
  a116=(a71*a115);
  a117=(a73*a4);
  a116=(a116+a117);
  a116=(a66*a116);
  a114=(a114-a116);
  a116=(a55*a115);
  a4=(a79*a4);
  a116=(a116+a4);
  a115=(a22*a115);
  a116=(a116+a115);
  a114=(a114-a116);
  if (res[0]!=0) res[0][27]=a114;
  a114=sin(a5);
  a90=(a114*a90);
  a54=(a88*a54);
  a46=(a54*a46);
  a90=(a90+a46);
  a46=(a50*a90);
  a74=(a54*a74);
  a42=(a114*a42);
  a74=(a74-a42);
  a42=(a61*a74);
  a46=(a46+a42);
  a46=(a27*a46);
  a42=(a71*a74);
  a116=(a73*a90);
  a42=(a42-a116);
  a42=(a66*a42);
  a46=(a46+a42);
  a55=(a55*a74);
  a79=(a79*a90);
  a55=(a55-a79);
  a74=(a22*a74);
  a55=(a55+a74);
  a46=(a46+a55);
  if (res[0]!=0) res[0][28]=a46;
  a46=cos(a3);
  a55=sin(a1);
  a74=(a46*a55);
  a79=(a81*a74);
  a90=cos(a1);
  a42=(a46*a90);
  a116=(a92*a42);
  a79=(a79+a116);
  a79=(a60*a79);
  a116=(a102*a42);
  a115=(a104*a74);
  a116=(a116-a115);
  a116=(a97*a116);
  a79=(a79+a116);
  a116=(a86*a42);
  a74=(a110*a74);
  a116=(a116-a74);
  a42=(a22*a42);
  a116=(a116+a42);
  a79=(a79+a116);
  a79=(-a79);
  if (res[0]!=0) res[0][29]=a79;
  a79=cos(a5);
  a116=cos(a1);
  a42=(a79*a116);
  a74=(a113*a85);
  a115=(a74*a55);
  a42=(a42-a115);
  a115=(a81*a42);
  a1=sin(a1);
  a4=(a79*a1);
  a117=(a74*a90);
  a4=(a4+a117);
  a117=(a92*a4);
  a115=(a115-a117);
  a115=(a60*a115);
  a117=(a102*a4);
  a118=(a104*a42);
  a117=(a117+a118);
  a117=(a97*a117);
  a115=(a115-a117);
  a117=(a86*a4);
  a42=(a110*a42);
  a117=(a117+a42);
  a4=(a22*a4);
  a117=(a117+a4);
  a115=(a115-a117);
  if (res[0]!=0) res[0][30]=a115;
  a5=sin(a5);
  a116=(a5*a116);
  a85=(a2*a85);
  a55=(a85*a55);
  a116=(a116+a55);
  a55=(a81*a116);
  a90=(a85*a90);
  a1=(a5*a1);
  a90=(a90-a1);
  a1=(a92*a90);
  a55=(a55+a1);
  a55=(a60*a55);
  a1=(a102*a90);
  a115=(a104*a116);
  a1=(a1-a115);
  a1=(a97*a1);
  a55=(a55+a1);
  a86=(a86*a90);
  a110=(a110*a116);
  a86=(a86-a110);
  a90=(a22*a90);
  a86=(a86+a90);
  a55=(a55+a86);
  if (res[0]!=0) res[0][31]=a55;
  a55=(a0*a20);
  a86=sin(a16);
  a90=(a55*a86);
  a0=(a0*a30);
  a110=cos(a16);
  a116=(a0*a110);
  a90=(a90+a116);
  a90=(a14*a90);
  a116=cos(a16);
  a1=(a55*a116);
  a115=sin(a16);
  a117=(a0*a115);
  a1=(a1-a117);
  a1=(a34*a1);
  a90=(a90+a1);
  a1=(a22*a116);
  a117=(a55*a1);
  a4=(a22*a115);
  a42=(a0*a4);
  a117=(a117-a42);
  a90=(a90+a117);
  a90=(-a90);
  if (res[0]!=0) res[0][32]=a90;
  a90=(a13*a29);
  a117=(a109*a30);
  a90=(a90-a117);
  a117=(a90*a110);
  a109=(a109*a20);
  a13=(a13*a25);
  a109=(a109+a13);
  a13=(a109*a86);
  a117=(a117-a13);
  a117=(a14*a117);
  a13=(a90*a115);
  a42=(a109*a116);
  a13=(a13+a42);
  a13=(a34*a13);
  a117=(a117-a13);
  a13=(a90*a4);
  a42=(a109*a1);
  a13=(a13+a42);
  a117=(a117-a13);
  if (res[0]!=0) res[0][33]=a117;
  a30=(a21*a30);
  a29=(a105*a29);
  a30=(a30+a29);
  a110=(a30*a110);
  a105=(a105*a25);
  a21=(a21*a20);
  a105=(a105-a21);
  a86=(a105*a86);
  a110=(a110-a86);
  a14=(a14*a110);
  a115=(a30*a115);
  a116=(a105*a116);
  a115=(a115+a116);
  a34=(a34*a115);
  a14=(a14-a34);
  a4=(a30*a4);
  a1=(a105*a1);
  a4=(a4+a1);
  a14=(a14-a4);
  if (res[0]!=0) res[0][34]=a14;
  a14=(a11*a53);
  a4=sin(a16);
  a1=(a14*a4);
  a11=(a11*a63);
  a34=cos(a16);
  a115=(a11*a34);
  a1=(a1+a115);
  a1=(a27*a1);
  a115=cos(a16);
  a116=(a14*a115);
  a110=sin(a16);
  a86=(a11*a110);
  a116=(a116-a86);
  a116=(a66*a116);
  a1=(a1+a116);
  a116=(a22*a115);
  a86=(a14*a116);
  a21=(a22*a110);
  a20=(a11*a21);
  a86=(a86-a20);
  a1=(a1+a86);
  a1=(-a1);
  if (res[0]!=0) res[0][35]=a1;
  a1=(a48*a62);
  a86=(a10*a63);
  a1=(a1-a86);
  a86=(a1*a34);
  a10=(a10*a53);
  a48=(a48*a58);
  a10=(a10+a48);
  a48=(a10*a4);
  a86=(a86-a48);
  a86=(a27*a86);
  a48=(a1*a110);
  a20=(a10*a115);
  a48=(a48+a20);
  a48=(a66*a48);
  a86=(a86-a48);
  a48=(a1*a21);
  a20=(a10*a116);
  a48=(a48+a20);
  a86=(a86-a48);
  if (res[0]!=0) res[0][36]=a86;
  a63=(a54*a63);
  a62=(a114*a62);
  a63=(a63+a62);
  a34=(a63*a34);
  a114=(a114*a58);
  a54=(a54*a53);
  a114=(a114-a54);
  a4=(a114*a4);
  a34=(a34-a4);
  a27=(a27*a34);
  a110=(a63*a110);
  a115=(a114*a115);
  a110=(a110+a115);
  a66=(a66*a110);
  a27=(a27-a66);
  a21=(a63*a21);
  a116=(a114*a116);
  a21=(a21+a116);
  a27=(a27-a21);
  if (res[0]!=0) res[0][37]=a27;
  a27=(a46*a84);
  a21=sin(a16);
  a116=(a27*a21);
  a46=(a46*a94);
  a66=cos(a16);
  a110=(a46*a66);
  a116=(a116+a110);
  a116=(a60*a116);
  a110=cos(a16);
  a115=(a27*a110);
  a16=sin(a16);
  a34=(a46*a16);
  a115=(a115-a34);
  a115=(a97*a115);
  a116=(a116+a115);
  a115=(a22*a110);
  a34=(a27*a115);
  a22=(a22*a16);
  a4=(a46*a22);
  a34=(a34-a4);
  a116=(a116+a34);
  a116=(-a116);
  if (res[0]!=0) res[0][38]=a116;
  a116=(a79*a93);
  a34=(a74*a94);
  a116=(a116-a34);
  a34=(a116*a66);
  a74=(a74*a84);
  a79=(a79*a89);
  a74=(a74+a79);
  a79=(a74*a21);
  a34=(a34-a79);
  a34=(a60*a34);
  a79=(a116*a16);
  a4=(a74*a110);
  a79=(a79+a4);
  a79=(a97*a79);
  a34=(a34-a79);
  a79=(a116*a22);
  a4=(a74*a115);
  a79=(a79+a4);
  a34=(a34-a79);
  if (res[0]!=0) res[0][39]=a34;
  a94=(a85*a94);
  a93=(a5*a93);
  a94=(a94+a93);
  a66=(a94*a66);
  a5=(a5*a89);
  a85=(a85*a84);
  a5=(a5-a85);
  a21=(a5*a21);
  a66=(a66-a21);
  a60=(a60*a66);
  a16=(a94*a16);
  a110=(a5*a110);
  a16=(a16+a110);
  a97=(a97*a16);
  a60=(a60-a97);
  a22=(a94*a22);
  a115=(a5*a115);
  a22=(a22+a115);
  a60=(a60-a22);
  if (res[0]!=0) res[0][40]=a60;
  a60=sin(a3);
  a22=cos(a23);
  a115=(a36*a22);
  a97=sin(a23);
  a16=(a32*a97);
  a110=(a12*a16);
  a115=(a115+a110);
  a115=(a8*a115);
  a22=(a37*a22);
  a16=(a15*a16);
  a22=(a22-a16);
  a22=(a17*a22);
  a115=(a115+a22);
  a97=(a38*a97);
  a97=(a18*a97);
  a115=(a115-a97);
  a97=(a60*a115);
  a22=(a55*a41);
  a16=(a0*a39);
  a22=(a22+a16);
  a16=cos(a23);
  a32=(a32*a16);
  a110=(a12*a32);
  a66=sin(a23);
  a36=(a36*a66);
  a110=(a110-a36);
  a110=(a8*a110);
  a37=(a37*a66);
  a32=(a15*a32);
  a37=(a37+a32);
  a37=(a17*a37);
  a110=(a110-a37);
  a38=(a38*a16);
  a38=(a18*a38);
  a110=(a110-a38);
  a38=(a22*a110);
  a97=(a97-a38);
  if (res[0]!=0) res[0][41]=a97;
  a97=(a90*a39);
  a38=(a109*a41);
  a97=(a97-a38);
  a38=(a97*a110);
  a91=(a91*a45);
  a16=(a91*a115);
  a38=(a38-a16);
  if (res[0]!=0) res[0][42]=a38;
  a39=(a30*a39);
  a41=(a105*a41);
  a39=(a39-a41);
  a110=(a39*a110);
  a111=(a111*a45);
  a115=(a111*a115);
  a110=(a110+a115);
  if (res[0]!=0) res[0][43]=a110;
  a110=sin(a3);
  a115=cos(a23);
  a45=(a68*a115);
  a41=sin(a23);
  a38=(a64*a41);
  a16=(a26*a38);
  a45=(a45+a16);
  a45=(a47*a45);
  a115=(a69*a115);
  a38=(a24*a38);
  a115=(a115-a38);
  a115=(a51*a115);
  a45=(a45+a115);
  a41=(a70*a41);
  a41=(a52*a41);
  a45=(a45-a41);
  a41=(a110*a45);
  a115=(a14*a73);
  a38=(a11*a71);
  a115=(a115+a38);
  a38=cos(a23);
  a64=(a64*a38);
  a16=(a26*a64);
  a37=sin(a23);
  a68=(a68*a37);
  a16=(a16-a68);
  a16=(a47*a16);
  a69=(a69*a37);
  a64=(a24*a64);
  a69=(a69+a64);
  a69=(a51*a69);
  a16=(a16-a69);
  a70=(a70*a38);
  a70=(a52*a70);
  a16=(a16-a70);
  a70=(a115*a16);
  a41=(a41-a70);
  if (res[0]!=0) res[0][44]=a41;
  a41=(a1*a71);
  a70=(a10*a73);
  a41=(a41-a70);
  a70=(a41*a16);
  a112=(a112*a77);
  a38=(a112*a45);
  a70=(a70-a38);
  if (res[0]!=0) res[0][45]=a70;
  a71=(a63*a71);
  a73=(a114*a73);
  a71=(a71-a73);
  a16=(a71*a16);
  a88=(a88*a77);
  a45=(a88*a45);
  a16=(a16+a45);
  if (res[0]!=0) res[0][46]=a16;
  a3=sin(a3);
  a16=cos(a23);
  a45=(a99*a16);
  a77=sin(a23);
  a73=(a95*a77);
  a70=(a59*a73);
  a45=(a45+a70);
  a45=(a78*a45);
  a16=(a100*a16);
  a73=(a57*a73);
  a16=(a16-a73);
  a16=(a82*a16);
  a45=(a45+a16);
  a77=(a101*a77);
  a77=(a83*a77);
  a45=(a45-a77);
  a77=(a3*a45);
  a16=(a27*a104);
  a73=(a46*a102);
  a16=(a16+a73);
  a73=cos(a23);
  a95=(a95*a73);
  a70=(a59*a95);
  a23=sin(a23);
  a99=(a99*a23);
  a70=(a70-a99);
  a70=(a78*a70);
  a100=(a100*a23);
  a95=(a57*a95);
  a100=(a100+a95);
  a100=(a82*a100);
  a70=(a70-a100);
  a101=(a101*a73);
  a101=(a83*a101);
  a70=(a70-a101);
  a101=(a16*a70);
  a77=(a77-a101);
  if (res[0]!=0) res[0][47]=a77;
  a77=(a116*a102);
  a101=(a74*a104);
  a77=(a77-a101);
  a101=(a77*a70);
  a113=(a113*a108);
  a73=(a113*a45);
  a101=(a101-a73);
  if (res[0]!=0) res[0][48]=a101;
  a102=(a94*a102);
  a104=(a5*a104);
  a102=(a102-a104);
  a70=(a102*a70);
  a2=(a2*a108);
  a45=(a2*a45);
  a70=(a70+a45);
  if (res[0]!=0) res[0][49]=a70;
  a55=(a55*a19);
  a0=(a0*a28);
  a55=(a55-a0);
  a0=sin(a9);
  a70=(a15*a0);
  a70=(a17*a70);
  a0=(a12*a0);
  a0=(a8*a0);
  a70=(a70-a0);
  a0=cos(a9);
  a0=(a18*a0);
  a70=(a70+a0);
  a0=(a55*a70);
  a45=cos(a9);
  a108=(a31*a45);
  a104=(a12*a108);
  a104=(a8*a104);
  a108=(a15*a108);
  a108=(a17*a108);
  a104=(a104-a108);
  a108=sin(a9);
  a31=(a31*a108);
  a31=(a18*a31);
  a104=(a104+a31);
  a31=(a22*a104);
  a0=(a0-a31);
  a45=(a43*a45);
  a15=(a15*a45);
  a15=(a17*a15);
  a12=(a12*a45);
  a12=(a8*a12);
  a15=(a15-a12);
  a43=(a43*a108);
  a18=(a18*a43);
  a15=(a15-a18);
  a18=(a60*a15);
  a0=(a0+a18);
  if (res[0]!=0) res[0][50]=a0;
  a109=(a109*a19);
  a90=(a90*a28);
  a109=(a109+a90);
  a90=(a109*a70);
  a0=(a97*a104);
  a90=(a90+a0);
  a0=(a91*a15);
  a90=(a90-a0);
  if (res[0]!=0) res[0][51]=a90;
  a105=(a105*a19);
  a30=(a30*a28);
  a105=(a105+a30);
  a70=(a105*a70);
  a104=(a39*a104);
  a70=(a70+a104);
  a15=(a111*a15);
  a70=(a70+a15);
  if (res[0]!=0) res[0][52]=a70;
  a14=(a14*a50);
  a11=(a11*a61);
  a14=(a14-a11);
  a11=sin(a9);
  a70=(a24*a11);
  a70=(a51*a70);
  a11=(a26*a11);
  a11=(a47*a11);
  a70=(a70-a11);
  a11=cos(a9);
  a11=(a52*a11);
  a70=(a70+a11);
  a11=(a14*a70);
  a15=cos(a9);
  a104=(a56*a15);
  a30=(a26*a104);
  a30=(a47*a30);
  a104=(a24*a104);
  a104=(a51*a104);
  a30=(a30-a104);
  a104=sin(a9);
  a56=(a56*a104);
  a56=(a52*a56);
  a30=(a30+a56);
  a56=(a115*a30);
  a11=(a11-a56);
  a15=(a75*a15);
  a24=(a24*a15);
  a24=(a51*a24);
  a26=(a26*a15);
  a26=(a47*a26);
  a24=(a24-a26);
  a75=(a75*a104);
  a52=(a52*a75);
  a24=(a24-a52);
  a52=(a110*a24);
  a11=(a11+a52);
  if (res[0]!=0) res[0][53]=a11;
  a10=(a10*a50);
  a1=(a1*a61);
  a10=(a10+a1);
  a1=(a10*a70);
  a11=(a41*a30);
  a1=(a1+a11);
  a11=(a112*a24);
  a1=(a1-a11);
  if (res[0]!=0) res[0][54]=a1;
  a114=(a114*a50);
  a63=(a63*a61);
  a114=(a114+a63);
  a70=(a114*a70);
  a30=(a71*a30);
  a70=(a70+a30);
  a24=(a88*a24);
  a70=(a70+a24);
  if (res[0]!=0) res[0][55]=a70;
  a27=(a27*a81);
  a46=(a46*a92);
  a27=(a27-a46);
  a46=sin(a9);
  a70=(a57*a46);
  a70=(a82*a70);
  a46=(a59*a46);
  a46=(a78*a46);
  a70=(a70-a46);
  a46=cos(a9);
  a46=(a83*a46);
  a70=(a70+a46);
  a46=(a27*a70);
  a24=cos(a9);
  a30=(a87*a24);
  a63=(a59*a30);
  a63=(a78*a63);
  a30=(a57*a30);
  a30=(a82*a30);
  a63=(a63-a30);
  a9=sin(a9);
  a87=(a87*a9);
  a87=(a83*a87);
  a63=(a63+a87);
  a87=(a16*a63);
  a46=(a46-a87);
  a24=(a106*a24);
  a57=(a57*a24);
  a57=(a82*a57);
  a59=(a59*a24);
  a59=(a78*a59);
  a57=(a57-a59);
  a106=(a106*a9);
  a83=(a83*a106);
  a57=(a57-a83);
  a83=(a3*a57);
  a46=(a46+a83);
  if (res[0]!=0) res[0][56]=a46;
  a74=(a74*a81);
  a116=(a116*a92);
  a74=(a74+a116);
  a116=(a74*a70);
  a46=(a77*a63);
  a116=(a116+a46);
  a46=(a113*a57);
  a116=(a116-a46);
  if (res[0]!=0) res[0][57]=a116;
  a5=(a5*a81);
  a94=(a94*a92);
  a5=(a5+a94);
  a70=(a5*a70);
  a63=(a102*a63);
  a70=(a70+a63);
  a57=(a2*a57);
  a70=(a70+a57);
  if (res[0]!=0) res[0][58]=a70;
  a70=cos(a6);
  a57=(a40*a70);
  a63=sin(a6);
  a94=(a44*a63);
  a57=(a57+a94);
  a57=(a8*a57);
  a94=cos(a6);
  a44=(a44*a94);
  a92=sin(a6);
  a40=(a40*a92);
  a44=(a44-a40);
  a44=(a17*a44);
  a57=(a57+a44);
  a60=(a60*a57);
  a44=(a7*a63);
  a44=(a8*a44);
  a7=(a7*a94);
  a7=(a17*a7);
  a44=(a44+a7);
  a55=(a55*a44);
  a70=(a35*a70);
  a63=(a33*a63);
  a70=(a70-a63);
  a8=(a8*a70);
  a35=(a35*a92);
  a33=(a33*a94);
  a35=(a35+a33);
  a17=(a17*a35);
  a8=(a8-a17);
  a22=(a22*a8);
  a55=(a55+a22);
  a60=(a60-a55);
  if (res[0]!=0) res[0][59]=a60;
  a97=(a97*a8);
  a109=(a109*a44);
  a97=(a97-a109);
  a91=(a91*a57);
  a97=(a97-a91);
  if (res[0]!=0) res[0][60]=a97;
  a39=(a39*a8);
  a105=(a105*a44);
  a39=(a39-a105);
  a111=(a111*a57);
  a39=(a39+a111);
  if (res[0]!=0) res[0][61]=a39;
  a39=cos(a6);
  a111=(a72*a39);
  a57=sin(a6);
  a105=(a76*a57);
  a111=(a111+a105);
  a111=(a47*a111);
  a105=cos(a6);
  a76=(a76*a105);
  a44=sin(a6);
  a72=(a72*a44);
  a76=(a76-a72);
  a76=(a51*a76);
  a111=(a111+a76);
  a110=(a110*a111);
  a76=(a49*a57);
  a76=(a47*a76);
  a49=(a49*a105);
  a49=(a51*a49);
  a76=(a76+a49);
  a14=(a14*a76);
  a39=(a67*a39);
  a57=(a65*a57);
  a39=(a39-a57);
  a47=(a47*a39);
  a67=(a67*a44);
  a65=(a65*a105);
  a67=(a67+a65);
  a51=(a51*a67);
  a47=(a47-a51);
  a115=(a115*a47);
  a14=(a14+a115);
  a110=(a110-a14);
  if (res[0]!=0) res[0][62]=a110;
  a41=(a41*a47);
  a10=(a10*a76);
  a41=(a41-a10);
  a112=(a112*a111);
  a41=(a41-a112);
  if (res[0]!=0) res[0][63]=a41;
  a71=(a71*a47);
  a114=(a114*a76);
  a71=(a71-a114);
  a88=(a88*a111);
  a71=(a71+a88);
  if (res[0]!=0) res[0][64]=a71;
  a71=cos(a6);
  a88=(a103*a71);
  a111=sin(a6);
  a114=(a107*a111);
  a88=(a88+a114);
  a88=(a78*a88);
  a114=cos(a6);
  a107=(a107*a114);
  a6=sin(a6);
  a103=(a103*a6);
  a107=(a107-a103);
  a107=(a82*a107);
  a88=(a88+a107);
  a3=(a3*a88);
  a107=(a80*a111);
  a107=(a78*a107);
  a80=(a80*a114);
  a80=(a82*a80);
  a107=(a107+a80);
  a27=(a27*a107);
  a71=(a98*a71);
  a111=(a96*a111);
  a71=(a71-a111);
  a78=(a78*a71);
  a98=(a98*a6);
  a96=(a96*a114);
  a98=(a98+a96);
  a82=(a82*a98);
  a78=(a78-a82);
  a16=(a16*a78);
  a27=(a27+a16);
  a3=(a3-a27);
  if (res[0]!=0) res[0][65]=a3;
  a77=(a77*a78);
  a74=(a74*a107);
  a77=(a77-a74);
  a113=(a113*a88);
  a77=(a77-a113);
  if (res[0]!=0) res[0][66]=a77;
  a102=(a102*a78);
  a5=(a5*a107);
  a102=(a102-a5);
  a2=(a2*a88);
  a102=(a102+a2);
  if (res[0]!=0) res[0][67]=a102;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_J_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_J(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[206];
  casadi_int *iw = 0;
  const casadi_real* arg[4] = {0};
  casadi_real* res[1] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+87);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+87);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+10, casadi_s2, w+87);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+10, casadi_s3, w+87);
  --resc;
  res[0] = w+19;
  i = f_J(arg, res, iw, w+87, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s4, res[0]);
}
#endif

casadi_int main_f_J(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[206];
  const casadi_real* arg[4];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+7;
  arg[2] = w+10;
  arg[3] = w+10;
  res[0] = w+19;
  a = w;
  for (j=0; j<19; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_J(arg, res, iw, w+87, 0);
  if (flag) return flag;
  r = w+19;
  for (j=0; j<68; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[4];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_J(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_J")==0) {
    mex_f_J(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_J'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_J")==0) {
    return main_f_J(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_J'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
