/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) f_J_mex_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[11] = {3, 2, 0, 3, 6, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s3[80] = {15, 7, 0, 10, 25, 40, 52, 58, 64, 70, 1, 2, 4, 5, 7, 8, 10, 11, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 9, 10, 11, 12, 13, 14, 9, 10, 11, 12, 13, 14, 9, 10, 11, 12, 13, 14};

/* f_J:(i0[7],i1[3],i2[3x2],i3[3x2])->(o0[15x7,70nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[1]? arg[1][0] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=arg[0]? arg[0][1] : 0;
  a4=sin(a3);
  a5=arg[0]? arg[0][0] : 0;
  a6=cos(a5);
  a7=(a4*a6);
  a8=(a2*a7);
  a9=sin(a1);
  a10=sin(a5);
  a11=(a9*a10);
  a8=(a8-a11);
  a8=(a0*a8);
  a11=arg[1]? arg[1][1] : 0;
  a12=cos(a1);
  a10=(a12*a10);
  a13=sin(a1);
  a7=(a13*a7);
  a10=(a10+a7);
  a10=(a11*a10);
  a8=(a8-a10);
  a10=arg[1]? arg[1][2] : 0;
  a7=cos(a3);
  a6=(a7*a6);
  a6=(a10*a6);
  a8=(a8-a6);
  if (res[0]!=0) res[0][0]=a8;
  a8=cos(a5);
  a9=(a9*a8);
  a6=sin(a5);
  a14=(a4*a6);
  a15=(a2*a14);
  a9=(a9+a15);
  a9=(a0*a9);
  a12=(a12*a8);
  a14=(a13*a14);
  a12=(a12-a14);
  a12=(a11*a12);
  a9=(a9+a12);
  a7=(a7*a6);
  a7=(a10*a7);
  a9=(a9-a7);
  if (res[0]!=0) res[0][1]=a9;
  a9=arg[0]? arg[0][3] : 0;
  a7=cos(a9);
  a6=arg[2]? arg[2][0] : 0;
  a7=(a7*a6);
  a12=sin(a9);
  a14=arg[2]? arg[2][1] : 0;
  a12=(a12*a14);
  a7=(a7-a12);
  a12=cos(a1);
  a8=sin(a3);
  a15=cos(a5);
  a16=(a8*a15);
  a17=(a12*a16);
  a18=sin(a1);
  a19=sin(a5);
  a20=(a18*a19);
  a17=(a17-a20);
  a17=(a7*a17);
  a20=sin(a9);
  a20=(a20*a6);
  a21=cos(a9);
  a21=(a21*a14);
  a20=(a20+a21);
  a21=cos(a1);
  a19=(a21*a19);
  a22=sin(a1);
  a16=(a22*a16);
  a19=(a19+a16);
  a16=(a20*a19);
  a17=(a17-a16);
  a16=arg[2]? arg[2][2] : 0;
  a23=cos(a3);
  a15=(a23*a15);
  a15=(a16*a15);
  a17=(a17-a15);
  a15=-2.5000000000000000e-01;
  a19=(a15*a19);
  a17=(a17-a19);
  if (res[0]!=0) res[0][2]=a17;
  a17=cos(a5);
  a19=(a18*a17);
  a24=sin(a5);
  a25=(a8*a24);
  a26=(a12*a25);
  a19=(a19+a26);
  a19=(a7*a19);
  a17=(a21*a17);
  a25=(a22*a25);
  a17=(a17-a25);
  a25=(a20*a17);
  a19=(a19+a25);
  a23=(a23*a24);
  a23=(a16*a23);
  a19=(a19-a23);
  a17=(a15*a17);
  a19=(a19+a17);
  if (res[0]!=0) res[0][3]=a19;
  a19=cos(a9);
  a17=arg[2]? arg[2][3] : 0;
  a19=(a19*a17);
  a23=sin(a9);
  a24=arg[2]? arg[2][4] : 0;
  a23=(a23*a24);
  a19=(a19-a23);
  a23=cos(a1);
  a25=sin(a3);
  a26=cos(a5);
  a27=(a25*a26);
  a28=(a23*a27);
  a29=sin(a1);
  a30=sin(a5);
  a31=(a29*a30);
  a28=(a28-a31);
  a28=(a19*a28);
  a31=sin(a9);
  a31=(a31*a17);
  a32=cos(a9);
  a32=(a32*a24);
  a31=(a31+a32);
  a32=cos(a1);
  a30=(a32*a30);
  a33=sin(a1);
  a27=(a33*a27);
  a30=(a30+a27);
  a27=(a31*a30);
  a28=(a28-a27);
  a27=arg[2]? arg[2][5] : 0;
  a34=cos(a3);
  a26=(a34*a26);
  a26=(a27*a26);
  a28=(a28-a26);
  a30=(a15*a30);
  a28=(a28-a30);
  if (res[0]!=0) res[0][4]=a28;
  a28=cos(a5);
  a30=(a29*a28);
  a26=sin(a5);
  a35=(a25*a26);
  a36=(a23*a35);
  a30=(a30+a36);
  a30=(a19*a30);
  a28=(a32*a28);
  a35=(a33*a35);
  a28=(a28-a35);
  a35=(a31*a28);
  a30=(a30+a35);
  a34=(a34*a26);
  a34=(a27*a34);
  a30=(a30-a34);
  a28=(a15*a28);
  a30=(a30+a28);
  if (res[0]!=0) res[0][5]=a30;
  a30=arg[0]? arg[0][5] : 0;
  a28=cos(a30);
  a34=arg[0]? arg[0][6] : 0;
  a26=cos(a34);
  a35=(a28*a26);
  a36=arg[3]? arg[3][0] : 0;
  a35=(a35*a36);
  a37=sin(a34);
  a38=(a28*a37);
  a39=arg[3]? arg[3][1] : 0;
  a38=(a38*a39);
  a35=(a35-a38);
  a38=sin(a30);
  a40=arg[3]? arg[3][2] : 0;
  a38=(a38*a40);
  a35=(a35+a38);
  a38=cos(a9);
  a41=cos(a1);
  a42=sin(a3);
  a43=cos(a5);
  a44=(a42*a43);
  a45=(a41*a44);
  a46=sin(a1);
  a47=sin(a5);
  a48=(a46*a47);
  a45=(a45-a48);
  a48=(a38*a45);
  a49=sin(a9);
  a50=cos(a1);
  a47=(a50*a47);
  a51=sin(a1);
  a44=(a51*a44);
  a47=(a47+a44);
  a44=(a49*a47);
  a48=(a48-a44);
  a48=(a35*a48);
  a44=arg[0]? arg[0][4] : 0;
  a52=sin(a44);
  a53=sin(a30);
  a54=(a52*a53);
  a55=(a54*a26);
  a56=cos(a44);
  a57=sin(a34);
  a58=(a56*a57);
  a55=(a55+a58);
  a55=(a55*a36);
  a58=cos(a34);
  a59=(a56*a58);
  a60=(a54*a37);
  a59=(a59-a60);
  a59=(a59*a39);
  a55=(a55+a59);
  a59=cos(a30);
  a60=(a52*a59);
  a60=(a60*a40);
  a55=(a55-a60);
  a60=cos(a9);
  a61=(a60*a47);
  a62=sin(a9);
  a63=(a62*a45);
  a61=(a61+a63);
  a61=(a55*a61);
  a48=(a48-a61);
  a61=sin(a44);
  a63=(a61*a57);
  a64=cos(a44);
  a65=(a64*a53);
  a66=(a65*a26);
  a63=(a63-a66);
  a63=(a63*a36);
  a66=(a65*a37);
  a67=(a61*a58);
  a66=(a66+a67);
  a66=(a66*a39);
  a63=(a63+a66);
  a66=(a64*a59);
  a66=(a66*a40);
  a63=(a63+a66);
  a66=cos(a3);
  a43=(a66*a43);
  a43=(a63*a43);
  a48=(a48-a43);
  a43=(a15*a60);
  a67=(a43*a47);
  a68=(a15*a62);
  a45=(a68*a45);
  a67=(a67+a45);
  a47=(a15*a47);
  a67=(a67+a47);
  a48=(a48-a67);
  if (res[0]!=0) res[0][6]=a48;
  a48=cos(a5);
  a67=(a46*a48);
  a47=sin(a5);
  a45=(a42*a47);
  a69=(a41*a45);
  a67=(a67+a69);
  a69=(a38*a67);
  a48=(a50*a48);
  a45=(a51*a45);
  a48=(a48-a45);
  a45=(a49*a48);
  a69=(a69+a45);
  a69=(a35*a69);
  a45=(a60*a48);
  a70=(a62*a67);
  a45=(a45-a70);
  a45=(a55*a45);
  a69=(a69+a45);
  a47=(a66*a47);
  a47=(a63*a47);
  a69=(a69-a47);
  a47=(a43*a48);
  a67=(a68*a67);
  a47=(a47-a67);
  a48=(a15*a48);
  a47=(a47+a48);
  a69=(a69+a47);
  if (res[0]!=0) res[0][7]=a69;
  a69=cos(a30);
  a47=cos(a34);
  a48=(a69*a47);
  a67=arg[3]? arg[3][3] : 0;
  a48=(a48*a67);
  a45=sin(a34);
  a70=(a69*a45);
  a71=arg[3]? arg[3][4] : 0;
  a70=(a70*a71);
  a48=(a48-a70);
  a70=sin(a30);
  a72=arg[3]? arg[3][5] : 0;
  a70=(a70*a72);
  a48=(a48+a70);
  a70=cos(a9);
  a73=cos(a1);
  a74=sin(a3);
  a75=cos(a5);
  a76=(a74*a75);
  a77=(a73*a76);
  a78=sin(a1);
  a79=sin(a5);
  a80=(a78*a79);
  a77=(a77-a80);
  a80=(a70*a77);
  a81=sin(a9);
  a82=cos(a1);
  a79=(a82*a79);
  a83=sin(a1);
  a76=(a83*a76);
  a79=(a79+a76);
  a76=(a81*a79);
  a80=(a80-a76);
  a80=(a48*a80);
  a76=sin(a44);
  a84=sin(a30);
  a85=(a76*a84);
  a86=(a85*a47);
  a87=cos(a44);
  a88=sin(a34);
  a89=(a87*a88);
  a86=(a86+a89);
  a86=(a86*a67);
  a89=cos(a34);
  a90=(a87*a89);
  a91=(a85*a45);
  a90=(a90-a91);
  a90=(a90*a71);
  a86=(a86+a90);
  a90=cos(a30);
  a91=(a76*a90);
  a91=(a91*a72);
  a86=(a86-a91);
  a91=cos(a9);
  a92=(a91*a79);
  a93=sin(a9);
  a94=(a93*a77);
  a92=(a92+a94);
  a92=(a86*a92);
  a80=(a80-a92);
  a92=sin(a44);
  a94=(a92*a88);
  a95=cos(a44);
  a96=(a95*a84);
  a97=(a96*a47);
  a94=(a94-a97);
  a94=(a94*a67);
  a97=(a96*a45);
  a98=(a92*a89);
  a97=(a97+a98);
  a97=(a97*a71);
  a94=(a94+a97);
  a97=(a95*a90);
  a97=(a97*a72);
  a94=(a94+a97);
  a97=cos(a3);
  a75=(a97*a75);
  a75=(a94*a75);
  a80=(a80-a75);
  a75=(a15*a91);
  a98=(a75*a79);
  a99=(a15*a93);
  a77=(a99*a77);
  a98=(a98+a77);
  a79=(a15*a79);
  a98=(a98+a79);
  a80=(a80-a98);
  if (res[0]!=0) res[0][8]=a80;
  a80=cos(a5);
  a98=(a78*a80);
  a79=sin(a5);
  a77=(a74*a79);
  a100=(a73*a77);
  a98=(a98+a100);
  a100=(a70*a98);
  a80=(a82*a80);
  a77=(a83*a77);
  a80=(a80-a77);
  a77=(a81*a80);
  a100=(a100+a77);
  a100=(a48*a100);
  a77=(a91*a80);
  a101=(a93*a98);
  a77=(a77-a101);
  a77=(a86*a77);
  a100=(a100+a77);
  a79=(a97*a79);
  a79=(a94*a79);
  a100=(a100-a79);
  a79=(a75*a80);
  a98=(a99*a98);
  a79=(a79-a98);
  a80=(a15*a80);
  a79=(a79+a80);
  a100=(a100+a79);
  if (res[0]!=0) res[0][9]=a100;
  a100=sin(a3);
  a79=(a13*a100);
  a79=(a11*a79);
  a100=(a2*a100);
  a100=(a0*a100);
  a79=(a79-a100);
  a100=cos(a3);
  a100=(a10*a100);
  a79=(a79+a100);
  if (res[0]!=0) res[0][10]=a79;
  a79=sin(a5);
  a100=cos(a3);
  a80=(a79*a100);
  a98=(a2*a80);
  a98=(a0*a98);
  a80=(a13*a80);
  a80=(a11*a80);
  a98=(a98-a80);
  a80=sin(a3);
  a77=(a79*a80);
  a77=(a10*a77);
  a98=(a98+a77);
  if (res[0]!=0) res[0][11]=a98;
  a98=cos(a5);
  a100=(a98*a100);
  a13=(a13*a100);
  a13=(a11*a13);
  a2=(a2*a100);
  a2=(a0*a2);
  a13=(a13-a2);
  a80=(a98*a80);
  a10=(a10*a80);
  a13=(a13-a10);
  if (res[0]!=0) res[0][12]=a13;
  a13=sin(a3);
  a10=(a22*a13);
  a80=(a20*a10);
  a13=(a12*a13);
  a13=(a7*a13);
  a80=(a80-a13);
  a13=cos(a3);
  a13=(a16*a13);
  a80=(a80+a13);
  a10=(a15*a10);
  a80=(a80+a10);
  if (res[0]!=0) res[0][13]=a80;
  a80=sin(a5);
  a10=cos(a3);
  a13=(a80*a10);
  a2=(a12*a13);
  a2=(a7*a2);
  a13=(a22*a13);
  a100=(a20*a13);
  a2=(a2-a100);
  a100=sin(a3);
  a77=(a80*a100);
  a77=(a16*a77);
  a2=(a2+a77);
  a13=(a15*a13);
  a2=(a2-a13);
  if (res[0]!=0) res[0][14]=a2;
  a2=cos(a5);
  a10=(a2*a10);
  a13=(a22*a10);
  a77=(a20*a13);
  a10=(a12*a10);
  a10=(a7*a10);
  a77=(a77-a10);
  a100=(a2*a100);
  a16=(a16*a100);
  a77=(a77-a16);
  a13=(a15*a13);
  a77=(a77+a13);
  if (res[0]!=0) res[0][15]=a77;
  a77=sin(a3);
  a13=(a33*a77);
  a16=(a31*a13);
  a77=(a23*a77);
  a77=(a19*a77);
  a16=(a16-a77);
  a77=cos(a3);
  a77=(a27*a77);
  a16=(a16+a77);
  a13=(a15*a13);
  a16=(a16+a13);
  if (res[0]!=0) res[0][16]=a16;
  a16=sin(a5);
  a13=cos(a3);
  a77=(a16*a13);
  a100=(a23*a77);
  a100=(a19*a100);
  a77=(a33*a77);
  a10=(a31*a77);
  a100=(a100-a10);
  a10=sin(a3);
  a101=(a16*a10);
  a101=(a27*a101);
  a100=(a100+a101);
  a77=(a15*a77);
  a100=(a100-a77);
  if (res[0]!=0) res[0][17]=a100;
  a100=cos(a5);
  a13=(a100*a13);
  a77=(a33*a13);
  a101=(a31*a77);
  a13=(a23*a13);
  a13=(a19*a13);
  a101=(a101-a13);
  a10=(a100*a10);
  a27=(a27*a10);
  a101=(a101-a27);
  a77=(a15*a77);
  a101=(a101+a77);
  if (res[0]!=0) res[0][18]=a101;
  a101=sin(a3);
  a77=(a51*a101);
  a27=(a49*a77);
  a101=(a41*a101);
  a10=(a38*a101);
  a27=(a27-a10);
  a27=(a35*a27);
  a10=(a62*a101);
  a13=(a60*a77);
  a10=(a10+a13);
  a10=(a55*a10);
  a27=(a27+a10);
  a10=cos(a3);
  a10=(a63*a10);
  a27=(a27+a10);
  a101=(a68*a101);
  a10=(a43*a77);
  a101=(a101+a10);
  a77=(a15*a77);
  a101=(a101+a77);
  a27=(a27+a101);
  if (res[0]!=0) res[0][19]=a27;
  a27=sin(a5);
  a101=cos(a3);
  a77=(a27*a101);
  a10=(a41*a77);
  a13=(a38*a10);
  a77=(a51*a77);
  a102=(a49*a77);
  a13=(a13-a102);
  a13=(a35*a13);
  a102=(a60*a77);
  a103=(a62*a10);
  a102=(a102+a103);
  a102=(a55*a102);
  a13=(a13-a102);
  a102=sin(a3);
  a103=(a27*a102);
  a103=(a63*a103);
  a13=(a13+a103);
  a103=(a43*a77);
  a10=(a68*a10);
  a103=(a103+a10);
  a77=(a15*a77);
  a103=(a103+a77);
  a13=(a13-a103);
  if (res[0]!=0) res[0][20]=a13;
  a13=cos(a5);
  a101=(a13*a101);
  a103=(a51*a101);
  a77=(a49*a103);
  a101=(a41*a101);
  a10=(a38*a101);
  a77=(a77-a10);
  a77=(a35*a77);
  a10=(a60*a103);
  a104=(a62*a101);
  a10=(a10+a104);
  a10=(a55*a10);
  a77=(a77+a10);
  a102=(a13*a102);
  a63=(a63*a102);
  a77=(a77-a63);
  a63=(a43*a103);
  a101=(a68*a101);
  a63=(a63+a101);
  a103=(a15*a103);
  a63=(a63+a103);
  a77=(a77+a63);
  if (res[0]!=0) res[0][21]=a77;
  a77=sin(a3);
  a63=(a83*a77);
  a103=(a81*a63);
  a77=(a73*a77);
  a101=(a70*a77);
  a103=(a103-a101);
  a103=(a48*a103);
  a101=(a93*a77);
  a102=(a91*a63);
  a101=(a101+a102);
  a101=(a86*a101);
  a103=(a103+a101);
  a101=cos(a3);
  a101=(a94*a101);
  a103=(a103+a101);
  a77=(a99*a77);
  a101=(a75*a63);
  a77=(a77+a101);
  a63=(a15*a63);
  a77=(a77+a63);
  a103=(a103+a77);
  if (res[0]!=0) res[0][22]=a103;
  a103=sin(a5);
  a77=cos(a3);
  a63=(a103*a77);
  a101=(a73*a63);
  a102=(a70*a101);
  a63=(a83*a63);
  a10=(a81*a63);
  a102=(a102-a10);
  a102=(a48*a102);
  a10=(a91*a63);
  a104=(a93*a101);
  a10=(a10+a104);
  a10=(a86*a10);
  a102=(a102-a10);
  a10=sin(a3);
  a104=(a103*a10);
  a104=(a94*a104);
  a102=(a102+a104);
  a104=(a75*a63);
  a101=(a99*a101);
  a104=(a104+a101);
  a63=(a15*a63);
  a104=(a104+a63);
  a102=(a102-a104);
  if (res[0]!=0) res[0][23]=a102;
  a102=cos(a5);
  a77=(a102*a77);
  a104=(a83*a77);
  a63=(a81*a104);
  a77=(a73*a77);
  a101=(a70*a77);
  a63=(a63-a101);
  a63=(a48*a63);
  a101=(a91*a104);
  a105=(a93*a77);
  a101=(a101+a105);
  a101=(a86*a101);
  a63=(a63+a101);
  a10=(a102*a10);
  a94=(a94*a10);
  a63=(a63-a94);
  a94=(a75*a104);
  a77=(a99*a77);
  a94=(a94+a77);
  a104=(a15*a104);
  a94=(a94+a104);
  a63=(a63+a94);
  if (res[0]!=0) res[0][24]=a63;
  a63=cos(a3);
  a94=sin(a1);
  a104=(a63*a94);
  a104=(a0*a104);
  a77=cos(a1);
  a63=(a63*a77);
  a63=(a11*a63);
  a104=(a104+a63);
  a104=(-a104);
  if (res[0]!=0) res[0][25]=a104;
  a104=cos(a5);
  a63=cos(a1);
  a10=(a104*a63);
  a79=(a79*a4);
  a101=(a79*a94);
  a10=(a10-a101);
  a10=(a0*a10);
  a101=sin(a1);
  a104=(a104*a101);
  a79=(a79*a77);
  a104=(a104+a79);
  a104=(a11*a104);
  a10=(a10-a104);
  if (res[0]!=0) res[0][26]=a10;
  a10=sin(a5);
  a63=(a10*a63);
  a98=(a98*a4);
  a94=(a98*a94);
  a63=(a63+a94);
  a0=(a0*a63);
  a98=(a98*a77);
  a10=(a10*a101);
  a98=(a98-a10);
  a11=(a11*a98);
  a0=(a0+a11);
  if (res[0]!=0) res[0][27]=a0;
  a0=cos(a3);
  a11=sin(a1);
  a98=(a0*a11);
  a98=(a7*a98);
  a10=cos(a1);
  a101=(a0*a10);
  a77=(a20*a101);
  a98=(a98+a77);
  a101=(a15*a101);
  a98=(a98+a101);
  a98=(-a98);
  if (res[0]!=0) res[0][28]=a98;
  a98=cos(a5);
  a101=cos(a1);
  a77=(a98*a101);
  a80=(a80*a8);
  a63=(a80*a11);
  a77=(a77-a63);
  a77=(a7*a77);
  a63=sin(a1);
  a94=(a98*a63);
  a4=(a80*a10);
  a94=(a94+a4);
  a4=(a20*a94);
  a77=(a77-a4);
  a94=(a15*a94);
  a77=(a77-a94);
  if (res[0]!=0) res[0][29]=a77;
  a77=sin(a5);
  a101=(a77*a101);
  a2=(a2*a8);
  a11=(a2*a11);
  a101=(a101+a11);
  a7=(a7*a101);
  a10=(a2*a10);
  a63=(a77*a63);
  a10=(a10-a63);
  a20=(a20*a10);
  a7=(a7+a20);
  a10=(a15*a10);
  a7=(a7+a10);
  if (res[0]!=0) res[0][30]=a7;
  a7=cos(a3);
  a10=sin(a1);
  a20=(a7*a10);
  a20=(a19*a20);
  a63=cos(a1);
  a101=(a7*a63);
  a11=(a31*a101);
  a20=(a20+a11);
  a101=(a15*a101);
  a20=(a20+a101);
  a20=(-a20);
  if (res[0]!=0) res[0][31]=a20;
  a20=cos(a5);
  a101=cos(a1);
  a11=(a20*a101);
  a16=(a16*a25);
  a8=(a16*a10);
  a11=(a11-a8);
  a11=(a19*a11);
  a8=sin(a1);
  a94=(a20*a8);
  a4=(a16*a63);
  a94=(a94+a4);
  a4=(a31*a94);
  a11=(a11-a4);
  a94=(a15*a94);
  a11=(a11-a94);
  if (res[0]!=0) res[0][32]=a11;
  a11=sin(a5);
  a101=(a11*a101);
  a100=(a100*a25);
  a10=(a100*a10);
  a101=(a101+a10);
  a19=(a19*a101);
  a63=(a100*a63);
  a8=(a11*a8);
  a63=(a63-a8);
  a31=(a31*a63);
  a19=(a19+a31);
  a63=(a15*a63);
  a19=(a19+a63);
  if (res[0]!=0) res[0][33]=a19;
  a19=cos(a3);
  a63=sin(a1);
  a31=(a19*a63);
  a8=(a38*a31);
  a101=cos(a1);
  a10=(a19*a101);
  a25=(a49*a10);
  a8=(a8+a25);
  a8=(a35*a8);
  a25=(a60*a10);
  a94=(a62*a31);
  a25=(a25-a94);
  a25=(a55*a25);
  a8=(a8+a25);
  a25=(a43*a10);
  a31=(a68*a31);
  a25=(a25-a31);
  a10=(a15*a10);
  a25=(a25+a10);
  a8=(a8+a25);
  a8=(-a8);
  if (res[0]!=0) res[0][34]=a8;
  a8=cos(a5);
  a25=cos(a1);
  a10=(a8*a25);
  a31=(a27*a42);
  a94=(a31*a63);
  a10=(a10-a94);
  a94=(a38*a10);
  a4=sin(a1);
  a104=(a8*a4);
  a79=(a31*a101);
  a104=(a104+a79);
  a79=(a49*a104);
  a94=(a94-a79);
  a94=(a35*a94);
  a79=(a60*a104);
  a105=(a62*a10);
  a79=(a79+a105);
  a79=(a55*a79);
  a94=(a94-a79);
  a79=(a43*a104);
  a10=(a68*a10);
  a79=(a79+a10);
  a104=(a15*a104);
  a79=(a79+a104);
  a94=(a94-a79);
  if (res[0]!=0) res[0][35]=a94;
  a94=sin(a5);
  a25=(a94*a25);
  a42=(a13*a42);
  a63=(a42*a63);
  a25=(a25+a63);
  a63=(a38*a25);
  a101=(a42*a101);
  a4=(a94*a4);
  a101=(a101-a4);
  a4=(a49*a101);
  a63=(a63+a4);
  a63=(a35*a63);
  a4=(a60*a101);
  a79=(a62*a25);
  a4=(a4-a79);
  a4=(a55*a4);
  a63=(a63+a4);
  a43=(a43*a101);
  a68=(a68*a25);
  a43=(a43-a68);
  a101=(a15*a101);
  a43=(a43+a101);
  a63=(a63+a43);
  if (res[0]!=0) res[0][36]=a63;
  a63=cos(a3);
  a43=sin(a1);
  a101=(a63*a43);
  a68=(a70*a101);
  a25=cos(a1);
  a4=(a63*a25);
  a79=(a81*a4);
  a68=(a68+a79);
  a68=(a48*a68);
  a79=(a91*a4);
  a104=(a93*a101);
  a79=(a79-a104);
  a79=(a86*a79);
  a68=(a68+a79);
  a79=(a75*a4);
  a101=(a99*a101);
  a79=(a79-a101);
  a4=(a15*a4);
  a79=(a79+a4);
  a68=(a68+a79);
  a68=(-a68);
  if (res[0]!=0) res[0][37]=a68;
  a68=cos(a5);
  a79=cos(a1);
  a4=(a68*a79);
  a101=(a103*a74);
  a104=(a101*a43);
  a4=(a4-a104);
  a104=(a70*a4);
  a1=sin(a1);
  a10=(a68*a1);
  a105=(a101*a25);
  a10=(a10+a105);
  a105=(a81*a10);
  a104=(a104-a105);
  a104=(a48*a104);
  a105=(a91*a10);
  a106=(a93*a4);
  a105=(a105+a106);
  a105=(a86*a105);
  a104=(a104-a105);
  a105=(a75*a10);
  a4=(a99*a4);
  a105=(a105+a4);
  a10=(a15*a10);
  a105=(a105+a10);
  a104=(a104-a105);
  if (res[0]!=0) res[0][38]=a104;
  a5=sin(a5);
  a79=(a5*a79);
  a74=(a102*a74);
  a43=(a74*a43);
  a79=(a79+a43);
  a43=(a70*a79);
  a25=(a74*a25);
  a1=(a5*a1);
  a25=(a25-a1);
  a1=(a81*a25);
  a43=(a43+a1);
  a43=(a48*a43);
  a1=(a91*a25);
  a104=(a93*a79);
  a1=(a1-a104);
  a1=(a86*a1);
  a43=(a43+a1);
  a75=(a75*a25);
  a99=(a99*a79);
  a75=(a75-a99);
  a25=(a15*a25);
  a75=(a75+a25);
  a43=(a43+a75);
  if (res[0]!=0) res[0][39]=a43;
  a43=(a0*a12);
  a75=sin(a9);
  a75=(a6*a75);
  a25=cos(a9);
  a25=(a14*a25);
  a75=(a75+a25);
  a43=(a43*a75);
  a0=(a0*a22);
  a25=cos(a9);
  a6=(a6*a25);
  a25=sin(a9);
  a14=(a14*a25);
  a6=(a6-a14);
  a0=(a0*a6);
  a43=(a43+a0);
  a43=(-a43);
  if (res[0]!=0) res[0][40]=a43;
  a43=(a98*a21);
  a0=(a80*a22);
  a43=(a43-a0);
  a43=(a43*a6);
  a80=(a80*a12);
  a98=(a98*a18);
  a80=(a80+a98);
  a80=(a80*a75);
  a43=(a43-a80);
  if (res[0]!=0) res[0][41]=a43;
  a22=(a2*a22);
  a21=(a77*a21);
  a22=(a22+a21);
  a22=(a22*a6);
  a77=(a77*a18);
  a2=(a2*a12);
  a77=(a77-a2);
  a77=(a77*a75);
  a22=(a22-a77);
  if (res[0]!=0) res[0][42]=a22;
  a22=(a7*a23);
  a77=sin(a9);
  a77=(a17*a77);
  a75=cos(a9);
  a75=(a24*a75);
  a77=(a77+a75);
  a22=(a22*a77);
  a7=(a7*a33);
  a75=cos(a9);
  a17=(a17*a75);
  a75=sin(a9);
  a24=(a24*a75);
  a17=(a17-a24);
  a7=(a7*a17);
  a22=(a22+a7);
  a22=(-a22);
  if (res[0]!=0) res[0][43]=a22;
  a22=(a20*a32);
  a7=(a16*a33);
  a22=(a22-a7);
  a22=(a22*a17);
  a16=(a16*a23);
  a20=(a20*a29);
  a16=(a16+a20);
  a16=(a16*a77);
  a22=(a22-a16);
  if (res[0]!=0) res[0][44]=a22;
  a33=(a100*a33);
  a32=(a11*a32);
  a33=(a33+a32);
  a33=(a33*a17);
  a11=(a11*a29);
  a100=(a100*a23);
  a11=(a11-a100);
  a11=(a11*a77);
  a33=(a33-a11);
  if (res[0]!=0) res[0][45]=a33;
  a33=(a19*a41);
  a11=sin(a9);
  a77=(a33*a11);
  a19=(a19*a51);
  a100=cos(a9);
  a23=(a19*a100);
  a77=(a77+a23);
  a77=(a35*a77);
  a23=cos(a9);
  a29=(a33*a23);
  a17=sin(a9);
  a32=(a19*a17);
  a29=(a29-a32);
  a29=(a55*a29);
  a77=(a77+a29);
  a29=(a15*a23);
  a32=(a33*a29);
  a22=(a15*a17);
  a16=(a19*a22);
  a32=(a32-a16);
  a77=(a77+a32);
  a77=(-a77);
  if (res[0]!=0) res[0][46]=a77;
  a77=(a8*a50);
  a32=(a31*a51);
  a77=(a77-a32);
  a32=(a77*a100);
  a31=(a31*a41);
  a8=(a8*a46);
  a31=(a31+a8);
  a8=(a31*a11);
  a32=(a32-a8);
  a32=(a35*a32);
  a8=(a77*a17);
  a16=(a31*a23);
  a8=(a8+a16);
  a8=(a55*a8);
  a32=(a32-a8);
  a8=(a77*a22);
  a16=(a31*a29);
  a8=(a8+a16);
  a32=(a32-a8);
  if (res[0]!=0) res[0][47]=a32;
  a51=(a42*a51);
  a50=(a94*a50);
  a51=(a51+a50);
  a100=(a51*a100);
  a94=(a94*a46);
  a42=(a42*a41);
  a94=(a94-a42);
  a11=(a94*a11);
  a100=(a100-a11);
  a35=(a35*a100);
  a17=(a51*a17);
  a23=(a94*a23);
  a17=(a17+a23);
  a55=(a55*a17);
  a35=(a35-a55);
  a22=(a51*a22);
  a29=(a94*a29);
  a22=(a22+a29);
  a35=(a35-a22);
  if (res[0]!=0) res[0][48]=a35;
  a35=(a63*a73);
  a22=sin(a9);
  a29=(a35*a22);
  a63=(a63*a83);
  a55=cos(a9);
  a17=(a63*a55);
  a29=(a29+a17);
  a29=(a48*a29);
  a17=cos(a9);
  a23=(a35*a17);
  a9=sin(a9);
  a100=(a63*a9);
  a23=(a23-a100);
  a23=(a86*a23);
  a29=(a29+a23);
  a23=(a15*a17);
  a100=(a35*a23);
  a15=(a15*a9);
  a11=(a63*a15);
  a100=(a100-a11);
  a29=(a29+a100);
  a29=(-a29);
  if (res[0]!=0) res[0][49]=a29;
  a29=(a68*a82);
  a100=(a101*a83);
  a29=(a29-a100);
  a100=(a29*a55);
  a101=(a101*a73);
  a68=(a68*a78);
  a101=(a101+a68);
  a68=(a101*a22);
  a100=(a100-a68);
  a100=(a48*a100);
  a68=(a29*a9);
  a11=(a101*a17);
  a68=(a68+a11);
  a68=(a86*a68);
  a100=(a100-a68);
  a68=(a29*a15);
  a11=(a101*a23);
  a68=(a68+a11);
  a100=(a100-a68);
  if (res[0]!=0) res[0][50]=a100;
  a83=(a74*a83);
  a82=(a5*a82);
  a83=(a83+a82);
  a55=(a83*a55);
  a5=(a5*a78);
  a74=(a74*a73);
  a5=(a5-a74);
  a22=(a5*a22);
  a55=(a55-a22);
  a48=(a48*a55);
  a9=(a83*a9);
  a17=(a5*a17);
  a9=(a9+a17);
  a86=(a86*a9);
  a48=(a48-a86);
  a15=(a83*a15);
  a23=(a5*a23);
  a15=(a15+a23);
  a48=(a48-a15);
  if (res[0]!=0) res[0][51]=a48;
  a48=sin(a3);
  a15=cos(a44);
  a23=(a57*a15);
  a86=sin(a44);
  a9=(a53*a86);
  a17=(a26*a9);
  a23=(a23+a17);
  a23=(a36*a23);
  a15=(a58*a15);
  a9=(a37*a9);
  a15=(a15-a9);
  a15=(a39*a15);
  a23=(a23+a15);
  a86=(a59*a86);
  a86=(a40*a86);
  a23=(a23-a86);
  a86=(a48*a23);
  a15=(a33*a62);
  a9=(a19*a60);
  a15=(a15+a9);
  a9=cos(a44);
  a53=(a53*a9);
  a17=(a26*a53);
  a55=sin(a44);
  a57=(a57*a55);
  a17=(a17-a57);
  a17=(a36*a17);
  a58=(a58*a55);
  a53=(a37*a53);
  a58=(a58+a53);
  a58=(a39*a58);
  a17=(a17-a58);
  a59=(a59*a9);
  a59=(a40*a59);
  a17=(a17-a59);
  a59=(a15*a17);
  a86=(a86-a59);
  if (res[0]!=0) res[0][52]=a86;
  a86=(a77*a60);
  a59=(a31*a62);
  a86=(a86-a59);
  a59=(a86*a17);
  a27=(a27*a66);
  a9=(a27*a23);
  a59=(a59-a9);
  if (res[0]!=0) res[0][53]=a59;
  a60=(a51*a60);
  a62=(a94*a62);
  a60=(a60-a62);
  a17=(a60*a17);
  a13=(a13*a66);
  a23=(a13*a23);
  a17=(a17+a23);
  if (res[0]!=0) res[0][54]=a17;
  a3=sin(a3);
  a17=cos(a44);
  a23=(a88*a17);
  a66=sin(a44);
  a62=(a84*a66);
  a59=(a47*a62);
  a23=(a23+a59);
  a23=(a67*a23);
  a17=(a89*a17);
  a62=(a45*a62);
  a17=(a17-a62);
  a17=(a71*a17);
  a23=(a23+a17);
  a66=(a90*a66);
  a66=(a72*a66);
  a23=(a23-a66);
  a66=(a3*a23);
  a17=(a35*a93);
  a62=(a63*a91);
  a17=(a17+a62);
  a62=cos(a44);
  a84=(a84*a62);
  a59=(a47*a84);
  a44=sin(a44);
  a88=(a88*a44);
  a59=(a59-a88);
  a59=(a67*a59);
  a89=(a89*a44);
  a84=(a45*a84);
  a89=(a89+a84);
  a89=(a71*a89);
  a59=(a59-a89);
  a90=(a90*a62);
  a90=(a72*a90);
  a59=(a59-a90);
  a90=(a17*a59);
  a66=(a66-a90);
  if (res[0]!=0) res[0][55]=a66;
  a66=(a29*a91);
  a90=(a101*a93);
  a66=(a66-a90);
  a90=(a66*a59);
  a103=(a103*a97);
  a62=(a103*a23);
  a90=(a90-a62);
  if (res[0]!=0) res[0][56]=a90;
  a91=(a83*a91);
  a93=(a5*a93);
  a91=(a91-a93);
  a59=(a91*a59);
  a102=(a102*a97);
  a23=(a102*a23);
  a59=(a59+a23);
  if (res[0]!=0) res[0][57]=a59;
  a33=(a33*a38);
  a19=(a19*a49);
  a33=(a33-a19);
  a19=sin(a30);
  a59=(a37*a19);
  a59=(a39*a59);
  a19=(a26*a19);
  a19=(a36*a19);
  a59=(a59-a19);
  a19=cos(a30);
  a19=(a40*a19);
  a59=(a59+a19);
  a19=(a33*a59);
  a23=cos(a30);
  a97=(a52*a23);
  a93=(a26*a97);
  a93=(a36*a93);
  a97=(a37*a97);
  a97=(a39*a97);
  a93=(a93-a97);
  a97=sin(a30);
  a52=(a52*a97);
  a52=(a40*a52);
  a93=(a93+a52);
  a52=(a15*a93);
  a19=(a19-a52);
  a23=(a64*a23);
  a37=(a37*a23);
  a37=(a39*a37);
  a26=(a26*a23);
  a26=(a36*a26);
  a37=(a37-a26);
  a64=(a64*a97);
  a40=(a40*a64);
  a37=(a37-a40);
  a40=(a48*a37);
  a19=(a19+a40);
  if (res[0]!=0) res[0][58]=a19;
  a31=(a31*a38);
  a77=(a77*a49);
  a31=(a31+a77);
  a77=(a31*a59);
  a19=(a86*a93);
  a77=(a77+a19);
  a19=(a27*a37);
  a77=(a77-a19);
  if (res[0]!=0) res[0][59]=a77;
  a94=(a94*a38);
  a51=(a51*a49);
  a94=(a94+a51);
  a59=(a94*a59);
  a93=(a60*a93);
  a59=(a59+a93);
  a37=(a13*a37);
  a59=(a59+a37);
  if (res[0]!=0) res[0][60]=a59;
  a35=(a35*a70);
  a63=(a63*a81);
  a35=(a35-a63);
  a63=sin(a30);
  a59=(a45*a63);
  a59=(a71*a59);
  a63=(a47*a63);
  a63=(a67*a63);
  a59=(a59-a63);
  a63=cos(a30);
  a63=(a72*a63);
  a59=(a59+a63);
  a63=(a35*a59);
  a37=cos(a30);
  a93=(a76*a37);
  a51=(a47*a93);
  a51=(a67*a51);
  a93=(a45*a93);
  a93=(a71*a93);
  a51=(a51-a93);
  a30=sin(a30);
  a76=(a76*a30);
  a76=(a72*a76);
  a51=(a51+a76);
  a76=(a17*a51);
  a63=(a63-a76);
  a37=(a95*a37);
  a45=(a45*a37);
  a45=(a71*a45);
  a47=(a47*a37);
  a47=(a67*a47);
  a45=(a45-a47);
  a95=(a95*a30);
  a72=(a72*a95);
  a45=(a45-a72);
  a72=(a3*a45);
  a63=(a63+a72);
  if (res[0]!=0) res[0][61]=a63;
  a101=(a101*a70);
  a29=(a29*a81);
  a101=(a101+a29);
  a29=(a101*a59);
  a63=(a66*a51);
  a29=(a29+a63);
  a63=(a103*a45);
  a29=(a29-a63);
  if (res[0]!=0) res[0][62]=a29;
  a5=(a5*a70);
  a83=(a83*a81);
  a5=(a5+a83);
  a59=(a5*a59);
  a51=(a91*a51);
  a59=(a59+a51);
  a45=(a102*a45);
  a59=(a59+a45);
  if (res[0]!=0) res[0][63]=a59;
  a59=cos(a34);
  a45=(a61*a59);
  a51=sin(a34);
  a83=(a65*a51);
  a45=(a45+a83);
  a45=(a36*a45);
  a83=cos(a34);
  a65=(a65*a83);
  a81=sin(a34);
  a61=(a61*a81);
  a65=(a65-a61);
  a65=(a39*a65);
  a45=(a45+a65);
  a48=(a48*a45);
  a65=(a28*a51);
  a65=(a36*a65);
  a28=(a28*a83);
  a28=(a39*a28);
  a65=(a65+a28);
  a33=(a33*a65);
  a59=(a56*a59);
  a51=(a54*a51);
  a59=(a59-a51);
  a36=(a36*a59);
  a56=(a56*a81);
  a54=(a54*a83);
  a56=(a56+a54);
  a39=(a39*a56);
  a36=(a36-a39);
  a15=(a15*a36);
  a33=(a33+a15);
  a48=(a48-a33);
  if (res[0]!=0) res[0][64]=a48;
  a86=(a86*a36);
  a31=(a31*a65);
  a86=(a86-a31);
  a27=(a27*a45);
  a86=(a86-a27);
  if (res[0]!=0) res[0][65]=a86;
  a60=(a60*a36);
  a94=(a94*a65);
  a60=(a60-a94);
  a13=(a13*a45);
  a60=(a60+a13);
  if (res[0]!=0) res[0][66]=a60;
  a60=cos(a34);
  a13=(a92*a60);
  a45=sin(a34);
  a94=(a96*a45);
  a13=(a13+a94);
  a13=(a67*a13);
  a94=cos(a34);
  a96=(a96*a94);
  a34=sin(a34);
  a92=(a92*a34);
  a96=(a96-a92);
  a96=(a71*a96);
  a13=(a13+a96);
  a3=(a3*a13);
  a96=(a69*a45);
  a96=(a67*a96);
  a69=(a69*a94);
  a69=(a71*a69);
  a96=(a96+a69);
  a35=(a35*a96);
  a60=(a87*a60);
  a45=(a85*a45);
  a60=(a60-a45);
  a67=(a67*a60);
  a87=(a87*a34);
  a85=(a85*a94);
  a87=(a87+a85);
  a71=(a71*a87);
  a67=(a67-a71);
  a17=(a17*a67);
  a35=(a35+a17);
  a3=(a3-a35);
  if (res[0]!=0) res[0][67]=a3;
  a66=(a66*a67);
  a101=(a101*a96);
  a66=(a66-a101);
  a103=(a103*a13);
  a66=(a66-a103);
  if (res[0]!=0) res[0][68]=a66;
  a91=(a91*a67);
  a5=(a5*a96);
  a91=(a91-a5);
  a102=(a102*a13);
  a91=(a91+a102);
  if (res[0]!=0) res[0][69]=a91;
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int f_J_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int f_J_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int f_J_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void f_J_release(int mem) {
}

CASADI_SYMBOL_EXPORT void f_J_incref(void) {
}

CASADI_SYMBOL_EXPORT void f_J_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int f_J_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real f_J_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* f_J_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* f_J_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int f_J_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_f_J(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[199];
  casadi_int *iw = 0;
  const casadi_real* arg[4] = {0};
  casadi_real* res[1] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+92);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s1, w+92);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+10, casadi_s2, w+92);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+16, casadi_s2, w+92);
  --resc;
  res[0] = w+22;
  i = f_J(arg, res, iw, w+92, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"f_J\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif

casadi_int main_f_J(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[199];
  const casadi_real* arg[4];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+7;
  arg[2] = w+10;
  arg[3] = w+16;
  res[0] = w+22;
  a = w;
  for (j=0; j<22; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = f_J(arg, res, iw, w+92, 0);
  if (flag) return flag;
  r = w+22;
  for (j=0; j<70; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[4];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_f_J(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "f_J")==0) {
    mex_f_J(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'f_J'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "f_J")==0) {
    return main_f_J(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'f_J'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
